### ISSUE TITLE
Server error when trying to delete file

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1381]
I've been having issues deleting files, where sometimes the file remains in the Files even though it's been deleted on the server; or the reverse, where the file disappears from the Files view but is not deleted on the server.  Unfortunately, it happens intermittently, and I haven't found a way to repeatedly recreate this issue.

However, I did see this exception in the server console.  Maybe this'll be helpful to find the root cause:

```
2011-12-14 18:47:36.825:WARN::ERROR:  /maqetta/cmd/deleteResource
java.lang.NullPointerException
    at maqetta.core.server.standalone.command.DeleteResource.handleCommand(DeleteResource.java:18)
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:126)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:317)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

@JonFerraiolo @peller

**Comment by childsb** [comment]
moving to m5 (can't recreate)

**Comment by childsb** [comment]
Fixed a bug around this for windows, but haven't seen the problem on OSX.  Closing.
