### ISSUE TITLE
Single user - don't redirect to welcome page after session timeout

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1503]
This one has been bothering me for a long time, and I've been debating about how bad this is, but I have concluded we need to fix before shipping Preview 4 because we still have tons of users who download the ZIP and run the single-user version of the application.

If you download a ZIP, run maqetta.local.mac.command or maqetta.local.win.bat, launch the Maqetta app, and then don't do anything for awhile, the server times out, and the next time you try to do something, you get redirected to the welcome page. But for single-user mode, we should never go to the welcome page. The user should somehow or other be able to merrily continue to use the Maqetta application without having to log back in (since there is no login with single user). I'm not sure exactly how to accomplish this in the best manner - maybe add a conditional to the redirect logic that determines whether the server was launched in single-user mode, and if so, then redirect to /maqetta rather than /maqetta/welcome?

**Comment by JonFerraiolo** [comment]
Actually, I'm not sure this is a valid bug anymore. I just waited for a couple of hours and there was no session timeout. I'll leave it overnight to see if there is a session timeout in the morning. Maybe @childsb can look at the code and say whether there is a session timeout for single-user mode and if there is a timeout what happens (e.g., redirect to welcome page)?

**Comment by JonFerraiolo** [comment]
I had a localhost:8081/maqetta single-user session open from yesterday and I went back to it today, and up came the page that says "click here to login", and when I clicked on the login link, I was take to the welcome.html page. But then I hit the back button and it brought me back into the page editor in single-user mode. The server console (in Eclipse) had this:

```
2012-01-09 10:07:40.464:WARN::ERROR:  /maqetta/cmd/findResource
java.lang.NullPointerException
    at maqetta.core.server.standalone.user.User.findFiles(User.java:619)
    at maqetta.core.server.standalone.command.FindResource.handleCommand(FindResource.java:28)
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:28)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:71)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:25)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
request: /welcome, logged in=true

```

Another issue is that I'm pretty sure that I had 2 workingcopy HTML files open but not saved, and upon returning to my session, those two files have gone away.

**Comment by childsb** [comment]
@JonFerraiolo was there a chance the server started and stopped between the sessions?

**Comment by JonFerraiolo** [comment]
I'm pretty sure the server was not restarted. The server log showed no signs of any restarts and I don't remember doing any restarts.

**Comment by childsb** [comment]
I checked in a fix to redirect local user to "." in 53445babb7da7f720773e3d44ca5b4d2f9422944

closing this bug.  if you find the findResource(...) error test case please open a new bug
