### ISSUE TITLE
NPE thrown in handleLibraryRequest

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1720]
@waynevicknair 

Perhaps this error is the result of migration?  The bug here isn't so much whatever state led to this error, but the error handling. The server code should surface the exception as an HTTP error rather than throwing a NullPointerError

This is the error frequently seen in nohup.out on maqetta.org:

2012-02-07 22:54:15.411:WARN::ERROR:  /maqetta/user/_Guest_1328065113877/ws/workspace/project1/themes/sketch/sketch.theme
java.lang.NullPointerException
    at maqetta.core.server.standalone.DavinciPageServlet.handleLibraryRequest(Unknown Source)
    at maqetta.core.server.standalone.DavinciPageServlet.handleWSRequest(Unknown Source)
    at maqetta.core.server.standalone.DavinciPageServlet.doGet(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:126)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by peller** [comment]
looks like it's got to be either user or path that's null

**Comment by childsb** [comment]
I'm marking this resolved.  If we see again on m5 production lets reopen.

**Comment by peller** [comment]
The issue isn't so much whether the condition persists as the error handling that should surface such exceptions

**Comment by peller** [comment]
I'm seeing it, still (Preview 5, running locally, but this time as single user)

DavinciPageServlet.java:268

```
IVResource libraryURL = user.getResource(path.toString());
```

Either 'user' is null or 'path' is null.  Perhaps it's not the same error seen on the live server (multi-user)  Based on the logging, it seems like path is defined?  Regardless, what we want I think is for the method to return false and then post a 404, so it might be as simple as checking for null, iff null is a valid value for either of those two vars.

Page Servlet request: /user/undefined/ws/workspace/project1/themes/android/android.theme, logged in=true
2012-03-27 18:33:11.889:WARN::ERROR:  /maqetta/user/undefined/ws/workspace/project1/themes/android/android.theme
java.lang.NullPointerException
    at maqetta.core.server.DavinciPageServlet.handleLibraryRequest(DavinciPageServlet.java:268)
    at maqetta.core.server.DavinciPageServlet.handleWSRequest(DavinciPageServlet.java:230)
    at maqetta.core.server.DavinciPageServlet.doGet(DavinciPageServlet.java:137)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:28)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:71)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:25)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by peller** [comment]
confirmed on maqetta.org (multiuser) on 2012-03-29 also.  No symbols there, but same stack, probably the same line.

**Comment by peller** [comment]
-> high.  This is causing a lot of noise in the logs, if nothing else.

**Comment by peller** [comment]
is the prefix `/maqetta/user/undefined/ws/workspace/...` in the logs a clue as to what might be wrong here?   I see that on the maqetta.org logs.

**Comment by childsb** [comment]
the "undefined" in the path makes me think that the user cookie on the client isn't set for some reason. do you have a way to recreate this by chance?  or any idea what you were doing when this happened?

**Comment by peller** [comment]
no idea, but it's all over the server log

**Comment by childsb** [comment]
can't reproduce.

**Comment by peller** [comment]
user cookie is gone in M6, right?  maybe this bug will go with it
