### ISSUE TITLE
Eclipse errors occur during the initial build

### ISSUE THREAD

**Issue by airazabal** [maqetta/maqetta#1878]
I followed the instructions in the tutorials, imported the project, so far so good. Eclipse started compiling my project and I came up with the following errors: 
Perhaps I am missing some required dependencies? J2EE?

!SESSION 2012-03-08 15:39:59.990 -----------------------------------------------
eclipse.buildId=I20110613-1736
java.version=1.6.0_29
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product -product org.eclipse.epp.package.rcp.product -product org.eclipse.epp.package.rcp.product -keyring /Users/alexirazabal/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.rcp.product -product org.eclipse.epp.package.rcp.product -data /Users/alexirazabal/Documents/workspaceforMaqetta -product org.eclipse.epp.package.rcp.product -keyring /Users/alexirazabal/.eclipse_keyring -showlocation

!ENTRY org.eclipse.core.resources 4 2 2012-03-08 15:40:52.851
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.ExceptionInInitializerError
    at org.eclipse.jst.j2ee.project.facet.EarFacetValidator.validate(EarFacetValidator.java:53)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectValidationBuilder.build(FacetedProjectValidationBuilder.java:132)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException: Project facet jst.ejb has not been defined.
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.getProjectFacet(FacetedProjectFrameworkImpl.java:234)
    at org.eclipse.wst.common.project.facet.core.ProjectFacetsManager.getProjectFacet(ProjectFacetsManager.java:75)
    at org.eclipse.jst.j2ee.project.facet.IJ2EEFacetConstants.<clinit>(IJ2EEFacetConstants.java:38)
    ... 14 more

!ENTRY org.eclipse.core.resources 4 75 2012-03-08 15:40:53.316
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.wst.common.project.facet.core 4 75 2012-03-08 15:40:53.316
!MESSAGE Errors running builder 'Faceted Project Validation Builder' on project 'maqetta_project'.
!STACK 0
java.lang.ExceptionInInitializerError
    at org.eclipse.jst.j2ee.project.facet.EarFacetValidator.validate(EarFacetValidator.java:53)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectValidationBuilder.build(FacetedProjectValidationBuilder.java:132)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException: Project facet jst.ejb has not been defined.
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.getProjectFacet(FacetedProjectFrameworkImpl.java:234)
    at org.eclipse.wst.common.project.facet.core.ProjectFacetsManager.getProjectFacet(ProjectFacetsManager.java:75)
    at org.eclipse.jst.j2ee.project.facet.IJ2EEFacetConstants.<clinit>(IJ2EEFacetConstants.java:38)
    ... 14 more

!ENTRY org.eclipse.core.resources 4 2 2012-03-08 15:41:21.954
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jst.j2ee.project.facet.IJ2EEFacetConstants
    at org.eclipse.jst.j2ee.project.facet.EarFacetValidator.validate(EarFacetValidator.java:53)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectValidationBuilder.build(FacetedProjectValidationBuilder.java:132)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.core.resources 4 75 2012-03-08 15:41:22.006
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.wst.common.project.facet.core 4 75 2012-03-08 15:41:22.006
!MESSAGE Errors running builder 'Faceted Project Validation Builder' on project 'maqetta_project'.
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jst.j2ee.project.facet.IJ2EEFacetConstants
    at org.eclipse.jst.j2ee.project.facet.EarFacetValidator.validate(EarFacetValidator.java:53)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectValidationBuilder.build(FacetedProjectValidationBuilder.java:132)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by peller** [comment]
It might have something to do with which Eclipse distro you use.  I don't believe we use j2ee or wst at all on the maqetta dev team.

**Comment by airazabal** [comment]
I am using the following:
Eclipse for RCP and RAP Developers

Version: Indigo Release
Build id: 20110615-0604

Is there another you recommend?

**Comment by jhpedemonte** [comment]
In the [Developer Setup](https://github.com/maqetta/maqetta/wiki/Developer-Setup), we recommend downloading the *\* Eclipse IDE for Java EE Developers*\* distribution, since that includes most of the components we need (even though we don't do J2EE).  I've used that and haven't run into any issues. (Never tried \* Eclipse for RCP and RAP Developers*)

@airazabal, do you think you could try that one and see if you get past the errors?

**Comment by airazabal** [comment]
Thanks Javier. 
I downloaded the J2EE 
Eclipse Java EE IDE for Web Developers.

Version: Indigo Service Release 2
Build id: 20120216-1857
and now have the following 4 errors:
Domo-theme-editor.html line 100
                            <div>
                                <input dojoType="dijit.form.CheckBox"
                                    type="checkBox"  class='dvThemeWidget'>CheckBox</input>
                            </div>
Attribute value (checkbox) uses wrong case character

then 3 of the same:
svg2gfx.xsl line 731, 789 1082:

```
    <xsl:apply-templates select="&SupportedElements;">
        <xsl:with-param name="groupAttrs" select="$newGroupAttrs"/>
    </xsl:apply-templates>
```

Xpath is invalid - referring to the '&' in the select statement...
Thanks for your prompt help on this ....

**Comment by peller** [comment]
SupportedElements is defined as an entity.  Perhaps the Eclipse validator is wrong. In any case, if there is a bug there, it would need to be filed against the Dojo Toolkit.
