### ISSUE TITLE
Switch themes broken with Eclipse projects

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2016]
@billreed63 

Don't know how we didn't notice this one until now.
- New Eclipse project
- Clone claro into claro2, change global background-color to green, save
- New HTML file, add a Button
- Switch themes to claro2

Result=> page goes blank. Console shows this:

```
GET http://lab9.austin.ibm.com:50020/maqetta/user/jferrai@us.ibm.com/ws/workspace/themes/claro2/claro2.css 404 (Not Found)
GET http://lab9.austin.ibm.com:50020/maqetta/user/jferrai@us.ibm.com/ws/workspace/lib/dojo/dojo/resources/dojo.css 404 (Not Found)
GET http://lab9.austin.ibm.com:50020/maqetta/user/jferrai@us.ibm.com/ws/workspace/app.css 404 (Not Found)
```

The URL paths above should have had `eproj4/WebContent/` somewhere inside. (my Eclipse project was "eproj4")

**Comment by billreed63** [comment]
The new themes dialog is pulling in all the themes from the base project as well, it should only be getting the theme's from the current project

**Comment by childsb** [comment]
there's a simpler scenario

((in project1 or new project of your choice)) 

1) new theme: claro2
2) new folder ffffffffffff
3) new html file, create it under ffffffffffff
4) add a button
5) switch themes to claro2

**Comment by billreed63** [comment]
All of the paths get corrupted after the theme switch

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "../../themes/claro1/claro1.css";@import "../../lib/dojo/dojo/resources/dojo.css";@import "../../app.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" src="../../lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'yui','location':'../../yui'},{'name':'oneui','location':'../../oneui'},{'name':'maqetta','location':'../../../'},{'name':'jquery-ui','location':'../../jquery-ui'}]"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dijit/form/Button"]);</script>
</head>
<body dvFlowLayout="true" data-davinci-ws="collapse" class="claro1" id="myapp">
 <input type="button" data-dojo-type="dijit.form.Button" label="Button"></input>
</body>
</html>
```

**Comment by billreed63** [comment]
I just pulled from git and deleted my user workspace, restarted the server multiuser

created a new user
new->theme and I see this in the server log

```
age Servlet request: /user/user3/ws/workspace/eproject/WebContent/themes/android/android.theme, logged in=true
2012-03-27 16:34:14.201:WARN::ERROR:  /maqetta/user/user3/ws/workspace/eproject/WebContent/themes/android/android.theme
java.lang.NullPointerException
    at maqetta.core.server.DavinciPageServlet.handleLibraryRequest(DavinciPageServlet.java:268)
    at maqetta.core.server.DavinciPageServlet.handleWSRequest(DavinciPageServlet.java:230)
    at maqetta.core.server.DavinciPageServlet.doGet(DavinciPageServlet.java:137)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:317)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

```

**Comment by childsb** [comment]
i can't reproduce bills stack dump on osx.

**Comment by billreed63** [comment]
this bit of code in PageEditor.setContent is the culprit

```
        if (this._isNewFile && this.resourceFile.parent!=system.resource.getRoot()) {
            var rootPath = new Path([]),
                newPath = new Path(this.resourceFile.getPath()).getParentPath(),
                updatePath = function (src) {
                    var fullPath=rootPath.append(src);
                    var newSrc=fullPath.relativeTo(newPath);
                    return newSrc.toString();
                };
            var visitor = {visit: function (element) {
                if (element.elementType=="HTMLElement") {
                    if (element.tag=="script") {
                        var src=element.getAttribute("src");
                        if (src) {
                            element.addAttribute("src",updatePath(src));
                        }
                    }
                } else if (element.elementType=="CSSImport") {
                    var newPath=updatePath(element.url);
                    element.url=newPath;
                }
            }
            };
            this.htmlEditor.model.visit(visitor);
        }
```

It mucks with the path of scripts and css files.... The question is why is it there? seems like we should remove it

**Comment by billreed63** [comment]
I have done some quik testing with the above code deleted and it seems to have no negative effects if we remove the code
