### ISSUE TITLE
Modify libraries fails

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2106]
1. Click on Mofidy Libraries button
2. Change lib/dojo to lib/mydojo/dojo and click OK
3. Notice library not moved in Files Palette (only message in console is warning: `davinci.js:45521metadata resource (javascript-module, maqetta/States) does not specify 'library'`)
4. Open Sample1.html and see error in (now) red VE pane:

```
Uh oh! An error has occurred:
xhrFailed
Error: xhrFailed at http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/mydojo/dojo/dojo/dojo.js:15:436 at Function.getText (http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/mydojo/dojo/dojo/dojo.js:15:2976) at http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/mydojo/dojo/dojo/dojo.js:15:14852 at http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/mydojo/dojo/dojo/dojo.js:15:328 at http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/mydojo/dojo/dojo/dojo.js:15:6324 at http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/mydojo/dojo/dojo/dojo.js:15:7002 at http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/mydojo/dojo/dojo/dojo.js:15:555 at [object Object]._require (http://localhost:50000/maqetta/app/davinci/davinci.js?2e74435c04a757c062b317d39e27792aaf0cbb2d:45575:35) at Object._44f [as forEach] (http://localhost:50000/maqetta/app/dojo/dojo.js?2e74435c04a757c062b317d39e27792aaf0cbb2d:5664:4) at [object Object].setHeader (http://localhost:50000/maqetta/app/davinci/davinci.js?2e74435c04a757c062b317d39e27792aaf0cbb2d:46098:6)
```

And, these errors show up in console:

```
dojo.js:15GET http://localhost:50000/maqetta/user/tonyErwin/ws/workspace/qqqqq/lib/maqetta/States.js 404 (Not Found)
davinci.js:45578FAILED: Context.js _require failure for module=maqetta/States
davinci.js:46243Context._restoreStates: this._loadFileStatesCache missing
6event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.
```

**Comment by childsb** [comment]
hey tony,

can you try to recreate again?  this is working for me on build and unbuilt.

**Comment by aerwin** [comment]
Yes, looks like this is working now. I'll close.
