### ISSUE TITLE
NPE in DavinciPageServlet.handleLibraryRequest

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#215]
Seeing many of the following errors from the server:

java.lang.NullPointerException
    at org.davinci.server.DavinciPageServlet.handleLibraryRequest(Unknown Source)
    at org.davinci.server.DavinciPageServlet.handleWSRequest(Unknown Source)
    at org.davinci.server.DavinciPageServlet.doGet(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:28)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:71)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:25)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:76)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

Might need to add logging of some sort to get more information.

**Comment by jhpedemonte** [comment]
Forgot to include some information.  Before the Java stack trace, the logs mention different files, such as:

WARN::ERROR:  /maqetta/user/_Guest_1303986828715/ws/workspace/welcome

WARN::ERROR:  /maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/StackController.js

WARN::ERROR:  /maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/ContentPane.js

WARN::ERROR:  /maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/StackContainer.js

WARN::ERROR:  /maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/MenuSeparator.js

WARN::ERROR:  /maqetta/user/_Guest_1303639043877/ws/workspace/Sample1.html

**Comment by childsb** [comment]
I believe this is fixed, please re-open with a test case if you can reproduce.
