### ISSUE TITLE
NPE in SaveFile.handleCommand()

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#218]
Many instances of this exception in server logs:

ERROR:  /maqetta/cmd/saveFile
java.lang.NullPointerException
    at org.davinci.server.internal.command.SaveFile.handleCommand(Unknown Source)
    at org.davinci.server.DavinciCommandServlet.doPut(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:730)
    at org.davinci.server.DavinciCommandServlet.service(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:28)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:71)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:25)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:939)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by jhpedemonte** [comment]
Similar exceptions with other commands:

2011-05-04 06:53:47.617:WARN::ERROR:  /maqetta/cmd/deleteResource
java.lang.NullPointerException
    at org.davinci.server.internal.command.DeleteResource.handleCommand(Unknown Source)
    at org.davinci.server.DavinciCommandServlet.doGet(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    ...

2011-04-29 09:07:52.265:WARN::ERROR:  /maqetta/cmd/rename
java.lang.NullPointerException
    at org.davinci.server.internal.command.Rename.handleCommand(Unknown Source)
    at org.davinci.server.DavinciCommandServlet.doGet(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    ...

2011-04-29 09:07:52.302:WARN::ERROR:  /maqetta/cmd/loadFile
java.lang.NullPointerException
    at org.davinci.server.internal.command.LoadFile.handleCommand(Unknown Source)
    at org.davinci.server.DavinciCommandServlet.doGet(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    ...

**Comment by childsb** [comment]
Fixed? Do you have a recreate scenario?  I'm guessing this was fixed with recent server changes.  Please reopen with recreate scenario if you can reproduce this.
