### ISSUE TITLE
Jetty exception when downloading files

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#219]
**A TON** of these exceptions in the server logs:

org.mortbay.jetty.EofException
    at org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:789)
    at org.mortbay.jetty.AbstractGenerator$Output.blockForOutput(AbstractGenerator.java:550)
    at org.mortbay.jetty.AbstractGenerator$Output.flush(AbstractGenerator.java:571)
    at org.mortbay.jetty.HttpConnection$Output.flush(HttpConnection.java:1006)
    at org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:650)
    at org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:579)
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:161)
    at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:118)
    at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:72)
    at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:91)
    at org.mortbay.servlet.GzipFilter$GzipStream.write(GzipFilter.java:498)
    at java.util.zip.ZipOutputStream.writeInt(ZipOutputStream.java:428)
    at java.util.zip.ZipOutputStream.writeEXT(ZipOutputStream.java:349)
    at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:208)
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:117)
    at org.davinci.server.internal.command.Download.zipFiles(Unknown Source)
    at org.davinci.server.internal.command.Download.zipDir(Unknown Source)
    at org.davinci.server.internal.command.Download.zipFiles(Unknown Source)
    at org.davinci.server.internal.command.Download.zipDir(Unknown Source)
    at org.davinci.server.internal.command.Download.zipFiles(Unknown Source)
    at org.davinci.server.internal.command.Download.zipDir(Unknown Source)
    at org.davinci.server.internal.command.Download.zipFiles(Unknown Source)
    at org.davinci.server.internal.command.Download.handleCommand(Unknown Source)
    at org.davinci.server.DavinciCommandServlet.doGet(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.davinci.server.DavinciCommandServlet.service(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:28)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:71)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:25)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcher.write0(Native Method)
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:29)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:104)
    at sun.nio.ch.IOUtil.write(IOUtil.java:60)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:302)
    at org.mortbay.io.nio.ChannelEndPoint.flush(ChannelEndPoint.java:169)
    at org.mortbay.io.nio.SelectChannelEndPoint.flush(SelectChannelEndPoint.java:221)
    at org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:723)
    ... 51 more

**Comment by childsb** [comment]
Fixed.
