### ISSUE TITLE
JS error when deleting new file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2549]
1. Create new HTML file
2. Right-click on file in File palette and choose delete
3. Click OK on the "are you sure?" dialog
4. Editor and file go away, but extra dialog that says "undefined" pops up and there are errors in console:

```
GET http://lab9.austin.ibm.com:50010/maqetta/cmd/deleteResource?path=.%2Fproject1%2Ffile1.html 500 (Internal Server Error) dojo.js:5022
dojo.xhr dojo.js:5022
dojo.xhrGet dojo.js:5034
_1fcd.serverJSONRequest davinci.js:44198
_25b1.deleteResource davinci.js:53006
_9cc.deleteAction davinci.js:11415
_9cc.deleteAction davinci.js:11413
davinci.actionSets.actions.run davinci.js:3114
_c2 dojo.js:568
_36 dojo.js:646
_16 dojo.js:370
_82 dojo.js:385
davinci.actionSets.actions.run davinci.js:3113
_3e9._runAction davinci.js:4801
_37e dojo.js:4535
_14ec.onItemClick davinci.js:26421
_1abe._onClick davinci.js:35416
_383 dojo.js:4551
_1e3 dijit.js:1936
Error
 dojo.js:4857
Error
 dojo.js:1746
dojo.Deferred.reject.errback dojo.js:1746
dojo.Deferred.reject.errback dojo.js:1747
_3cd dojo.js:4967
func dojo.js:4884
_3c6 dojo.js:4903
dojo._ioWatch dojo.js:4948
dojo.xhr dojo.js:5029
dojo.xhrGet dojo.js:5034
_1fcd.serverJSONRequest davinci.js:44198
_25b1.deleteResource davinci.js:53006
_9cc.deleteAction davinci.js:11415
_9cc.deleteAction davinci.js:11413
davinci.actionSets.actions.run davinci.js:3114
_c2 dojo.js:568
_36 dojo.js:646
_16 dojo.js:370
_82 dojo.js:385
davinci.actionSets.actions.run davinci.js:3113
_3e9._runAction davinci.js:4801
_37e dojo.js:4535
_14ec.onItemClick davinci.js:26421
_1abe._onClick davinci.js:35416
_383 dojo.js:4551
_1e3 dijit.js:1936
Error
arguments: undefined
get stack: function () { [native code] }
message: "Unable to load cmd/deleteResource?path=.%2Fproject1%2Ffile1.html status:500"
responseText: "<html>↵<head>↵<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>↵<title>Error 500 INTERNAL_SERVER_ERROR</title>↵</head>↵<body><h2>HTTP ERROR 500</h2>↵<p>Problem accessing /maqetta/cmd/deleteResource. Reason:↵<pre>    INTERNAL_SERVER_ERROR</pre></p><h3>Caused by:</h3><pre>java.lang.NullPointerException↵   at maqetta.core.server.command.DeleteResource.handleCommand(DeleteResource.java:21)↵  at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)↵ at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)↵  at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)↵  at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)↵  at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)↵ at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)↵    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)↵   at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)↵ at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)↵  at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)↵   at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)↵ at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)↵   at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)↵    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)↵  at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)↵  at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:317)↵  at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)↵    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)↵  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)↵  at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)↵  at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)↵  at org.mortbay.jetty.Server.handle(Server.java:326)↵  at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)↵   at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)↵   at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)↵   at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)↵  at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)↵  at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)↵  at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)↵</pre>↵<hr /><i><small>Powered by Jetty://</small></i><br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵<br/>                                                ↵↵</body>↵</html>↵"
set stack: function () { [native code] }
status: 500
type: undefined
xhr: XMLHttpRequest
__proto__: SetUpError.d
 dojo.js:1746

```

**Comment by jhpedemonte** [comment]
Perhaps this is similar to other issues and will work correctly now that you've cleared cookies?

**Comment by peller** [comment]
@childsb

would be great to figure out why a null exception is thrown, regardless.  I thought the cookie length issue threw a special http error code rather than a 500?

```
java.lang.NullPointerException↵
   at maqetta.core.server.command.DeleteResource.handleCommand(DeleteResource.java:21)
```

**Comment by aerwin** [comment]
No, don't think this has anything to do with the cookie issue. Happened before I ran into any cookie issues, and I just reproduced.
