### ISSUE TITLE
Review publish not working, throws error

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2658]
Tried to create a new review while running on lab9:50010, but got this error in the browser console:

```
"Unable to load http://lab9:50010/maqetta/cmd/publish status: 500"
```

Server log shows this:

```
2012-07-01 22:09:37.694:WARN::ERROR:  /maqetta/cmd/publish
java.lang.NullPointerException
        at maqetta.core.server.command.Publish.handleCommand(Publish.java:54)
        at org.maqetta.server.DavinciCommandServlet.doPost(DavinciCommandServlet.java:134)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        ...
```

---

Tested sendmail on that machine and it's working.  However, not sure what would have changed in build to break this.

@childsb

**Comment by aerwin** [comment]
Closing with above commit.
