### ISSUE TITLE
Need to strip out `dojo/connect` script tags for event handling

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2715]
@JonFerraiolo @jhpedemonte @billreed63 @childsb @peller @doronrosenberg 

For the work in #79, I enabled a number of features that required me start putting &lt;script&gt; blocks in our declarative HTML (which is new in Maqetta as far as I know). So, I'm opening this issue as a forum for discussion (and potential code changes) as I suspect we might end up with more of this moving forward and figured some group awareness should be raised for any precedents we might be setting.

For example, here is the output from dropping a tree onto a page and clicking OK on smart input:

```
 <div data-dojo-type="dojo.store.Memory" id="Memory_1" jsId="Memory_1" data="[{&quot;id&quot;:&quot;treeRoot&quot;,&quot;label&quot;:&quot;Root&quot;},{&quot;id&quot;:&quot;1&quot;,&quot;label&quot;:&quot;1&quot;,&quot;parent&quot;:&quot;treeRoot&quot;},{&quot;id&quot;:&quot;1.1&quot;,&quot;label&quot;:&quot;1.1&quot;,&quot;parent&quot;:&quot;1&quot;,&quot;leaf&quot;:&quot;true&quot;},{&quot;id&quot;:&quot;1.2&quot;,&quot;label&quot;:&quot;1.2&quot;,&quot;parent&quot;:&quot;1&quot;,&quot;leaf&quot;:&quot;true&quot;},{&quot;id&quot;:&quot;2&quot;,&quot;label&quot;:&quot;2&quot;,&quot;parent&quot;:&quot;treeRoot&quot;},{&quot;id&quot;:&quot;2.1&quot;,&quot;label&quot;:&quot;2.1&quot;,&quot;parent&quot;:&quot;2&quot;,&quot;leaf&quot;:&quot;true&quot;},{&quot;id&quot;:&quot;2.2&quot;,&quot;label&quot;:&quot;2.2&quot;,&quot;parent&quot;:&quot;2&quot;,&quot;leaf&quot;:&quot;true&quot;},{&quot;id&quot;:&quot;2.3&quot;,&quot;label&quot;:&quot;2.3&quot;,&quot;parent&quot;:&quot;2&quot;,&quot;leaf&quot;:&quot;true&quot;}]">
   <script type="dojo/method" data-dojo-event="getChildren" data-dojo-args="item">
     return this.query({parent: this.getIdentity(item)});</script>
 </div>
 <div data-dojo-type="dijit.tree.ObjectStoreModel" id="ObjectStoreModel_1" jsId="ObjectStoreModel_1" labelAttr="label" query="{&quot;id&quot;:&quot;treeRoot&quot;}" store="Memory_1">
   <script type="dojo/method" data-dojo-event="mayHaveChildren" data-dojo-args="item">
     return !item.leaf;</script>
 </div>
 <div data-dojo-type="dijit.Tree" autoExpand="true" showRoot="false" childrenAttr="children" openOnClick="false" openOnDblClick="false" persist="false" dndParams="onDndDrop,itemCreator,onDndCancel,checkAcceptance,checkItemAcceptance,dragThreshold,betweenThreshold" dragThreshold="5" style="min-height: 1em; width: 100%; height: auto;" model="ObjectStoreModel_1">
   <script type="dojo/method" data-dojo-event="getIconStyle" data-dojo-args="item, opened">var iconStyle = item.iconStyle;if (opened && item.iconStyleOpen) {   iconStyle = item.iconStyleOpen;};return iconStyle;</script>
   <script type="dojo/connect" data-dojo-event="onClick" data-dojo-args="item, node, evt">if (item.onClick) {   dojo.eval(item.onClick);};</script>
   <script type="dojo/connect" data-dojo-event="onDblClick" data-dojo-args="item, node, evt">if (item.onDblClick) {     dojo.eval(item.onDblClick);};</script>
   <script type="dojo/connect" data-dojo-event="onClose" data-dojo-args="item, node">if (item.onClose) {    dojo.eval(item.onClose);};</script>
   <script type="dojo/connect" data-dojo-event="onOpen" data-dojo-args="item, node">if (item.onOpen) {  dojo.eval(item.onOpen);};</script>
 </div>
```
- Issue 1: No 2-way editing of script blocks
  - We're not enabled to do any kind of two-way script editing, so I don't think we really want users modifying these script blocks. Should we somehow mark the blocks as Maqetta-generated and add a comment to the effect "JavaScript generated by Maqetta. Change at your own risk!"? Other ideas?
- Issue 2: Need to disable JS in script blocks (at least ones with `data-dojo-event` set to a value starting with "on") from running in page editor
  - Including here for discussion, but also covered in #2699 ("onOpen handler for tree node runs in page editor context when tree auto-expanded")
- Issue 3 (perhaps most controversial): currently use `dojo.eval` in event handlers (for example, see script block for data-dojo-event="onClick" above)
  - Comment I made a few days ago in #79: "on the back end (in the runtime JS) I end up leveraging dojo.eval. I'm not sure there are really any better alternatives, but I know some folks might worry about the use of dojo.eval so potentially worth a discussion"
  - If folks really don't think we should do this (and it's probably a bigger deal if the data is coming from an external source), then I think we'll need to limit the values we allow users to put in the _onclick_ field in tree smart input to be something we can "interpret". E.g., limit to the state events and some setting that indicates we should call a pre-defined function or something. Then, we could do something like the following:

```
<script type="dojo/connect" data-dojo-event="onClick" data-dojo-args="item, node, evt">
    //untested psuedo code...

    if (item.onClick) {     

       if (item.onClick.startsWith("davinci.states.setState") {
             //parse out state name from string of form "davinci.states.setState('Normal')" and call davinci.states.setState ourselves
            davinci.states.setStates(state string pulled out of item.onClick);
      }
     else if (item.onClick === "preDefinedEventHandler") { //some string that indicates they want to handle event themselves  
           //call out to some new pre-defined function in app.js they can extend?
           handleTreeEvent(treeId, item, node, evt);
    }
  }

</script>
```
- Of course, doing something like the above disallows entering things like `console.log('click!')` like we allow for `dijit.Button`'s, etc. in the event panel of the props palette
- Also, if we start adding more complex logic in our script blocks, we probably want to start calling some of our own pre-defined functions (potentially living in app.js?)

**Comment by jhpedemonte** [comment]
I'm still trying to understand this:  why exactly are the inline script elements needed?  What issue are they solving?

**Comment by aerwin** [comment]
Take the tree inline blocks as an example:
- getIconStyle -- the only way to modify the styling of tree node icons is to override the `dijit.Tree`'s `getIconStyle` or `getIconClass` functions and return values based on an examination of the item's state and properties
  - also... we're not yet supporting label or row styling in the tree, but same kind of thing would hold there (e.g., need to override `getLabelStyle` \ `getLabelClass` and `getRowStyle` \ `getRowClass`
- onClick -- in order to do handling of the click event for an individual node, we need to do a `dojo.connect` for the tree's `onClick` (same for `onDblClick`, `onOpen`, and `onClose`)

The only other alternative to script blocks would be to provide a brand new `maqetta.Tree` widget in a new widget library whose class definition overrides `getIconStyle` and does the `dojo.connect`'s. And, I don't think we really want to go down that path. :)

**Comment by aerwin** [comment]
Some more details on the comments in my last post: http://livedocs.dojotoolkit.org/dijit/Tree#betweenthreshold

**Comment by aerwin** [comment]
actually, http://livedocs.dojotoolkit.org/dijit/Tree goes to the top of the page, and http://livedocs.dojotoolkit.org/dijit/Tree#icons would take you to the section on icons...

**Comment by JonFerraiolo** [comment]
I'm totally fine with the current approach @aerwin has implemented already, including the use of `dojo.eval` in this context, so long as it actually works in all scenarios. Detailed comments:
- We already put a bunch of stuff in user HTML files that they better know what they are doing before they attempt to change. It's OK to put more stuff into the HTML file so long as we can justify it in terms of making things easier for the user to create useful pages without programming, and there was no other reasonable approach that we could use.
- "Maqetta-generated, don't touch" comments are a good idea wherever we can insert such comments without making the source code overly ugly. In this case, I would put any "don't touch" comments as HTML comments are children of widget root elements, versus putting the comments outside of the widget's root element.
- Regarding running dojo.eval, gosh, the browser will do an eval on the textual content of an onclick attribute anyway, all we are doing is one level of indirection, so while some people might say "wait a minute", in reality we aren't exposing any new vulnerabilities versus standard onclick vulnerabilities. And we need dojo.eval to get the whole thing to work.

But one worry I have is how the Maqetta page editor deals with SCRIPT tags and event attributes. Right now, on page parsing, the page editor puts SCRIPT tags and event attributes (e.g., onclick) into the model but not into the user iframe. But in this case, do we need the SCRIPT tag logic to run in the page editor, or only at runtime? I hope the answer is only at runtime. If so, then the helpers for Tree can follow the same approach: put SCRIPT tags into the model, but not into the user iframe.

**Comment by aerwin** [comment]
@JonFerraiolo thanks for the response...

One question you asked:

> But in this case, do we need the SCRIPT tag logic to run in the page editor, or only at runtime? 

We need the SCRIPT blocks of type "dojo/method" to be able to do their thing in the page editor as they provide overrides to the superclass. E.g., we need `getIconStyle`to run in the page editor otherwise we won't see the custom icons. And, similarly, for the `dojo.store.Memory` we need `getChildren` or the tree can't figure out the children for each node in order to render itself.

But, the SCRIPT blocks of type="dojo/connect" (for "onClick", etc.) do not need to be run in the page editor. These are the ones we need to disable (like we take steps in other cases that use `onClick`, etc. attributes directly on the element).

**Comment by JonFerraiolo** [comment]
> We need the SCRIPT blocks of type "dojo/method" to be able to do their thing in the page editor as they provide overrides to the superclass.

Hmm. Are you saying the page editor's policy would be to run SCRIPT tags with "dojo/method" but not any others? It seems like we will run into widgets where we would want to ignore "dojo/method". Is the decision about embedded SCRIPT tags up to the widget helpers? In that case, then we have the hooks for widget-specific decisions about embedded SCRIPT tag.

A follow-on question is whether widget.js:createWidget should scan the widget's "content" (from the OAM file and/or the widgets.json file) to look for embedded SCRIPT tags. My current thinking and analysis on that question is that we don't have to put a priority on that worry because the widget developer would have inserted those SCRIPT tags and we have to assume they know what they are doing.

One more question: have you tried putting the two store elements for the tree as children of the tree? If that works, then that might make various things cleaner and simpler in both the HTML source code and in our own code. (@billreed63)

**Comment by aerwin** [comment]
> Is the decision about embedded SCRIPT tags up to the widget helpers?

Nothing is currently in place for this to be determined by helpers. In #2699, you pointed me at the code that deactivates HTML event attributes. 

> We have logic in Maqetta to look for all HTML event attributes (e.g., onclick, onmouseover) and we deactivate those attributes in the page editor simply by removing those attributes when a page is viewed in the page editor. This is a nice general approach that required about 20 lines of code to pull off. Look at ve/widget.js:495, _Widget.js:468 and Context.js:1236 (search for "event attribute").

Quickly glancing at ve/widget.js (and without trying it), it seems like we could add a short block that strips out the data-dojo-event attributes for html.script elements that have type = "dojo/connect".

A new helper call could be invented, but seems a little like overkill at the moment (and kind of goes against recent statements by @jhpedemonte about the proliferation of helpers).

> One more question: have you tried putting the two store elements for the tree as children of the tree? If that works, then that might make various things cleaner and simpler in both the HTML source code and in our own code. (@billreed63)

No, but no reason to expect that would work. It's the same as any other data store based widget that we have where stores are separate entities outside of the widget. Which (while complicating our lives), is really what you want. E.g., in practice data stores are often used by widgets across the page. (Which I'm starting to worry about a bit for my toleration of dojo.mvc, but no reason to have that sepearate discussion here.)

**Comment by JonFerraiolo** [comment]
> about the proliferation of helpers

If we need a helper, we need a helper.

> seems a little like overkill at the moment

that one resonates more with me in this particular case

> no reason to expect that would work

I tried it and in fact it didn't work

So I believe that I'm fine with all of your proposals.

**Comment by aerwin** [comment]
During testing with the latest orion build, I'm seeing the following exception when I open the file containing the tree configured as part of running through the tree test case. I'm assuming it's because we're allowing the onOpen handler to run and in this case  the onOpen handler for one of the nodes contains `davinci.states.setState('myState',event)`. So, I'm guessing this will be resolved when this issue is addressed to not allow these kinds of handlers to run in the page editor.

```
ReferenceError
 "ReferenceError: davinci is not defined
    at eval (eval at <anonymous> (eval at <anonymous> (lib/dojo/dojo/_base/kernel.js)))
    at eval (native)
    at Object.d.eval (eval at <anonymous> (lib/dojo/dojo/_base/kernel.js))
    at eval (eval at <anonymous> (lib/dojo/dojo/parser.js))
    at lang.hitch (lib/dojo/dojo/_base/lang.js:375:55)
    at target.(anonymous function).dispatcher [as onOpen] (lib/dojo/dojo/aspect.js:94:38)
    at declare._expandNode (lib/dojo/dijit/Tree.js:1628:9)
    at lang.hitch (lib/dojo/dojo/_base/lang.js:375:55)
    at signalListener (lib/dojo/dojo/Deferred.js:37:21)
    at signalWaiting (lib/dojo/dojo/Deferred.js:28:4)
    ----------------------------------------
    rejected at signalDeferred (lib/dojo/dojo/Deferred.js:78:15)
    at signalListener (lib/dojo/dojo/Deferred.js:49:5)
    at signalWaiting (lib/dojo/dojo/Deferred.js:28:4)
    at Deferred.resolve (lib/dojo/dojo/Deferred.js:186:5)
    at declare._expandNode (lib/dojo/dijit/Tree.js:1610:26)
    at notify (lib/dojo/dojo/_base/Deferred.js:187:23)
    at complete (lib/dojo/dojo/_base/Deferred.js:168:4)
    at dojo.Deferred.resolve.callback (lib/dojo/dojo/_base/Deferred.js:215:4)
    at addResult (lib/dojo/dojo/DeferredList.js:54:10)
    at dojo.DeferredList.darray.forEach.resultList.(anonymous function) (lib/dojo/dojo/DeferredList.js:37:5)
    ----------------------------------------
[object Deferred]
    at Deferred.then.promise.then (lib/dojo/dojo/Deferred.js:246:24)
    at declare._expandNode (lib/dojo/dijit/Tree.js:1621:22)
    at declare.setChildItems.isExpandable (lib/dojo/dijit/Tree.js:425:21)
    at Object.array.forEach (lib/dojo/dojo/_base/array.js:240:15)
    at declare.setChildItems (lib/dojo/dijit/Tree.js:388:10)
    at declare._expandNode (lib/dojo/dijit/Tree.js:1609:11)
    at declare.getChildren (lib/dojo/dijit/tree/ObjectStoreModel.js:147:6)
    at lang.hitch (lib/dojo/dojo/_base/lang.js:375:55)
    at when (lib/dojo/dojo/when.js:40:12)
    at declare.getChildren (lib/dojo/dijit/tree/ObjectStoreModel.js:123:4)" 
```

**Comment by jhpedemonte** [comment]
> Are you saying the page editor's policy would be to run SCRIPT tags with "dojo/method" but not any others? It seems like we will run into widgets where we would want to ignore "dojo/method". Is the decision about embedded SCRIPT tags up to the widget helpers? In that case, then we have the hooks for widget-specific decisions about embedded SCRIPT tag.

I agree with Jon here:  we are making assumptions as to which scripts we will/will not want to run;  just because we do things one way to dijit.Tree doesn't mean that will apply to all widgets in the future.  As Jon states, we need to abstract this somehow and provide a mechanism so that each widget can make these decisions.

>  I'm assuming it's because we're allowing the onOpen handler to run

Don't we `on*` handlers from running in the VE?

**Comment by aerwin** [comment]
> > Are you saying the page editor's policy would be to run SCRIPT tags with "dojo/method" but not any others? It seems like we will run into widgets where we would want to ignore "dojo/method". Is the decision about embedded SCRIPT tags up to the widget helpers? In that case, then we have the hooks for widget-specific decisions about embedded SCRIPT tag.
> 
> I agree with Jon here:  we are making assumptions as to which scripts we will/will not want to run;  just because we do things one way to dijit.Tree doesn't mean that will apply to all widgets in the future.  As Jon states, we need to abstract this somehow and provide a mechanism so that each widget can make these decisions.

Could @jhpedemonte or @JonFerraiolo  give me an example of a case where "dojo/method" should not be "run"? 

And, really, it's not even a matter of "running" it... E.g., "dojo/method" is used to override a function in the superclass. So, you're essentially making a declarative subclass. To me that just doesn't make sense to add metadata and/or helpers to stop such subclassing from happening in the visual editor.

And, would we really add metadata that doesn't even have a current use case? E.g., I can certainly add "allowDojoMethod" to the package.json schema, but the default would be true and none of our current widgets would set it to false.

> Don't we [disable] on\* handlers from running in the VE?

Right, which is exactly why I'd argue for disabling "dojo/connect" without adding any additional metadata to do so. E.g. to be consistent with how we handle other similar cases. Are you saying we need to revisit that original design decision and add some sort of widget-specific metadata to control that? That doesn't really make sense to me either.

**Comment by aerwin** [comment]
@jhpedemonte @JonFerraiolo 

-> M8
-> Changing title to "Need to strip out `dojo/connect` script tags for event handling"

Had briefly started to look more closely at how to do this last night, but I noticed @JonFerraiolo deferred an issue that seems related this morning -- _Need better code for stripping out event attrs_ (#1804). Seems like this work should go somewhat hand in hand with that.

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med
