### ISSUE TITLE
maqetta.server.mac.command fails to launch

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2738]
@peller 

When running local install tests and tried to run maqetta.server.mac.command, the command line console shows the following text, and the server doesn't launch. The local install script works fine, and no problems with either launch script on Windows (server or local).

@peller - could ZAZL be causing any problems? Just a guess. There is an issue on Macs where sometimes folders get 700 permissions.

```
Last login: Thu Jul 12 16:53:56 on ttys000
jonferraiolomacbookpro:~ jonferraiolo$ /Users/jonferraiolo/maqettaBuilds/20120712-lab9-external/maqetta.server.mac.command ; exit;
Java version=1.6

!!!!!!!!!!!!!!
NOTE: CLOSING THIS WINDOW WILL
STOP THE MAQETTA SERVER PROCESS
!!!!!!!!!!!!!

Using jar: /Users/jonferraiolo/maqettaBuilds/20120712-lab9-external/plugins/org.eclipse.equinox.launcher_1.2.0.v20110502.jar
Using directory: /Users/jonferraiolo/maqettaBuilds/20120712-lab9-external/users
Start your browser at: http://localhost:50000/maqetta

osgi> FATAL!!!!! User directory does not exist.
FATAL ERROR Starting maqetta: java.lang.NullPointerException
FATAL!!!!! User directory does not exist.
org.eclipse.core.runtime.CoreException: Plug-in "maqetta.core.server.standalone" was unable to instantiate class "maqetta.core.server.user.manager.PersonManagerImpl".
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:186)
    at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.maqetta.server.ServerManager.getPersonManager(ServerManager.java:234)
    at maqetta.core.server.user.manager.UserManagerImpl.<init>(UserManagerImpl.java:43)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
    at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.maqetta.server.ServerManager.getUserManager(ServerManager.java:130)
    at maqetta.zazl.Activator.register(Activator.java:80)
    at maqetta.zazl.Activator$HttpServiceTracker.addingService(Activator.java:124)
    at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:980)
    at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
    at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:262)
    at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:185)
    at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:348)
    at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:283)
    at maqetta.zazl.Activator.start(Activator.java:40)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
    at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:389)
    at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1130)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.NullPointerException
    at org.maqetta.server.ServerManager.getBaseDirectory(ServerManager.java:262)
    at maqetta.core.server.user.manager.PersonManagerImpl.getBaseDirectory(PersonManagerImpl.java:107)
    at maqetta.core.server.user.manager.PersonManagerImpl.loadUsers(PersonManagerImpl.java:185)
    at maqetta.core.server.user.manager.PersonManagerImpl.<init>(PersonManagerImpl.java:114)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
    ... 40 more
Registering Zazl JavaScript servlet
Registering Maqetta HTML Filter for Zazl
```

**Comment by JonFerraiolo** [comment]
Withdrawing. I rebooted and then no problem with the maqetta.server.mac.command. I'm not sure what was wrong.
