### ISSUE TITLE
Cannot register new user

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2745]
I cannot register a new user on lab9:50010.  Get the following error in the server log file:

```
2012-07-13 10:27:27.389:WARN::ERROR:  /maqetta/cmd/register
java.lang.NullPointerException
        at maqetta.core.server.user.manager.UserManagerImpl.checkUserExists(UserManagerImpl.java:170)
        at maqetta.core.server.user.manager.UserManagerImpl.addUser(UserManagerImpl.java:107)
        at maqetta.core.server.command.Register.handleCommand(Register.java:38)
        at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
        at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        ...
```

**Comment by jhpedemonte** [comment]
Fixed by commit 392fd36287630740b40b9e761cbc969c37764df6.
