### ISSUE TITLE
zazl error on preview

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2766]
I was doing the Gridx Data Column test case:
1) new HTML file
2) DND gridx
3) Select file, choose file from workspace samples/sample_data/sampleManyColumns.json
4) click preview in browser.

Ran into this error:

```
HTTP ERROR 500

Problem accessing /maqetta/user/bradley/ws/workspace/project2/file1.html. Reason:

    0
Caused by:

java.lang.ArrayIndexOutOfBoundsException: 0
    at maqetta.zazl.MaqettaHTMLFilter$ServletOutputStreamWrapper.toString(MaqettaHTMLFilter.java:153)
    at maqetta.zazl.MaqettaHTMLFilter$ResponseWrapper.toString(MaqettaHTMLFilter.java:216)
    at maqetta.zazl.MaqettaHTMLFilter.doFilter(MaqettaHTMLFilter.java:96)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:317)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by rbackhouse** [comment]
I just tried this out from the eclipse dev env and it worked fine. Was this observed while running via the maqetta server ?

**Comment by peller** [comment]
only seems to occur with a build, and only for empty files (no requires)  Drop a widget on the page and all is well.

**Comment by peller** [comment]
When dropping a gridx widget on the page, I see this:

```

Failed to load resource: the server responded with a status of 500 (AST parsing error for [gridx/Grid] error : Unable to obtain source for Module [/maqetta/user/peller/ws/workspace/project1/lib/dojo/gridx/model/Model]) http://lab9.austin.ibm.com:50010/_javascript?modules=dijit/dijit,dojo/parser,maqetta/space,maqetta/AppStates,dijit/form/Button,dojox/io/xhrScriptPlugin,dojo/data/ItemFileReadStore,gridx/Grid,gridx/core/model/cache/Async,dojox/data/CsvStore&writeBootstrap=false&locale=en-us&config=%7B%22directInject%22%3Atrue%2C%22injectUrl%22%3A%22%2F_javascript%22%2C%22packages%22%3A%5B%7B%22name%22%3A%22dojo%22%2C%22location%22%3A%22lib%2Fdojo%2Fdojo%22%2C%22main%22%3A%22main%22%7D%2C%7B%22name%22%3A%22dijit%22%2C%22location%22%3A%22lib%2Fdojo%2Fdijit%22%2C%22main%22%3A%22main%22%7D%2C%7B%22name%22%3A%22dojox%22%2C%22location%22%3A%22lib%2Fdojo%2Fdojox%22%2C%22main%22%3A%22main%22%7D%5D%2C%22paths%22%3A%7B%22maqettaSamples%22%3A%22samples%22%2C%22maqetta%22%3A%22lib%2Fmaqetta%22%2C%22DojoThemes%22%3A%22themes%22%2C%22gridx%22%3A%22lib%2Fdojo%2Fgridx%22%2C%22clipart%22%3A%22lib%2Fclipart%22%2C%22shapes%22%3A%22lib%2Fshapes%22%7D%2C%22baseUrl%22%3A%22%2Fmaqetta%2Fuser%2Fpeller%2Fws%2Fworkspace%2Fproject1%2F%22%2C%22scanCJSRequires%22%3Afalse%2C%22debug%22%3Afalse%7D&exclude=

```

I think it's just that the packages config info is missing.  The zazl plugin is generating paths instead, and it doesn't seem to be the right path.  I think it should just have an entry for gridx: ../gridx

**Comment by rbackhouse** [comment]
It looks like gridx is being built via the dojo builder and that is what is being used in built version. Just like Dojo Zazl requires the gridx code to be available in src form for it to be able to analyze correctly.
