### ISSUE TITLE
JS error reopening file in Widget Palette: Mobile Data test case

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2832]
Using Chrome on Mac... and doing "EdgeToEdgeDataList: Comma separated data" section of "Widget Palette: Mobile Data Store Based (Basic)" test case...

This doesn't appear to have a functional impact as far as I can tell (so making Sev 3 severity), but when I reopen the file I see the following exception:

```
Error in event handler for 'undefined': Cannot read property 'id' of null TypeError: Cannot read property 'id' of null
    at Object.prepareImgLinks (chrome-extension://nonjdcjchghhkdoolnlbekcfllmednbl/plugins/ipboard_a.js:9:20)
    at prepareImgLinks (chrome-extension://nonjdcjchghhkdoolnlbekcfllmednbl/js/hoverzoom.js:576:25)
    at init (chrome-extension://nonjdcjchghhkdoolnlbekcfllmednbl/js/hoverzoom.js:948:4)
    at applyOptions (chrome-extension://nonjdcjchghhkdoolnlbekcfllmednbl/js/hoverzoom.js:670:4)
    at chrome-extension://nonjdcjchghhkdoolnlbekcfllmednbl/js/hoverzoom.js:709:5
    at miscellaneous_bindings:283:9
    at [object Object].dispatch (event_bindings:203:41)
    at Object.<anonymous> (miscellaneous_bindings:250:22) event_bindings:207
chrome.Event.dispatch event_bindings:207
chromeHidden.Port.dispatchOnMessage miscellaneous_bindings:250
```

**Comment by jhpedemonte** [comment]
-> @doronrosenberg

**Comment by doronrosenberg** [comment]
@aerwin I see a chrome-extension error in there, do you have any chrome extensions installed?

**Comment by aerwin** [comment]
@doronrosenberg Yes, lots of Chrome extensions. :) I should have noticed that when I opened the defect... guess I didn't look closely enough. I'll go ahead and close.
