### ISSUE TITLE
Building maq+orion w/ Zazl fails

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2941]
@peller 

I created the branch `zazl-build` to try to resolve this, and it is being built on lab9.  There were a couple commits from Brad in order to enable building Zazl, but it currently fails with this error:

> BUILD FAILED
> /var/lib/jenkins/jobs/zazl-build/workspace/repository/maqetta/releng/davinci.releng/orion/buildAll.xml:21: The following error occurred while executing this line:
> /var/lib/jenkins/jobs/zazl-build/workspace/repository/maqetta/releng/davinci.releng/orion/buildAll.xml:105: The following error occurred while executing this line:
> /var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/scripts/productBuild/productBuild.xml:42: The following error occurred while executing this line:
> /var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/scripts/build.xml:91: The following error occurred while executing this line:
> /var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/templates/headless-build/customTargets.xml:12: The following error occurred while executing this line:
> /var/lib/jenkins/jobs/zazl-build/workspace/repository/maqetta/releng/davinci.releng/orion/builder/allElements.xml:16: The following error occurred while executing this line:
> /var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/scripts/genericTargets.xml:111: Processing inclusion from feature maqetta.zazl.feature: Unable to find plug-in: maqetta.zazl_0.0.0. Please check the error log for more details.

---

**Tasks:** _(updated 2012-08-23)_
- ~~Build with Zazl plugins.~~
- Fix server launch [error](https://github.com/maqetta/maqetta/issues/2941#issuecomment-7905633) (workaround is to [use "-clean"](https://github.com/maqetta/maqetta/issues/2941#issuecomment-7952703)).

**Comment by jhpedemonte** [comment]
The file **maqetta.zazl.feature/feature.xml** lists several plugins, including _maqetta.zazl_.

The file **maqetta.orion.feature/feature.xml** is similar, listing plugins such as _maqetta.core.client_ and _davinci.dojo_1_8_.  These plugins can be found in **$WORKSPACE/I201208141846/plugins/**.

However, none of the plugins listed in **maqetta.zazl.feature/feature.xml** are in that _plugins_ directory.  Is this the reason for the error?  The PDE Build process is trying to find the _maqetta.zazl_ plugin in that _plugins_ dir?

**Comment by jhpedemonte** [comment]
From the log file, here's the start of the section that handles **maqetta.orion.feature**:

```

GitFetchElementFromLocalRepo:
     [copy] Copying 3 files to /var/lib/jenkins/jobs/zazl-build/workspace/I201208141846/features/maqetta.orion.feature

fetch.plugins:

GitUpdateLocalRepo:
     [echo] [GIT] /var/lib/jenkins/jobs/zazl-build/workspace/gitClones/https___github_com_maqetta_maqetta_git >> git fetch

GitCheckSkipClone:

GitCloneRepoToLocalRepo:

GitCheckoutTagInLocalRepo:
     [echo] [GIT] /var/lib/jenkins/jobs/zazl-build/workspace/gitClones/https___github_com_maqetta_maqetta_git >> git checkout --force zazl-build
     [exec] Already on 'zazl-build'

GitFetchElementFromLocalRepo:
     [copy] Copying 9860 files to /var/lib/jenkins/jobs/zazl-build/workspace/I201208141846/plugins/maqetta.core.client
```

And here's the failing section that tries to handle **maqetta.zazl.feature**:

```

GitFetchElementFromLocalRepo:
     [copy] Copying 3 files to /var/lib/jenkins/jobs/zazl-build/workspace/I201208141846/features/maqetta.zazl.feature

fetch.plugins:

FetchIUsFromRepo:
     [echo] Fetching IUs from http://download.eclipse.org/tools/orbit/downloads/drops/R20120526062928/repository to /var/lib/jenkins/jobs/zazl-build/workspace/target/transformedRepos.

fetch.recursively:

postFetch:

jsdocs:

requirejs:

generateFeature:

generate:

preGenerate:

allElements:

allElementsDelegator:

init:

generateScript:

BUILD FAILED
```

---

For whatever reason, the build doesn't invoke `GitFetchElementFromLocalRepo` in order to copy over the Zazl plugins from the local repo.

**Comment by jhpedemonte** [comment]
Latest breakage (building from `zazl-build` branch):

```
generateFeature:
[eclipse.generateFeature] Some inter-plug-in dependencies have not been satisfied.
[eclipse.generateFeature] Bundle org.eclipse.orion.server.authentication.openid.core:
[eclipse.generateFeature]   Unsatisfied import package org.json_0.0.0.
[eclipse.generateFeature] Bundle maqetta.server.orion.standard:
[eclipse.generateFeature]   Missing required plug-in maqetta.server.orion_1.0.0.
[eclipse.generateFeature]   Unsatisfied import package org.json_0.0.0.
[eclipse.generateFeature] Bundle org.eclipse.orion.client.users:
[eclipse.generateFeature]   Unsatisfied import package org.json_0.0.0.
[eclipse.generateFeature] Bundle org.eclipse.orion.server.authentication.formopenid:
[eclipse.generateFeature]   Missing required plug-in org.eclipse.orion.server.authentication.openid.core_0.1.0.
[eclipse.generateFeature] Bundle maqetta.server.orion:
[eclipse.generateFeature]   Unsatisfied import package org.json_0.0.0.

generate:
preGenerate:

allElements:

allElementsDelegator:

init:

generateScript:
[eclipse.buildScript] Some inter-plug-in dependencies have not been satisfied.
[eclipse.buildScript] Bundle org.eclipse.orion.server.authentication.openid.core:
[eclipse.buildScript]   Unsatisfied import package org.json_0.0.0.
[eclipse.buildScript] Bundle maqetta.server.orion.standard:
[eclipse.buildScript]   Missing required plug-in maqetta.server.orion_1.0.0.
[eclipse.buildScript]   Unsatisfied import package org.json_0.0.0.
[eclipse.buildScript] Bundle org.eclipse.orion.client.users:
[eclipse.buildScript]   Unsatisfied import package org.json_0.0.0.
[eclipse.buildScript] Bundle org.eclipse.orion.server.authentication.formopenid:
[eclipse.buildScript]   Missing required plug-in org.eclipse.orion.server.authentication.openid.core_0.1.0.
[eclipse.buildScript] Bundle maqetta.server.orion:
[eclipse.buildScript]   Unsatisfied import package org.json_0.0.0.
BUILD FAILED
/var/lib/jenkins/jobs/zazl-build/workspace/repository/maqetta/releng/davinci.releng/orion/buildAll.xml:21: The following error occurred while executing this line:
/var/lib/jenkins/jobs/zazl-build/workspace/repository/maqetta/releng/davinci.releng/orion/buildAll.xml:105: The following error occurred while executing this line:
/var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/scripts/productBuild/productBuild.xml:42: The following error occurred while executing this line:
/var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/scripts/build.xml:91: The following error occurred while executing this line:
/var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/templates/headless-build/customTargets.xml:12: The following error occurred while executing this line:
/var/lib/jenkins/jobs/zazl-build/workspace/repository/maqetta/releng/davinci.releng/orion/builder/allElements.xml:16: The following error occurred while executing this line:
/var/lib/jenkins/jobs/zazl-build/workspace/support/org.eclipse.releng.basebuilder_R3_7/plugins/org.eclipse.pde.build_3.7.0.v20110512-1320/scripts/genericTargets.xml:111: Bundle org.eclipse.orion.server.authentication.formopenid_0.3.0.v20120619-1547 failed to resolve.:
    Missing required plug-in org.eclipse.orion.server.authentication.openid.core_0.1.0.
```

**Comment by jhpedemonte** [comment]
OK, now that builds are back to normal, I tested this against one of the latest builds.  But Zazl still doesn't seem to be working.  I don't see anything Zazl related in the Network panel when loading a Preview page.

**Comment by jhpedemonte** [comment]
While I could start a Maqetta+Orion+Zazl build once, subsequent times led to an error.  Also, the first time the server did load, I loaded Maqetta but Zazl did not seem to be working.

-> @peller, cc @rbackhouse 

Here's the error, don't know what it means:

```
!SESSION 2012-08-20 16:50:03.256 -----------------------------------------------
eclipse.buildId=I20120627-1350
java.version=1.6.0_33
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Command-line arguments:  -console

!ENTRY org.eclipse.osgi 4 0 2012-08-20 16:50:03.946
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:734)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
    at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:225)
    at org.eclipse.osgi.framework.internal.core.Framework.launch(Framework.java:657)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:274)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.lang.IllegalStateException: Expected to find an object at table index: 192
    at org.eclipse.osgi.internal.resolver.StateReader.getFromObjectTable(StateReader.java:83)
    at org.eclipse.osgi.internal.resolver.StateReader.readGenericDescription(StateReader.java:600)
    at org.eclipse.osgi.internal.resolver.StateReader.readBundleDescriptionLazyData(StateReader.java:350)
    at org.eclipse.osgi.internal.resolver.StateReader.fullyLoad(StateReader.java:823)
    at org.eclipse.osgi.internal.resolver.BundleDescriptionImpl.loadLazyData(BundleDescriptionImpl.java:662)
    at org.eclipse.osgi.internal.resolver.BundleDescriptionImpl.getExportPackages(BundleDescriptionImpl.java:160)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.setFrameworkVersion(PackageAdminImpl.java:706)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.setResolvedBundles(PackageAdminImpl.java:656)
    at org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start(SystemBundleActivator.java:67)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
    ... 13 more
Root exception:
java.lang.IllegalStateException: Expected to find an object at table index: 192
    at org.eclipse.osgi.internal.resolver.StateReader.getFromObjectTable(StateReader.java:83)
    at org.eclipse.osgi.internal.resolver.StateReader.readGenericDescription(StateReader.java:600)
    at org.eclipse.osgi.internal.resolver.StateReader.readBundleDescriptionLazyData(StateReader.java:350)
    at org.eclipse.osgi.internal.resolver.StateReader.fullyLoad(StateReader.java:823)
    at org.eclipse.osgi.internal.resolver.BundleDescriptionImpl.loadLazyData(BundleDescriptionImpl.java:662)
    at org.eclipse.osgi.internal.resolver.BundleDescriptionImpl.getExportPackages(BundleDescriptionImpl.java:160)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.setFrameworkVersion(PackageAdminImpl.java:706)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.setResolvedBundles(PackageAdminImpl.java:656)
    at org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start(SystemBundleActivator.java:67)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
    at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:225)
    at org.eclipse.osgi.framework.internal.core.Framework.launch(Framework.java:657)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:274)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

!ENTRY org.eclipse.osgi 4 0 2012-08-20 16:50:03.948
!MESSAGE Startup error
!STACK 1
java.lang.RuntimeException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
    at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:233)
    at org.eclipse.osgi.framework.internal.core.Framework.launch(Framework.java:657)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:274)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:734)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
    at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:225)
    ... 11 more
Caused by: java.lang.IllegalStateException: Expected to find an object at table index: 192
    at org.eclipse.osgi.internal.resolver.StateReader.getFromObjectTable(StateReader.java:83)
    at org.eclipse.osgi.internal.resolver.StateReader.readGenericDescription(StateReader.java:600)
    at org.eclipse.osgi.internal.resolver.StateReader.readBundleDescriptionLazyData(StateReader.java:350)
    at org.eclipse.osgi.internal.resolver.StateReader.fullyLoad(StateReader.java:823)
    at org.eclipse.osgi.internal.resolver.BundleDescriptionImpl.loadLazyData(BundleDescriptionImpl.java:662)
    at org.eclipse.osgi.internal.resolver.BundleDescriptionImpl.getExportPackages(BundleDescriptionImpl.java:160)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.setFrameworkVersion(PackageAdminImpl.java:706)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.setResolvedBundles(PackageAdminImpl.java:656)
    at org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start(SystemBundleActivator.java:67)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
    ... 13 more
```

**Comment by rbackhouse** [comment]
Is the build available somewhere for me to download and try myself ?

**Comment by rbackhouse** [comment]
Javier got me a copy of the build. Thanks

Re: Zazl not starting

This product assembly is using Eclipse P2 to provision instead of a simple config.ini file that details the bundles that are to be activated. P2 is not activating the maqetta.zazl bundle which creates and starts the Zazl servlet and Filter. I'm not much of a P2 expert to know how the maqetta.zazl bundle can be configured to start automatically though.

Also when I manually started the bundle I ran into another issue. It looks like orion is providing an org.json bundle which is colliding with the org.json bundle that zazl depends on. The orion one is the java JSON code and zazl's the javscript JSON code. I think we will have to rename the Zazl dependency (I say this as we can actually do this whereas orion probably won't be so flexibile). Renaming to org.json.js actually better reflects its content anyways.

I also saw the above errors on subsequent starts. It looks like the OSGi system bundles is failing pretty badly. I don't think this is anything that the zazl bundles are causing though.

**Comment by rbackhouse** [comment]
Its seems that the product file is where the activate bundle configuration needs to be set.

**Comment by jhpedemonte** [comment]
@rbackhouse, so you'll take care of renaming the JSON dependency?

@childsb, I'll need help fixing the other things listed above.

**Comment by rbackhouse** [comment]
@jhpedemonte, yes, I can take care of that, although it is more intrusive that I had hoped. It will require an update to both the optimizer-release and optimizer-dependencies submodules along with any refs to org.json that are in the maqetta repo. (That includes any releng/eclipse config files etc).

**Comment by jhpedemonte** [comment]
@rbackhouse, great.  Let me know if you need anything from me.  After the rename commit, I can work with @childsb to get the other parts going.

**Comment by rbackhouse** [comment]
The changes are committed. I think I got all the product and releng refs to the org.json bundle converted. Note that the new org.json.js project will have to be imported into developers workspaces and the old "org.json" deleted.

**Comment by peller** [comment]
-> @childsb

**Comment by jhpedemonte** [comment]
OK, after @rbackhouse's changes, I made changes to get Zazl building and automatically starting again (on _zazl-build_ branch).  However, I'm running into the same issue: starts up just fine the first time, but afterwards, starting the server errors out (same error [as before](https://github.com/maqetta/maqetta/issues/2941#issuecomment-7905633)).

**Comment by jhpedemonte** [comment]
If I move aside the `configuration/org.eclipse.osgi` directory, then I can successfully start the server.  Here are the contents:

```
org.eclipse.osgi
org.eclipse.osgi/.bundledata.1
org.eclipse.osgi/.lazy.1
org.eclipse.osgi/.manager
org.eclipse.osgi/.manager/.fileTable.4
org.eclipse.osgi/.manager/.fileTable.5
org.eclipse.osgi/.manager/.fileTableLock
org.eclipse.osgi/.state.1
org.eclipse.osgi/bundles
org.eclipse.osgi/bundles/108
org.eclipse.osgi/bundles/108/data
org.eclipse.osgi/bundles/110
org.eclipse.osgi/bundles/110/data
org.eclipse.osgi/bundles/110/data/jettywork
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1009061070
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1009328066
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1077451042
...
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1809367110/proxytemp
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1809367110/proxytemp/hc_1002051732
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1809367110/proxytemp/hc_1066113372
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1809367110/proxytemp/hc_1531485190
...
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1854740480
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1877581236
org.eclipse.osgi/bundles/110/data/jettywork/pid_-521425485/proxytemp/hc_1883341406
...
org.eclipse.osgi/bundles/22
org.eclipse.osgi/bundles/22/2
org.eclipse.osgi/bundles/22/2/.cp
org.eclipse.osgi/bundles/22/2/.cp/lib
org.eclipse.osgi/bundles/22/2/.cp/lib/activation.jar
org.eclipse.osgi/bundles/22/2/.cp/lib/mail.jar
org.eclipse.osgi/bundles/77
org.eclipse.osgi/bundles/77/2
org.eclipse.osgi/bundles/77/2/.cp
org.eclipse.osgi/bundles/77/2/.cp/os
org.eclipse.osgi/bundles/77/2/.cp/os/macosx
org.eclipse.osgi/bundles/77/2/.cp/os/macosx/libunixfile_1_0_0.jnilib
```

This directory doesn't exist in the downloaded build;  it is created after the first launch of the server.

**Comment by jhpedemonte** [comment]
Removing the directory `configuration/org.eclipse.osgi/.manager` seems to do the trick. It's got a couple of `.fileTable` files that generally look like this:

```
#safe table
#Wed Aug 22 15:08:18 CDT 2012
.bundledata=3
.state=2
.lazy=2
.crc0707aa30.v1
```

**Comment by jhpedemonte** [comment]
I am at a loss here.  For some reason, running with the Zazl plugins causes the OSGi object table to be incorrectly generated, making subsequent starts fail.  @rbackhouse, any chance that the maqetta.zazl plugin is doing something funky, maybe in Activator.java?

Workaround would be to always start with `-clean` (which removes the offending files), but I'd really like to figure out what the issue is.

**Comment by rbackhouse** [comment]
I don't think the maqetta.zazl bundle is causing the problem. I went back to a clean version of the build you gave me and ran it the first time without starting the maqetta.zazl bundle at all. Stopping and starting again resulted in the same "java.lang.IllegalStateException: Expected to find an object at table index" error.

**Comment by jhpedemonte** [comment]
Hmm, this only seems to happen with builds that have the Zazl plugins (might not be required to actually start Zazl).  Might be an issue with how we include Zazl into the build?

I've seen many mentions of the `IllegalStateException: Expected to find an object at table index` error online, but unfortunately no obvious solutions.

**Comment by rbackhouse** [comment]
It could be this equinox bug 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=375650. 

There is a fragment bundle that is being provided by the maqetta zazl code.

**Comment by jhpedemonte** [comment]
As far as I know, we are building against 4.2 final, which should contain that fix.

**Comment by rbackhouse** [comment]
The org.eclipse.osgi bundle that I see in the build has a filename of org.eclipse.osgi_3.8.0.v20120529-1548 which indicates that it was built May 29 2012. This the 375650 bug fix was not delivered until July 13. 

It may or may not actually resolve the problem we have but reading all the similar problems that result in a stack trace like this I would say this is not something that a bundle can be causing by doing something wrong. The OSGi internal storage is getting corrupted and that is not something bundles have access to. That has to be an Equinox bug.

**Comment by jhpedemonte** [comment]
I built against the Eclipse 4.3 Integration builds, which pulled in **org.eclipse.osgi_3.8.100.v20120820-131721.jar**.  Still see the same issue.

Either the fix in that bug didn't work, or it is not included in this version of the OSGi plugin.

That bug mentions that the fix went into Juno SR1 -- Juno === 4.2, right?  But plugin still shows 3.8.

If we want Zazl in for M7, we'll have to go with always running `-clean` on startup.

**Comment by jhpedemonte** [comment]
Re-enabled the Zazl build on _master_ and added the "-clean" argument when launching the server.  This workaround will do for M7.

Pushing this to M8 for further investigation then.  Hopefully we can fix this and remove "-clean".

**Comment by rbackhouse** [comment]
I think to get this resolved we will have to file a bug report against equinox giving them the corrupted files. We may also have to provide a runnable example that demonstrates the failure. Should be as simple as providing a build and instructing how to remove the -clean. Hopefully they won't balk at the size of the example.

**Comment by jhpedemonte** [comment]
-> M9
