### ISSUE TITLE
create gridx fails first time with async:true

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2963]
Now that async has been turned on, the first time you dnd a gridx onto the canvas, it fails.  There are no error messages to the console.  Subsequent attempts work fine.

@aerwin, please assess.  I can back out the async bit if necessary.

**Comment by peller** [comment]
Now I see this message in the console:

```
ReferenceError
 "ReferenceError: ItemFileReadStore_1 is not defined
    at eval (eval at <anonymous> (eval at <anonymous> (http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/project1/lib/dojo/dojo/_base/kernel.js:1:0)))
    at eval (native)
    at Object.d.eval (eval at <anonymous> (http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/project1/lib/dojo/dojo/_base/kernel.js:1:0))
    at null.<anonymous> (http://localhost:8081/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridCreateTool.js?@revision@:107:32)
    at Object.ret.withDoc (http://localhost:8081/maqetta/app/dojo/_base/window.js?@revision@:121:20)
    at declare._getCreateCommand (http://localhost:8081/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridCreateTool.js?@revision@:94:8)
    at declare._create (http://localhost:8081/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridCreateTool.js?@revision@:31:22)
    at declare.create (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:579:9)
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:37:21)
    at Promise.Deferred.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:252:5)
    ----------------------------------------
    rejected at signalDeferred (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:78:15)
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:49:5)
    at Promise.Deferred.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:252:5)
    at declare.create (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:578:41)
    at declare.onMouseUp (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:385:9)
    at declare.onMouseUp (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:2294:21)
    at Object.dispatcher.around.advice (http://localhost:8081/maqetta/app/dojo/aspect.js?@revision@:106:23)
    at target.(anonymous function).dispatcher [as onMouseUp] (http://localhost:8081/maqetta/app/dojo/aspect.js?@revision@:88:39)
    at HTMLBodyElement.lang.hitch (http://localhost:8081/maqetta/app/dojo/_base/lang.js?@revision@:373:45)
    ----------------------------------------
[object Deferred]
    at Promise.Deferred.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:246:24)
    at declare.create (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:578:41)
    at declare.onMouseUp (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:385:9)
    at declare.onMouseUp (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:2294:21)
    at Object.dispatcher.around.advice (http://localhost:8081/maqetta/app/dojo/aspect.js?@revision@:106:23)
    at target.(anonymous function).dispatcher [as onMouseUp] (http://localhost:8081/maqetta/app/dojo/aspect.js?@revision@:88:39)
    at HTMLBodyElement.lang.hitch (http://localhost:8081/maqetta/app/dojo/_base/lang.js?@revision@:373:45)" 
```

**Comment by peller** [comment]
forgot that gridx still uses dojox/grid helpers...

**Comment by aerwin** [comment]
@peller 

Was ecstatic to see this one closed out, but after doing a "git pull" and running from Eclipse launch script, I'm still seeing the issue. I've cleared my browser cache (and even went so far as to delete workspace and restart server). Am I missing something obvious?

**Comment by aerwin** [comment]
FYI, this started working for me yesterday using launch from Eclipse and Chrome. But, I think there are still issues (see comments added to #2433).
