### ISSUE TITLE
Need strategy for handling read-only files (was: Error saving workingcopy (intermittent))

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2971]
Every so often, I get an error in the console when Maqetta tries to save a working copy:

> An error occurred: davinci.model.resource.File.prototype.setContents RequestError: Unable to load ./project1/samples/Sample1.html.workingcopy status: 404 : ./project1/samples/Sample1.html.workingcopy

Here's what seems to be the corresponding error in the server log file:

```

org.eclipse.core.runtime.CoreException: Could not write file: /var/lib/maqetta/ws-orion/B/
samples/Sample1.html.workingcopy.
        at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:55)
        at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile
.java:391)
        at maqetta.server.orion.VOrionStorage.createNewFile(VOrionStorage.java:155)
        at org.maqetta.server.VFile.createNewInstance(VFile.java:126)
        at maqetta.core.server.DavinciPageServlet.doPut(DavinciPageServlet.java:83)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:758)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.servic
e(ServletManager.java:180)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRe
gistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainI
mpl.java:38)
        at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
        at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
        at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92)
        at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
        at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
        at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
```

---

**Tasks:** _(updated 2012-08-21)_
- Disable **auto-save** for read-only files.
- Disable **Save** for read-only files -- only allow **Save As**.

**Comment by doronrosenberg** [comment]
Same error happened to me with Sample1.html

**Comment by jhpedemonte** [comment]
Didn't think of this at first, but this has to do with the fact that the `samples` directory is **read-only**.  Hence the error trying to write a file (the _workingcopy_) into that directory.

So how do we handle files in _read-only_ directories?  Currently, the samples files open up with a dirty bit (causing the client trying to save a working copy);  that should be fixed.

Also, I can click on **Save** and it appears to work, even though the file resides in a read-only directory.  There should be an error, or _preferrably_ a dialog asking me to save the file in a writable location.

Changing summary to better fit the problem.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
>  There should be an error, or preferrably a dialog asking me to save the file in a writable location.

Agreed

**Comment by jhpedemonte** [comment]
Added a **tasks** list to summary.

Sending to @doronrosenberg.  Can you please take a look at this one?

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo 

I would say we reuse the Save As dialog and add some text to the dialog contents such as "This file is a read-only file.  Please save it to a writeable location."

A better solution is to make the file uneditable, post a message somewhere in the UI and have it show the save as button only, but that is too complicated for m7.

**Comment by jhpedemonte** [comment]
No, I think it's good to keep it editable, so user can add to/change the sample files.  We just want to add some protection when dealing with read-only directories/files.

Your first option is the way to go, in addition to shutting off the working copy support for read-only files (to prevent errors).

**Comment by doronrosenberg** [comment]
@jhpedemonte is there a bug for the back end work if any is needed?

**Comment by jhpedemonte** [comment]
I don't think any server work is necessary.  As long as the two tasks in the summary are handled, then I think we're golden here.
