### ISSUE TITLE
Error saving theme workingcopy

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3034]
Server log files show this error:

```
org.eclipse.core.runtime.CoreException: Could not write file: /var/lib/maqetta/ws-orion/E/
themes/themes.theme.workingcopy.
        at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:55)
        at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:391)
        at maqetta.server.orion.VOrionStorage.createNewFile(VOrionStorage.java:155)
        at org.maqetta.server.VFile.createNewInstance(VFile.java:126)
        at maqetta.server.orion.user.OrionUser.createResource(OrionUser.java:210)
        at maqetta.core.server.command.CreateResource.handleCommand(CreateResource.java:23)
        ...
Caused by: java.io.FileNotFoundException: /var/lib/maqetta/ws-orion/E/themes/themes.theme.workingcopy (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:209)
        at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:382)
        ... 58 more
```

There are similar errors for other theme related files in the same directory.

Trying to write to read-only directory? Related to #2971?

Assigning to @childsb for now, but maybe @doronrosenberg can take a look.  cc @billreed63

**Comment by jhpedemonte** [comment]
Some other, possible related, errors:

```
2012-08-21 19:25:23.108 [qtp21680077-18] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/project1/themes/document.css
java.lang.NullPointerException: null
        at maqetta.core.server.DavinciPageServlet.doPut(DavinciPageServlet.java:78) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:758) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) ~[na:na]
        ...
2012-08-21 19:25:23.216 [qtp21680077-17] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/project1/themes/themes.css
java.lang.NullPointerException: null
        at maqetta.core.server.DavinciPageServlet.doPut(DavinciPageServlet.java:78) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:758) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) ~[na:na]
        ...
```

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte M8 Prio-High

**Comment by jhpedemonte** [comment]
-> M9
