### ISSUE TITLE
Orion error loading localhost:50000/maqetta

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3065]
With latest builds, when running locally and loading http://localhost:50000/maqetta, I get this error:

```
osgi> 2012-08-23 21:53:59.018 [qtp1677170384-28] WARN  o.e.jetty.servlet.ServletHandler - /maqetta
java.lang.NullPointerException: null
    at maqetta.server.orion.user.OrionUserManager.getUser(OrionUserManager.java:120) ~[na:na]
    at maqetta.core.server.DavinciPageServlet.doGet(DavinciPageServlet.java:111) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) ~[na:na]
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
```

Doesn't happen all the time, but more than 50% of the time.

When in this failed state, I can log into Orion by going to http://localhost:50000 and see my workspace.  But going to `/maqetta` still fails.

**Comment by jhpedemonte** [comment]
This did start happening after I enabled Zazl plugins again.  Possibly related?

**Comment by jhpedemonte** [comment]
Just tried deploy latest build to maqetta-test and this error happened 100% of the time.

**Comment by childsb** [comment]
@rbackhouse @jhpedemonte @peller  i was able to re-create this in eclipse/dev environment just by adding the zazl feature to the maqetta launch script ((mimicking the build)).

so it looks like zazl is somehow causing this.  any ideas? i dont see any zazl errors in the logs

**Comment by rbackhouse** [comment]
The stack trace suggests that line 35 in OrionUserManager is returning null;

```
    authenticationService = ConfiguratorActivator.getDefault().getAuthService();
```

My guess would be that the ConfiguratorActivator, assuming it is the Activator class for a bundle has not completed activation. Perhaps the bundle is not starting ?

**Comment by rbackhouse** [comment]
You can do a "ss" command in the osgi console to see the status of the "org.eclipse.orion.server.configurator" bundle. My guess is that it is not "Active" and thus the singleton it provides is null. I'm not sure I understand how Zazl can be affecting this though.

**Comment by childsb** [comment]
It shows active:
23  ACTIVE      maqetta.server.orion.w3.hosted_1.0.0.qualifier
24  ACTIVE      maqetta.shapes_1.0.0.qualifier
25  ACTIVE      maqetta.zazl_1.0.0.qualifier
26  ACTIVE      org.apache.commons.codec_1.3.0.v201101211617

Also I see this on startup:
2012-08-24 11:59:14.197 [Start Level Event Dispatcher] INFO  org.eclipse.orion.server.config - Server configuration file loaded from: /Users/childsb/dev/git/maqetta/maqetta.server.orion/web-ide.conf
servlet parm 'maqetta.maxUsers' is : null
servlet parm 'maqetta.maxUsers' is : null
Registering Zazl JavaScript servlet
Registering Maqetta HTML Filter for Zazl

So it seems that zazl is loading

**Comment by rbackhouse** [comment]
What about the "org.eclipse.orion.server.configurator" bundle though ? 

That is the one that is providing the ConfiguratorActivator.getDefault().getAuthService() code.

**Comment by childsb** [comment]
That plugin looks alive and well.  Here's the entire ss result:

"Framework is launched."

id  State       Bundle
0   ACTIVE      org.eclipse.osgi_3.8.0.v20120529-1548
1   ACTIVE      org.eclipse.equinox.simpleconfigurator_1.0.300.v20110815-1744
2   ACTIVE      ch.qos.logback.classic_1.0.0.v20111214-2030
                Fragments=108
3   ACTIVE      ch.qos.logback.core_1.0.0.v20111214-2030
4   RESOLVED    ch.qos.logback.slf4j_1.0.0.v20120123-1500
                Master=117
5   ACTIVE      com.ibm.icu_4.4.2.v20110823
6   ACTIVE      com.jcraft.jsch_0.1.44.v201101211721
7   ACTIVE      com.sun.el_2.2.0.v201108011116
8   ACTIVE      davinci.dojo_1_8_1.0.0.qualifier
9   ACTIVE      davinci.gridx_1.0.0.qualifier
10  ACTIVE      davinci.html_1.0.0.qualifier
11  ACTIVE      idx_1.0.0.qualifier
12  ACTIVE      javax.activation_1.1.0.v201108011116
13  ACTIVE      javax.el_2.2.0.v201108011116
14  ACTIVE      javax.mail.glassfish_1.4.1.v201108011116
15  ACTIVE      javax.servlet_3.0.0.v201112011016
16  ACTIVE      javax.servlet.jsp_2.2.0.v201112011158
17  ACTIVE      javax.xml_1.3.4.v201005080400
18  ACTIVE      maqetta.client.orion_1.0.0.qualifier
19  ACTIVE      maqetta.clipart_1.0.0.qualifier
20  ACTIVE      maqetta.core.client_1.0.0.qualifier
21  ACTIVE      maqetta.core.server_1.0.0.qualifier
22  ACTIVE      maqetta.server.orion_1.0.0.qualifier
23  ACTIVE      maqetta.server.orion.w3.hosted_1.0.0.qualifier
24  ACTIVE      maqetta.shapes_1.0.0.qualifier
25  ACTIVE      maqetta.zazl_1.0.0.qualifier
26  ACTIVE      org.apache.commons.codec_1.3.0.v201101211617
27  ACTIVE      org.apache.commons.fileupload_1.2.0.201208131240
28  ACTIVE      org.apache.commons.httpclient_3.1.0.v201012070820
29  ACTIVE      org.apache.commons.io_2.0.1.v201105210651
30  ACTIVE      org.apache.commons.logging_1.0.4.v201101211617
31  ACTIVE      org.apache.felix.gogo.command_0.8.0.v201108120515
32  ACTIVE      org.apache.felix.gogo.runtime_0.8.0.v201108120515
33  ACTIVE      org.apache.felix.gogo.shell_0.8.0.v201110170705
34  ACTIVE      org.apache.jasper.glassfish_2.2.2.v201205150955
35  ACTIVE      org.apache.lucene_3.5.0.v20120319-2345
36  ACTIVE      org.apache.lucene.analysis_3.5.0.v20120319-2345
37  ACTIVE      org.apache.lucene.core_3.5.0.v20120319-2345
38  ACTIVE      org.apache.lucene.grouping_3.5.0.v20120319-2345
39  ACTIVE      org.apache.lucene.highlighter_3.5.0.v20120319-2345
40  ACTIVE      org.apache.lucene.memory_3.5.0.v20120319-2345
41  ACTIVE      org.apache.lucene.misc_3.5.0.v20120319-2345
42  ACTIVE      org.apache.lucene.queries_3.5.0.v20120319-2345
43  ACTIVE      org.apache.lucene.spatial_3.5.0.v20120319-2345
44  ACTIVE      org.apache.lucene.spellchecker_3.5.0.v20120319-2345
45  ACTIVE      org.apache.solr.client.solrj_3.5.0.v20120319-2345
46  ACTIVE      org.apache.solr.core_3.5.0.v20120320-2000
47  ACTIVE      org.apache.xerces_2.9.0.v201101211617
48  ACTIVE      org.apache.xml.resolver_1.2.0.v201005080400
49  ACTIVE      org.apache.xml.serializer_2.7.1.v201005080400
50  ACTIVE      org.cyberneko.html_1.9.15
51  ACTIVE      org.dojotoolkit_1.6.1.v201108161253
52  ACTIVE      org.dojotoolkit.compressor_0.3.8
53  ACTIVE      org.dojotoolkit.compressor.shrinksafe_0.3.8
54  ACTIVE      org.dojotoolkit.json_0.3.1
55  ACTIVE      org.dojotoolkit.optimizer_0.3.2
56  ACTIVE      org.dojotoolkit.optimizer.amd_0.3.8
57  ACTIVE      org.dojotoolkit.optimizer.amd.rhinoast_0.3.6
58  ACTIVE      org.dojotoolkit.optimizer.servlet_0.3.2
59  ACTIVE      org.dojotoolkit.server.util_0.3.1
60  ACTIVE      org.dojotoolkit.server.util.js_0.3.1
61  ACTIVE      org.dojotoolkit.shrinksafe_1.0.1
62  ACTIVE      org.eclipse.core.contenttype_3.4.200.v20120523-2004
63  ACTIVE      org.eclipse.core.expressions_3.4.400.v20120523-2004
64  ACTIVE      org.eclipse.core.filesystem_1.3.200.v20120522-2012
                Fragments=65
65  RESOLVED    org.eclipse.core.filesystem.macosx_1.3.0.v20120522-1137
                Master=64
66  ACTIVE      org.eclipse.core.jobs_3.5.200.v20120521-2346
67  ACTIVE      org.eclipse.core.runtime_3.8.0.v20120521-2346
68  ACTIVE      org.eclipse.equinox.app_1.3.100.v20120522-1841
69  ACTIVE      org.eclipse.equinox.common_3.6.100.v20120522-1841
70  ACTIVE      org.eclipse.equinox.console_1.0.0.v20120522-1841
71  ACTIVE      org.eclipse.equinox.ds_1.4.0.v20120522-1841
72  ACTIVE      org.eclipse.equinox.http.jetty_3.0.0.v20120522-1841
73  ACTIVE      org.eclipse.equinox.http.registry_1.1.200.v20120522-2049
74  ACTIVE      org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841
75  ACTIVE      org.eclipse.equinox.jsp.jasper_1.0.400.v20120522-2049
76  ACTIVE      org.eclipse.equinox.jsp.jasper.registry_1.0.300.v20120522-2049
77  ACTIVE      org.eclipse.equinox.preferences_3.5.0.v20120522-1841
78  ACTIVE      org.eclipse.equinox.registry_3.5.200.v20120522-1841
79  ACTIVE      org.eclipse.equinox.security_1.1.100.v20120522-1841
80  ACTIVE      org.eclipse.equinox.util_1.0.400.v20120522-2049
81  ACTIVE      org.eclipse.help_3.6.0.v20120521-2344
82  ACTIVE      org.eclipse.help.base_3.6.100.v201206081400
83  ACTIVE      org.eclipse.help.webapp_3.6.100.v20120521-2344
84  ACTIVE      org.eclipse.jetty.client_8.1.3.v20120522
85  ACTIVE      org.eclipse.jetty.continuation_8.1.3.v20120522
86  ACTIVE      org.eclipse.jetty.http_8.1.3.v20120522
87  ACTIVE      org.eclipse.jetty.io_8.1.3.v20120522
88  ACTIVE      org.eclipse.jetty.security_8.1.3.v20120522
89  ACTIVE      org.eclipse.jetty.server_8.1.3.v20120522
90  ACTIVE      org.eclipse.jetty.servlet_8.1.3.v20120522
91  ACTIVE      org.eclipse.jetty.servlets_8.1.3.v20120522
92  ACTIVE      org.eclipse.jetty.util_8.1.3.v20120522
93  ACTIVE      org.eclipse.jgit_2.0.0.201206130900-r
94  ACTIVE      org.eclipse.orion.client.core_0.2.0.qualifier
95  ACTIVE      org.eclipse.orion.client.editor_0.1.0.qualifier
96  ACTIVE      org.eclipse.orion.client.git_0.2.0.qualifier
97  ACTIVE      org.eclipse.orion.client.users_0.2.0.qualifier
98  ACTIVE      org.eclipse.orion.doc.isv_0.2.0.v20120530-1934
99  ACTIVE      org.eclipse.orion.doc.user_0.2.0.v20120413-2008
100 ACTIVE      org.eclipse.orion.server.authentication.basic_0.2.0.v20120605-2104
101 ACTIVE      org.eclipse.orion.server.authentication.form.core_0.3.0.v20120619-1547
102 ACTIVE      org.eclipse.orion.server.authentication.formopenid_0.3.0.v20120619-1547
103 ACTIVE      org.eclipse.orion.server.authentication.openid.core_0.3.0.v20120618-1550
104 ACTIVE      org.eclipse.orion.server.configurator_0.5.0.v20120612-1830
105 ACTIVE      org.eclipse.orion.server.core_0.3.0.v20120619-1547
106 ACTIVE      org.eclipse.orion.server.git_0.4.0.v20120611-0901
107 ACTIVE      org.eclipse.orion.server.hosting_0.2.0.v20120615-1625
108 RESOLVED    org.eclipse.orion.server.logback.config_0.2.0.v20111007-1713
                Master=2
109 ACTIVE      org.eclipse.orion.server.search_0.5.0.v20120607-1524
110 ACTIVE      org.eclipse.orion.server.servlets_0.5.0.v20120606-2154
111 ACTIVE      org.eclipse.orion.server.user.securestorage_0.2.0.v20120210-1503
112 ACTIVE      org.eclipse.orion.server.useradmin_0.2.0.v20120210-1503
113 ACTIVE      org.eclipse.osgi.services_3.3.100.v20120522-1822
114 ACTIVE      org.json_1.0.0.v201011060100
115 ACTIVE      org.mozilla.javascript_1.7.3
116 ACTIVE      org.openid4java_0.9.5.v201105210655
117 ACTIVE      org.slf4j.api_1.6.4.v20120130-2120
                Fragments=4
118 ACTIVE      org.slf4j.jcl_1.6.4.v20120130-2120
osgi>

**Comment by rbackhouse** [comment]
My guess is that you are hitting a timing issue. The OrionUserManager constructor is getting called before the ConfiguratorActivator is complete. That is where authenticationService is being assigned.

I would suggest making  

authenticationService = ConfiguratorActivator.getDefault().getAuthService();

lazy as part of the getUser call 

```
        if (authenticationService == null) {
            authenticationService = ConfiguratorActivator.getDefault().getAuthService();
        }
        user = authenticationService.getAuthenticatedUser(req, null, authProperties);
```

**Comment by childsb** [comment]
Why would the inclusion of zazl introduce timing issues?  I tried waiting for 5 mins after launching the server to hit the page, but with the same error. 

With that said, I added a lazy load accessor method for the authentication service and that did fix the problem.

**Comment by rbackhouse** [comment]
You have more bundles loading. Using statics and OSGi opens up these sort of problems when those statics are initialized by activators. OSGi services are a much more robust approach.

**Comment by peller** [comment]
see 4c9e75c56d61b32a4dc0e2bdf77aa77bea0453e7

**Comment by cooljeffrey** [comment]
Hello guys, 

I just fetched the latest master code to my Eclipse 3.7 on Mac OSX, I got the same NPE error when accessing maqetta from web browser, could you please help or give me some guidance to fix it ? I am stuck here. Thanks!

osgi> servlet parm 'maqetta.maxUsers' is : null
servlet parm 'maqetta.maxUsers' is : null
RequestURL: http://localhost:50000/maqetta
Cookie: WLSESSIONID=5f0ec574-3680-4038-a4d3-ed35fce6f098; JSESSIONID=16au8ul6oibie10m0181o760pt
Host: localhost:50000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Charset: UTF-8,*;q=0.5
Accept-Language: en-US,en;q=0.8,ko;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.25 Safari/537.17
Connection: keep-alive
Cache-Control: max-age=0
Accept-Encoding: gzip,deflate,sdch
2012-11-29 16:29:27.385 [qtp988558046-32] WARN  o.e.jetty.servlet.ServletHandler - /maqetta
java.lang.NullPointerException: null
    at maqetta.server.orion.user.OrionUserManager.getUser(OrionUserManager.java:157) ~[na:na]
    at maqetta.core.server.DavinciPageServlet.doGet(DavinciPageServlet.java:148) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) ~[na:na]
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77) ~[na:na]
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384) ~[org.eclipse.equinox.http.jetty_3.0.0.v20120522-1841.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598) ~[org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.Server.handle(Server.java:350) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
    at java.lang.Thread.run(Thread.java:680) [na:1.6.0_37]

osgi> ss
"Framework is launched."

id  State       Bundle
0   ACTIVE      org.eclipse.osgi_3.8.1.v20120830-144521
                Fragments=67
1   ACTIVE      org.json_1.0.0.v201011060100
2   RESOLVED    ch.qos.logback.slf4j_1.0.0.v20120123-1500
                Master=49
3   ACTIVE      maqetta.shapes_1.0.0.qualifier
4   ACTIVE      org.apache.lucene.core_3.5.0.v20120319-2345
5   ACTIVE      org.eclipse.orion.server.hosting_0.2.0.v20120615-1625
6   ACTIVE      maqetta.core.client_1.0.0.qualifier
7   ACTIVE      org.eclipse.orion.server.search_0.5.0.v20120607-1524
8   ACTIVE      org.apache.commons.codec_1.3.0.v201101211617
9   ACTIVE      org.apache.felix.gogo.shell_0.8.0.v201110170705
10  ACTIVE      org.apache.commons.httpclient_3.1.0.v201012070820
11  ACTIVE      org.apache.lucene.queries_3.5.0.v20120319-2345
12  ACTIVE      org.eclipse.orion.server.configurator_0.5.0.v20120612-1830
13  ACTIVE      org.eclipse.jetty.io_8.1.3.v20120522
14  ACTIVE      org.apache.lucene.grouping_3.5.0.v20120319-2345
15  ACTIVE      org.apache.commons.logging_1.0.4.v201101211617
16  ACTIVE      javax.activation_1.1.0.v201108011116
17  ACTIVE      davinci.html_1.0.0.qualifier
18  ACTIVE      org.apache.commons.io_2.0.1.v201105210651
19  ACTIVE      maqetta.clipart_1.0.0.qualifier
20  ACTIVE      org.apache.lucene.memory_3.5.0.v20120319-2345
21  ACTIVE      javax.servlet_3.0.0.v201112011016
22  ACTIVE      ch.qos.logback.core_1.0.0.v20111214-2030
23  ACTIVE      org.apache.lucene.highlighter_3.5.0.v20120319-2345
24  ACTIVE      org.eclipse.equinox.app_1.3.100.v20120522-1841
25  ACTIVE      org.eclipse.jetty.continuation_8.1.3.v20120522
26  ACTIVE      maqetta.core.server_1.0.0.qualifier
27  ACTIVE      davinci.dojo_1_8_1.0.0.qualifier
28  ACTIVE      org.apache.felix.gogo.runtime_0.8.0.v201108120515
29  ACTIVE      org.apache.solr.client.solrj_3.5.0.v20120319-2345
30  ACTIVE      org.apache.lucene.spellchecker_3.5.0.v20120319-2345
31  ACTIVE      org.eclipse.equinox.http.registry_1.1.200.v20120522-2049
32  ACTIVE      org.apache.felix.gogo.command_0.8.0.v201108120515
33  ACTIVE      org.apache.lucene.misc_3.5.0.v20120319-2345
34  ACTIVE      org.eclipse.jetty.servlets_8.1.3.v20120522
35  RESOLVED    org.eclipse.orion.server.logback.config_0.2.0.v20111007-1713
                Master=58
36  ACTIVE      org.eclipse.orion.server.servlets_0.5.0.v20121109-bug390480
37  ACTIVE      org.eclipse.core.jobs_3.5.300.v20120622-204750
38  ACTIVE      org.eclipse.jgit_2.0.0.201206130900-r
39  ACTIVE      org.eclipse.core.contenttype_3.4.200.v20120523-2004
40  ACTIVE      org.eclipse.orion.server.core_0.3.0.v20120619-1547
41  ACTIVE      org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841
42  ACTIVE      org.eclipse.osgi.services_3.3.100.v20120522-1822
43  ACTIVE      org.apache.lucene_3.5.0.v20120319-2345
44  ACTIVE      maqetta.client.orion_1.0.0.qualifier
45  ACTIVE      org.apache.lucene.spatial_3.5.0.v20120319-2345
46  ACTIVE      javax.mail.glassfish_1.4.1.v201108011116
47  ACTIVE      org.eclipse.orion.server.git_0.4.0.v20120611-0901
48  ACTIVE      org.eclipse.jetty.http_8.1.3.v20120522
49  ACTIVE      org.slf4j.api_1.6.4.v20120130-2120
                Fragments=2
50  ACTIVE      org.eclipse.core.runtime_3.8.0.v20120521-2346
51  ACTIVE      org.eclipse.jetty.servlet_8.1.3.v20120522
52  ACTIVE      davinci.gridx_1.0.0.qualifier
53  ACTIVE      org.eclipse.orion.server.useradmin_0.2.0.v20120210-1503
54  ACTIVE      org.eclipse.equinox.http.jetty_3.0.0.v20120522-1841
55  ACTIVE      com.worklight.worklight-3rd-parties_5.0.2.407
56  ACTIVE      org.eclipse.jetty.security_8.1.3.v20120522
57  ACTIVE      com.jcraft.jsch_0.1.44.v201101211721
58  ACTIVE      ch.qos.logback.classic_1.0.0.v20111214-2030
                Fragments=35
59  ACTIVE      org.eclipse.equinox.console_1.0.0.v20120522-1841
60  ACTIVE      org.eclipse.equinox.preferences_3.5.0.v20120522-1841
61  ACTIVE      maqetta.client.plugins.defaults_1.0.0.M7
62  ACTIVE      org.apache.commons.fileupload_1.2.0.M7
63  ACTIVE      org.apache.lucene.analysis_3.5.0.v20120319-2345
64  RESOLVED    org.eclipse.core.filesystem.macosx_1.3.0.v20110423-0524
                Master=72
65  ACTIVE      org.eclipse.equinox.registry_3.5.200.v20120522-1841
                Fragments=71
66  ACTIVE      org.eclipse.jetty.util_8.1.3.v20120522
67  RESOLVED    javax.transaction_1.1.1.v201105210645
                Master=0
68  ACTIVE      org.apache.log4j_1.2.15.v201012070815
69  ACTIVE      org.eclipse.equinox.common_3.6.100.v20120522-1841
70  ACTIVE      org.eclipse.jetty.client_8.1.3.v20120522
71  RESOLVED    org.eclipse.core.runtime.compatibility.registry_3.5.0.v20110505
                Master=65
72  ACTIVE      org.eclipse.core.filesystem_1.3.200.v20120522-2012
                Fragments=64
73  ACTIVE      org.eclipse.jetty.server_8.1.3.v20120522
74  ACTIVE      maqetta.server.orion.standard_1.0.0.M7
75  ACTIVE      org.apache.solr.core_3.5.0.v20120320-2000
76  ACTIVE      maqetta.server.orion_1.0.0.qualifier
osgi> 

OK, i found my launch config missing some orion bundles ... I made it work after added them.

BTW, please consider to provide an out of the box working launch config. 
Thanks!

**Comment by jhpedemonte** [comment]
@cooljeffrey, as long as you follow the instructions from the [Developer Setup](https://github.com/maqetta/maqetta/wiki/Maqetta-with-Orion-Developer-Setup) page, you should be able to run one of the 2 mentioned run configs just fine, without error.

**Comment by cooljeffrey** [comment]
@jhpedemonte You are right, thank you!
