### ISSUE TITLE
404 error on save: Policy.error

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3139]
I've seen this error several times, working with samples or just creating new files.  Appears to be security policy related

```
org.eclipse.core.runtime.CoreException: Could not write file: /var/lib/maqetta/ws-orion/G/samples/Sample3-Mobile.html.workingcopy.
    at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:55)
    at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:391)
    at maqetta.server.orion.VOrionStorage.createNewFile(VOrionStorage.java:155)
    at org.maqetta.server.VFile.createNewInstance(VFile.java:126)
    at maqetta.core.server.DavinciPageServlet.doPut(DavinciPageServlet.java:83)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:758)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:350)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:900)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:954)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
    at java.lang.Thread.run(Thread.java:636)
Caused by: java.io.FileNotFoundException: /var/lib/maqetta/ws-orion/G/samples/Sample3-Mobile.html.workingcopy (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:209)
    at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:382)
```

**Comment by jhpedemonte** [comment]
This is an issue with trying to save to a **read-only** directory or overwrite a read-only file.

I thought @doronrosenberg had mostly fixed this.  Can't find that bug at the moment.

**Comment by peller** [comment]
while it's occurring, it might be worth making sure the error code posts some other 400 error and not a 404 on a put

**Comment by doronrosenberg** [comment]
@jhpedemonte Perhaps autosave is the culprit, I think I only fixed save by clicking the save button.

**Comment by jhpedemonte** [comment]
@doronrosenberg, would a similar fix work for auto-save?

**Comment by doronrosenberg** [comment]
@jhpedemonte well for save we put up a dialog, we could make sure that autosave does nothing if its readonly.  Any idea where the autosave code lives?

**Comment by JonFerraiolo** [comment]
I don't remember the details, but I remember that we used the 8 letters "autosave" in the implementation and a grep -i on autosave yields this:

```
Workbench.js:360:       Workbench._lastAutoSave = Date.now();
Workbench.js:361:       setInterval(dojo.hitch(this,"_autoSave"),30000);
Workbench.js:366:       Workbench._autoSave();
Workbench.js:2090:  _autoSave: function(){
Workbench.js:2091:      var lastSave = Workbench._lastAutoSave;
Workbench.js:2112:          Workbench._lastAutoSave = Date.now();
ve/Context.js:2453:         // Invoke autoSave, with "this" set to Workbench
ve/Context.js:2454:         Workbench._autoSave.call(Workbench);
ve/PageEditor.js:384:   save: function (isAutoSave) {
ve/PageEditor.js:387:       if (isAutoSave) {
ve/PageEditor.js:395:       this.visualEditor.save(isAutoSave);
ve/PageEditor.js:397:       this.isDirty= this.isDirty && isAutoSave;
ve/PageEditor.js:399:           this.editorContainer.setDirty(isAutoSave);
ve/themeEditor/ThemeEditor.js:696:                              //delete this.lookFor[aa]; we dont want to delete on autosave
ve/ThemeModifier.js:168:    saveDynamicCssFiles: function(cssFiles, isAutoSave){
ve/ThemeModifier.js:172:                        var deferred = node.save(isAutoSave);
ve/ThemeModifier.js:175:                            if (!isAutoSave){
ve/ThemeModifier.js:178:                            node.dirtyResource = isAutoSave;
ve/VisualEditor.js:415: save: function (isAutoSave){
ve/VisualEditor.js:424:                 node.save(isAutoSave);
ve/VisualEditor.js:431:     this.getContext().saveDynamicCssFiles(this.context.cssFiles, isAutoSave);
ve/VisualEditor.js:432:     this.isDirty=isAutoSave;

```

**Comment by doronrosenberg** [comment]
oops, I always forget to do case insensitive greps.  Taking

**Comment by doronrosenberg** [comment]
Hmm, we already do a readOnly check for autosave, so not sure how this is happening without a good testcase.

**Comment by peller** [comment]
all I did was open a sample file and leave the workbench idle.

**Comment by doronrosenberg** [comment]
I just let it idle for 15 minutes, no server errors.

**Comment by doronrosenberg** [comment]
In theory my dirty changes should prevent a opened but unchanged file from ever getting saved.  I'll let it run after making a page change

**Comment by doronrosenberg** [comment]
Closing as I can't reproduce, please reopen if it still happens
