### ISSUE TITLE
NPE in OrionPersonManager (cannot create review)

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3143]
I see the following errors in maqetta-test server logs (running maqetta-orion build):

```
2012-08-28 00:04:23.178 [qtp24856323-23] INFO  org.eclipse.orion.server.login - Login success: A
java.lang.NullPointerException
        at maqetta.server.orion.user.OrionPersonManager$OrionPersonImpl.getEmail(OrionPersonManager.java:41)
        at maqetta.server.orion.user.OrionPersonManager.getPersons(OrionPersonManager.java:150)
        at maqetta.core.server.command.GetBluePageInfo.handleCommand(GetBluePageInfo.java:35)
        at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
        at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        ...
2012-08-28 00:30:43.979 [qtp24856323-44] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/publish
java.lang.NullPointerException: null
        at maqetta.server.orion.user.OrionPersonManager$OrionPersonImpl.getEmail(OrionPersonManager.java:41) ~[na:na]
        at maqetta.server.orion.user.OrionPersonManager.getPersonByEmail(OrionPersonManager.java:134) ~[na:na]
        at org.davinci.server.review.user.Reviewer.getUserID(Reviewer.java:32) ~[na:na]
        at maqetta.core.server.user.ReviewManager$VersionFile.save(ReviewManager.java:376) ~[na:na]
        at maqetta.core.server.user.ReviewManager.saveVersionFile(ReviewManager.java:140) ~[na:na]
        at maqetta.core.server.user.ReviewManager.publish(ReviewManager.java:91) ~[na:na]
        at maqetta.core.server.command.Publish.handleCommand(Publish.java:145) ~[na:na]
        at org.maqetta.server.DavinciCommandServlet.doPost(DavinciCommandServlet.java:134) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        ...
```

Seems to be caused by trying to create a new Review (which fails).

**Comment by jhpedemonte** [comment]
cc @aerwin 

When creating a review, I get a related error in the browser console (server returned 500, due to NPE) and review creation seems to fail.

However, I do see the review in the other user's Reviews pane.  And after a refresh, the review shows up for my test user.  So the reviews themselves are created.

But I didn't not see a notification email for either user.

**Comment by jhpedemonte** [comment]
Also, most likely related, I get no notifications for new comments added to reviews.  Need to test after the NPE is fixed.

**Comment by aerwin** [comment]
--> @aerwin 

Per scrum, I said I can at least take a look.

**Comment by aerwin** [comment]
--> @childsb 

I'm not able to reproduce this in local Orion from Eclipse. 

Think I need to pass this one back to @childsb ... I've glanced at the code and the exception from @jhpedemonte 's stack tack occurs on the `this.email = user.getLogin();` line of the function below from `OrionPersonImpl`:

```
            public String getEmail() {
             if(this.email!=null)
                 return this.email;

       //    UserServiceHelper.getDefault().getUserProfileService().getUserProfileNode(this.name, false);
             IOrionCredentialsService userAdmin = UserServiceHelper.getDefault().getUserStore();
             User user = (User) userAdmin.getUser(UserConstants.KEY_UID, this.getUserID());
             this.email = user.getLogin();
             return email;
         }
```

It's invoked by the `String email = ((IPerson) persons.get(name)).getEmail();` line in the function below from `OrionPersonManager`:

```
 public IPerson[] getPersons(String userName, int resultNumber, int start) {
            HashMap<String, IPerson> users = new HashMap<String, IPerson>();
            Set<String> names = persons.keySet();
            int i = 0;
            for (String name : names) {
                String email = ((IPerson) persons.get(name)).getEmail();
                if (name.indexOf(userName) >= 0 || email.indexOf(userName) >= 0) {
                    if (i >= start && i < start + resultNumber) {
                        users.put(email, new OrionPersonImpl(name, "", email));
                    }
                    i++;
                }
            }
            return users.values().toArray(new IPerson[0]);
        }
```

I don't really know anything about the sign-up process... can you envision how there might not be a valid user in the  IOrionCredentialsService that matches an entry in the list of persons?

**Comment by aerwin** [comment]
@childsb 

Potential clue on this one...

A new maqetta-orion multi user.launch came down with a git pull today and it appears to happen locally now as well...

**Comment by aerwin** [comment]
@childsb @jhpedemonte 

So, the baseDirectory changed to ${env_var:MAQETTA_WORKSPACE} from a hard coded path in the launch script. I noticed there was an old .review directory in the directory my MAQETTA_WORKSPACE pointed at. I cleaned out my orion workspace and my old .review directory and restarted the server from scratch. Things are working fine again.

Do we have an old .review directory out on the internal test server by chance that isn't getting cleaned up between installs?

**Comment by jhpedemonte** [comment]
Where should I look for that?

**Comment by aerwin** [comment]
I'd have to defer to @childsb .

**Comment by jhpedemonte** [comment]
Reopening.  I'm still seeing quite a few instances of this exception.  Often following a call to `/maqetta/cmd/publish`, but sometimes the exception is by itself in the logs.

**Comment by aerwin** [comment]
@jhpedemonte So, just to be clear... you're seeing it in current logs after your refreshed the server this morning? That's weird because I'm not seeing any indication of that in the browser console (and able to successfully list and create reviews) after you refreshed the server.

**Comment by jhpedemonte** [comment]
@aerwin, seeing this on maqetta.org server logs.

I grepped through all of them since we shipped M7 and only saw 4 instances in that time, all back-to-back on the same day (Sept 14).

So this is rare, for the moment.  Of course, if it's only surfaced by using R&C, that could have something to do with it -- I expect R&C is not used much by the majority of our users on maqetta.org.

**Comment by aerwin** [comment]
For what it's worth, since @jhpedemonte has seen these on maqetta.org, I just went out to try and create a review on maqetta.org and it seemed to work. So, at least that's good. :)

**Comment by aerwin** [comment]
Well, now, I just logged into maqetta-test and see 500 errors for listVersion in the browser console again.

**Comment by aerwin** [comment]
In the end, I think we need @childsb to weigh in here about how a "bad" entry could be added to the `persons` data structure... but I took another quick peek and thought it strange that `getPerson` in `OrionPersonManager` tries to add the person if it doesn't find  him:

```
public IPerson getPerson(String userName) {

            IPerson person = (IPerson) persons.get(userName);
            if(person!=null)
                return person;

            try {
                return addPerson(userName, null, null);
            } catch (UserException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            return null;

        }
```

This is different from the `getPerson` impl in `PersonManagerImpl` in `maqetta.core.server` that just acts as a look up service:

```
public IPerson getPerson(String userName) {

        IPerson person = (IPerson) persons.get(userName);
        return person;

    }
```

But, exploring that further, I think the only place `getPerson` is called is in `getUser` function of `OrionUserManager` after a successful call to `checkUserExists` which uses the same `IOrionCredentialsService` that fails in the exception behind this issue:

```
protected boolean checkUserExists(String userName, Boolean isLogin) {
        String key = isLogin ? UserConstants.KEY_LOGIN : UserConstants.KEY_UID;
        IOrionCredentialsService userAdmin = UserServiceHelper.getDefault().getUserStore();
        org.eclipse.orion.server.useradmin.User user = (org.eclipse.orion.server.useradmin.User)
                userAdmin.getUser(key, userName);
        return user != null;
    }

    public IUser getUser(String userName, Boolean isLogin) {

        // IUser user = (IUser) users.get(userName);
         if (ServerManager.LOCAL_INSTALL && IDavinciServerConstants.LOCAL_INSTALL_USER.equals(userName)) {
             return this.getSingleUser();
         }

         if (this.checkUserExists(userName, isLogin)) {
             IPerson person = this.personManager.getPerson(userName);
             return newUser(person, null);

         }
         return null;

     }
```

**Comment by aerwin** [comment]
I didn't get the memo that @childsb has left the team, so @jhpedemonte had a chat with @childsb about `getPerson` having a call to `addPerson` in it. It sounds like @childsb speculated it was put there for R&C at some point. I don't know if that true or not, but as I explained to @jhpedemonte in ST... R&C doesn't call `getPerson` or `addPerson` anywhere I can see. And, like I tried to explain above, the one call to `getPerson` appears to be guarded by a check against the `IOrionCredentialsService` anyway.

The bottom line is somehow we're getting a mismatch between the list of persons stored in `OrionPersonManager` and the list of people known to the `IOrionCredentialsService`. I had been thinking a "bad" person was added to the PersonManager list, but a thought that just occurred to me is that it might be the oppositie. E.g., a user might have been removed from the `IOrionCredentialsService` that had previously been added to the `OrionPersonManager`. I don't know how often the `IOrionCredentialsService` is pruned as people logout, but it definitely seems to happen on server restart (see #3407).

We've also got issue #3406 ("Orion user id's are not consistent") which may be related.

It seems like we've got a number of issues with Orion user management, and I don't know who owns the area moving forward. But, for M7.0.1, I don't think there's a lot else we can do.

@jhpedemonte suggested I put in some trace... I did a little of that and went a step further to add a check for null in `getEmail` of `OrionPersonManager` (see 98827e18050844074066c793faf05049ade37481). This is a band-aid, but might keep us hobbling along when `OrionPersonManager` gets out of synch with `IOrionCredentialsService`.

**Comment by aerwin** [comment]
-> M8
-> Prio down to High, Severity down to 2

Per scrum, we'll keep this open to see if exception recurs and anything else we can do about it...

**Comment by aerwin** [comment]
Looks like no one's assigned (was @childsb ) as of yesterday, so I'll put my name on it...

**Comment by jhpedemonte** [comment]
@doronrosenberg was testing today and I saw many stack traces that look like this:

```
ERROR: OrionPersonImpl.getEmail: user 'doronr@...' could not be found in IOrionCredentialsService.
java.lang.NullPointerException
        at maqetta.server.orion.user.OrionPersonManager.getPersons(OrionPersonManager.java:158)
        at maqetta.core.server.command.GetBluePageInfo.handleCommand(GetBluePageInfo.java:35)
        at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
        at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:123)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
```

**Comment by billreed63** [comment]
Sending to @jhpedemonte

**Comment by jhpedemonte** [comment]
-> M9
