### ISSUE TITLE
Dojo Web Builder failure

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3303]
Enabled Dojo Web Builder on our test machine when downloading the whole workspace.

First, after clicking **Download** button, the dialog disappeared and I didn't see any progress bar. The only UI I saw was Chrome's status bar, which said _"Waiting for app.moketta.org..."_.

After about a minute, I got a blank page saying _"504 Gateway Time-out"_.  In the Maqetta server log, I see this:

```
analyzeWorkspace: number of files: 19
build.dojotoolkit.org: Analyse url=http://app.moketta.org/maqetta/user/A/ws/workspace/project1/themes/foobar/dojo-theme-editor.html
build.dojotoolkit.org: Analyse failed: HTTP/1.1 404 Not Found <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing //api/dependencies. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>
```

(Note that this was with a migrated work space.)

Nginx error log (_/var/log/nginx/maqetta-app.error.log_) showed this:

> 2012/09/07 07:09:23 [error] 5790#0: *395 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 24.206.109.131, server: app.moketta.org, request: "GET /maqetta/cmd/download?fileName=workspace1.zip&root=project1&build=1&resources=%5B%22project1%22%5D&libs=%5B%7B%22id%22%3A%22maqetta%22%2C%22version%22%3A%220.3%22%2C%22root%22%3A%22lib%2Fmaqetta%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22dojo%22%2C%22version%22%3A%221.8%22%2C%22root%22%3A%22lib%2Fdojo%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22DojoThemes%22%2C%22version%22%3A%221.8%22%2C%22root%22%3A%22themes%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22clipart%22%2C%22version%22%3A%221.0%22%2C%22root%22%3A%22lib%2Fclipart%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22shapes%22%2C%22version%22%3A%221.0%22%2C%22root%22%3A%22lib%2Fshapes%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22gridx%22%2C%22version%22%3A%221.0.0%22%2C%22root%22%3A%22lib%2Fdojo%2Fgridx%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22maqettaSamples%22%2C%22version%22%3A%221.0%22%2C%22root%22%3A%22samples%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22zazl%22%2C%22version%22%3A%220.3.0%22%2C%22root%22%3A%22lib%2Fzazl%22%2C%22includeSrc%22%3Atrue%7D%5D HTTP/1.1", upstream: "http://127.0.0.1:8080/maqetta/cmd/download?fileName=workspace1.zip&root=project1&build=1&resources=%5B%22project1%22%5D&libs=%5B%7B%22id%22%3A%22maqetta%22%2C%22version%22%3A%220.3%22%2C%22root%22%3A%22lib%2Fmaqetta%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22dojo%22%2C%22version%22%3A%221.8%22%2C%22root%22%3A%22lib%2Fdojo%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22DojoThemes%22%2C%22version%22%3A%221.8%22%2C%22root%22%3A%22themes%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22clipart%22%2C%22version%22%3A%221.0%22%2C%22root%22%3A%22lib%2Fclipart%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22shapes%22%2C%22version%22%3A%221.0%22%2C%22root%22%3A%22lib%2Fshapes%22%2C%22includeSrc%22%3Atrue%7D%2C%7B%22id%22%3A%22gridx%22%2C%

**Comment by peller** [comment]
it's possible the request really takes so long that it times out, and that we need to come up with some sort of polling scheme so the proxy doesn't fail (or raise the timeout limit)

**Comment by jhpedemonte** [comment]
OK, removed the trailing slash from the URL, and now a ZIP did download.  But I got this error in the server log:

```
analyzeWorkspace: number of files: 26
build.dojotoolkit.org: Analyse url=http://app.moketta.org/maqetta/user/A/ws/workspace/project1/themes/foobar/dojo-theme-editor.html
2012-09-07 13:46:46.636 [qtp1137600060-23] WARN  o.a.c.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
build.dojotoolkit.org: Analyse result={"requiredDojoModules":["dijit.dijit","dijit.form.Button","dijit.Toolbar","dijit.form.CheckBox","dijit.form.ComboBox","dijit.form.TextBox","dijit.Calendar","dijit.layout.TabContainer","dijit.layout.ContentPane","dijit.layout.AccordionContainer","dijit.TitlePane","dijit.layout.BorderContainer","dijit.Menu","dojo.parser"],"availableModules":[],"packages":[],"dojoVersion":"UNKNOWN"}
build.dojotoolkit.org: Analyse url=http://app.moketta.org/maqetta/user/A/ws/workspace/project1/themes/custom2/dojo-theme-editor.html
2012-09-07 13:46:47.104 [qtp1137600060-23] WARN  o.a.c.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
build.dojotoolkit.org: Analyse result={"requiredDojoModules":["dijit.form.DataList","dojox.mobile","dojox.mobile.parser","dojox.mobile.View","dojox.mobile.Button","dojox.mobile.ToggleButton","dojox.mobile.Switch","dojox.mobile.Heading","dojox.mobile.RoundRect","dojox.mobile.ComboBox"],"availableModules":[],"packages":[],"dojoVersion":"UNKNOWN"}
add dijit.form.DataList
add dojox.mobile
add dojox.mobile.parser
add dojox.mobile.View
add dojox.mobile.Button
add dojox.mobile.ToggleButton
add dojox.mobile.Switch
add dojox.mobile.Heading
add dojox.mobile.RoundRect
add dojox.mobile.ComboBox
build.dojotoolkit.org: Analyse url=http://app.moketta.org/maqetta/user/A/ws/workspace/project1/Sample2.html
build.dojotoolkit.org: Analyse failed: HTTP/1.1 500 FAILED ASSERTION <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 FAILED ASSERTION</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /api/dependencies. Reason:
<pre>    FAILED ASSERTION</pre></p><h3>Caused by:</h3><pre>java.lang.IllegalStateException: FAILED ASSERTION
    at org.mozilla.javascript.Kit.codeBug(Kit.java:480)
    at org.mozilla.javascript.TokenStream.&lt;init&gt;(TokenStream.java:82)
    at org.mozilla.javascript.Parser.parse(Parser.java:336)
    at org.dtk.analysis.script.BaseScriptParser.parse(BaseScriptParser.java:73)
    at org.dtk.analysis.script.config.BaseScriptConfigParser.initAndParseScriptConfiguration(BaseScriptConfigParser.java:92)
    at org.dtk.analysis.script.config.BaseScriptConfigParser.getScriptConfig(BaseScriptConfigParser.java:79)
    at org.dtk.analysis.page.WebPage.parseScriptConfiguration(WebPage.java:289)
    at org.dtk.analysis.page.WebPage.parsePreDojoScript(WebPage.java:177)
    at org.dtk.analysis.page.RemoteWebPage.parsePreDojoScript(RemoteWebPage.java:86)
    at org.dtk.analysis.page.WebPage.parse(WebPage.java:153)
    at org.dtk.analysis.page.RemoteWebPage.&lt;init&gt;(RemoteWebPage.java:62)
    at org.dtk.resources.Dependencies.analyseModulesFromUrl(Dependencies.java:245)
    at org.dtk.resources.Dependencies.analyseDependencies(Dependencies.java:150)
    at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
    at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:33)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.handlers.CreateInvocationParametersHandler.handleRequest(CreateInvocationParametersHandler.java:54)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleResourceMethod(FindResourceMethodHandler.java:151)
    at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleRequest(FindResourceMethodHandler.java:65)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.handlers.FindRootResourceHandler.handleRequest(FindRootResourceHandler.java:95)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.handlers.HeadMethodHandler.handleRequest(HeadMethodHandler.java:53)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.handlers.OptionsMethodHandler.handleRequest(OptionsMethodHandler.java:46)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.handlers.SearchResultHandler.handleRequest(SearchResultHandler.java:33)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.log.ResourceInvocation.handleRequest(ResourceInvocation.java:92)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.internal.log.Requests.handleRequest(Requests.java:76)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
    at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
    at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
    at org.apache.wink.server.handlers.AbstractHandlersChain.run(AbstractHandlersChain.java:48)
    at org.apache.wink.server.internal.RequestProcessor.handleRequestWithoutFaultBarrier(RequestProcessor.java:207)
    at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:154)
    at org.apache.wink.server.internal.servlet.RestServlet.service(RestServlet.java:119)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1351)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:170)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1322)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:514)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:247)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:151)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:679)
</pre>
<hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>
```

The file **workspace/project1/Sample2.html** does exist and it is in the downloaded zip.

**Comment by jthomas** [comment]
Reviewing this issue, there were two problems. There was a bug in the DWB analysis code when handling an AMD require with a first argument as just a configuration object with no further parameters. I've fixed this and re-deployed the code. 
Secondly, the built layer that's included for the gridx module is causing issues. We can't handle the module dependences that come from cached built AMD modules very well. It's a fairly unique use case for the app, using it to analyse a partially built application.

**Comment by jhpedemonte** [comment]
@jthomas, does the 2nd situation cause an error?  What about just ignoring it and not making any changes to those files; is that a possibility?

**Comment by peller** [comment]
pushing off problem with built layers like gridx to M8

**Comment by peller** [comment]
Ideally, DWB would be able to (transparently?) reference built layers and avoid re-building them or rolling the modules into a new layer, like dojo.js.  We do also have the option of passing in source to the DWB.  Right now, the source switch doesn't seem to do that.

**Comment by jthomas** [comment]
@jhpedemonte It doesn't cause an error directly but the returned module identifiers are broken. We get things like "..base/dom-class". Just ignoring the results would work.

**Comment by jhpedemonte** [comment]
I've seen the `java.lang.IllegalStateException` about 4 times since M7 launch on maqetta.org.

**Comment by JonFerraiolo** [comment]
@jhpedemonte - I'll leave this one to you to set the priority

**Comment by jthomas** [comment]
I've fixed the issue about handling built layers, can you re-test this issue?

**Comment by peller** [comment]
ok, new problem: I'm not copying over the built dojo/nls files into the zip, just dojo.js. Somehow we got away with that in Dojo 1.7.2.  The good news is that the DWB parses everything and returns a build.

**Comment by peller** [comment]
most of these problems appear to be addressed, except for the gateway timeout.  See #3879
