### ISSUE TITLE
Zazl EofException

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3313]
Saw this in the Maqetta server log:

```
Sep 7, 2012 9:53:12 AM org.dojotoolkit.optimizer.servlet.AMDJSHandler handle
SEVERE: Exception on request for [dijit/layout/ContentPane,dijit/form/TextBox,dijit/form/Button,dijit/layout/TabContainer,dijit/Calendar,maqetta/space
,maqetta/AppStates]
org.eclipse.jetty.io.EofException
       at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:952)
       at org.eclipse.jetty.http.AbstractGenerator.blockForOutput(AbstractGenerator.java:518)
       at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:182)
       at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:101)
       at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:178)
       at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:135)
       at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:89)
       at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:220)
       at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
       at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:124)
       at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
       at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:128)
       at java.io.BufferedWriter.write(BufferedWriter.java:229)
       at java.io.Writer.write(Writer.java:157)
        at org.dojotoolkit.optimizer.servlet.AMDJSHandler.customHandle(AMDJSHandler.java:98)
       at org.dojotoolkit.optimizer.servlet.JSHandler.handle(JSHandler.java:172)
       at org.dojotoolkit.optimizer.servlet.JSServlet.service(JSServlet.java:154)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
       at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
       at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
       at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
       at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
       at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
       at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
       at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92)
       at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
       at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
       at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
       at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
       at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
       at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
       at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
       at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
       at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
       at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
       at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
       at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
       at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
       at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42)
       at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
       at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
       at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
       at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
       at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
       at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
       at org.eclipse.jetty.server.Server.handle(Server.java:350)
       at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
       at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
       at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
       at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
       at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
       at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
       at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
       at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
       at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.IOException: Broken pipe
       at sun.nio.ch.FileDispatcher.write0(Native Method)
       at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
       at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:122)
       at sun.nio.ch.IOUtil.write(IOUtil.java:78)
       at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:352)
       at org.eclipse.jetty.io.nio.ChannelEndPoint.flush(ChannelEndPoint.java:288)
       at org.eclipse.jetty.io.nio.SelectChannelEndPoint.flush(SelectChannelEndPoint.java:341)
       at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:888)
       ... 66 more
Sep 7, 2012 9:53:17 AM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer _getAnalysisData
INFO: AST parsing [dojox/mobile/_compat] using the Rhino AST API
```

Unfortunately, that's all the info I have.  I don't know what caused this.

@peller

**Comment by rbackhouse** [comment]
Broken pipe exceptions are usually caused by writing to a client who has disconnected. I'm not sure there is much you can do about this. My guess is the page was probably still loading when it was closed.

**Comment by jhpedemonte** [comment]
OK, thanks.  Closing.
