### ISSUE TITLE
Adding comment fails in server

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3350]
Adding a review comment fails in latest build.

In browser console:

> GET http://app.moketta.org/maqetta/cmd/addComment?id=87914963-feeb-06a4-6e4f-247af33b50fd&subject=Circle%20button&content=foo!&ownerId=A&email=javier%40pedemonte.us&next=Next&pageStateList=%5B%7B%22id%22%3A%22myapp%22%2C%22xpath%22%3A%22%2Fhtml%2Fbody%22%7D%5D&viewSceneList=%7B%22DojoMobileViews%22%3A%5B%5D%7D&designerId=A&pageName=.review%2Fsnapshot%2F2012-09-11T00%3A24%3A55Z%2Ffoobar%2Fsamples%2FSample1.html&replyTo=root&drawingJson=%5B%7B%22type%22%3A%22Ellipse%22%2C%22x1%22%3A222%2C%22y1%22%3A21%2C%22x2%22%3A317%2C%22y2%22%3A80%2C%22colorAlias%22%3A%22A%22%2C%22commentId%22%3A%2287914963-feeb-06a4-6e4f-247af33b50fd%22%2C%22stateList%22%3A%22%5B%7B%5C%22id%5C%22%3A%5C%22myapp%5C%22%2C%5C%22xpath%5C%22%3A%5C%22%2Fhtml%2Fbody%5C%22%7D%5D%22%2C%22sceneList%22%3A%22%7B%5C%22DojoMobileViews%5C%22%3A%5B%5D%7D%22%7D%5D 400 (The review is not added successfully. Reason: null)

In server log:

```
java.lang.NullPointerException
    at maqetta.core.server.command.AddComment.handleCommand(AddComment.java:52)
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
```

That corresponds to this bit of code:

``` java
    //Set up project based on designer
    DavinciProject project = new DavinciProject();
    project.setOwnerId(designer.getUserID());                   // line 52
    comment.setProject(project);
```

So `designer` is null for some reason.

@aerwin @JonFerraiolo

**Comment by jhpedemonte** [comment]
This was broken by commit bb13147f68ff2df80169a97e106d68d0fc7baa34.

Brad changed `checkUserExists()` to take an actual email address.  But several places in the code (AddComment.handleCommand(), ListVersions.handleCommand(), maybe more) are still passing in users IDs in the form of `A`.

**Comment by jhpedemonte** [comment]
This seems to be working now with the latest patch.  However, I don't consider that a long term solution.  Need to clean up the code around handling user IDs vs Logins.  -> M8

**Comment by jhpedemonte** [comment]
Should be fixed by commits above.  Just to be sure, I also added some assertions into the relevant code, to make sure that we aren't passing in an email address when we really want an Orion user ID.  See 496792078687a358af92b281483113a567bb8ccb.
