### ISSUE TITLE
Download as zip: Downloading sketch theme has exceptions and zip file includes all themes (not just selected one)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3353]
Using Chrome on Mac going to staging server and doing Step 3 of the "download as zip (context menu)" test case in the Files test plan. I'm using an Eclipse project, but wouldn't think that should matter.

> Select the ./themes/sketch folder. Right-click on file to bring up context menu and select "Download". In dialog, type in "download3". A file named download3.zip should be in your browser's download area with all of the files from that folder inside.

After doing so see:

```
GET http://app.moketta.org/maqetta/cmd/findResource?path=*.html&ignoreCase=true&workspaceOnly=true&inFolder=.%2FtestEclipse20120910%2FWebContent%2Fthemes%2Fsketch 500 (Server Error) dojo.js:4720
xhr dojo.js:4720
dojo.xhr dojo.js:5440
dojo.xhrGet dojo.js:5456
_107c.serverJSONRequest davinci.js:22917
_2a2b.findResource davinci.js:58994
_1da3._rewriteUrls davinci.js:40856
_1da3.okButton davinci.js:40897
lang.hitch dojo.js:4956
_55f.(anonymous function)._564 dojo.js:6939
_2418._onClick davinci.js:50588
_272 dojo.js:2795
_ebd._onClick davinci.js:21009
lang.hitch dojo.js:4956
_d4 dijit.js:674
```

then see:

```
_4fc
get stack: function () { [native code] }
message: "Unable to load cmd/findResource?path=*.html&ignoreCase=true&workspaceOnly=true&inFolder=.%2FtestEclipse20120910%2FWebContent%2Fthemes%2Fsketch status: 500"
response: Object
set stack: function () { [native code] }
__proto__: TMP
```

then see:

```
Workbench::handleIoError reason=RequestError: Unable to load cmd/findResource?path=*.html&ignoreCase=true&workspaceOnly=true&inFolder=.%2FtestEclipse20120910%2FWebContent%2Fthemes%2Fsketch status: 500 
```

then see (covered by #3352):

```
Uncaught TypeError: Object [object Object] has no method 'getOnUnloadWarningMessage' davinci.js:22823
_107c.run
```

Download completes, but all of the themes are included in the zip file. Perhaps this isn't a valid test case anymore if we just always download all themes?

**Comment by jhpedemonte** [comment]
-> M8

**Comment by billreed63** [comment]
-> M9
@JonFerraiolo @jhpedemonte

**Comment by billreed63** [comment]
The issues seems to be when the user right clicks on a folder it is treated as a download selected file/folder which does not download the readonly files, this seems like a bug as if I right click on the theme folder I would expect all the themes to be downloaded not just the read/write themes. Also if I am in an eclipse project and right click download the webcontainer folder I would expect the libs to be in the zip as well.

I am sending this to @peller as he is the download dude.

**Comment by peller** [comment]
this is what's causing the 500:

```
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet doGet
SEVERE: Unhandled Exception
java.lang.NullPointerException
    at maqetta.core.server.util.DirectoryFilter.isHidden(DirectoryFilter.java:21)
    at maqetta.core.server.util.Resource.isHidden(Resource.java:32)
    at maqetta.core.server.util.Resource.foundVRsourcesToJson(Resource.java:77)
    at maqetta.core.server.command.FindResource.handleCommand(FindResource.java:37)
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:74)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:99)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:350)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
    at java.lang.Thread.run(Thread.java:680)
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: RequestURL: http://localhost:8081/maqetta/cmd/findResource
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Query: path=*.html&ignoreCase=true&workspaceOnly=true&inFolder=.%2Fproject1%2Fthemes%2Fsketch
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: X-Requested-With: XMLHttpRequest
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Cookie: JSESSIONID=0CF6B719D562922F90D6BD08E4F5CE8B; reviewWizardTargetTreeSaveSelectedCookie=root%2Froot%2Ffile1.html; JSESSIONID=xdpzn9258zaj8ziozwmqilnv
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Host: localhost:8081
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept: */*
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Content-Type: application/x-www-form-urlencoded
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept-Language: en-US,en;q=0.8
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Referer: http://localhost:8081/maqetta/
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Connection: keep-alive
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept-Encoding: gzip,deflate,sdch
2013-04-12 14:13:19.018 [qtp1105339954-1366] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/findResource
java.lang.NullPointerException: null
    at maqetta.core.server.util.DirectoryFilter.isHidden(DirectoryFilter.java:21) ~[na:na]
    at maqetta.core.server.util.Resource.isHidden(Resource.java:32) ~[na:na]
    at maqetta.core.server.util.Resource.foundVRsourcesToJson(Resource.java:77) ~[na:na]
    at maqetta.core.server.command.FindResource.handleCommand(FindResource.java:37) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:74) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) ~[na:na]
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:99) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77) ~[na:na]
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226) ~[na:na]
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42) ~[na:na]
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384) ~[org.eclipse.equinox.http.jetty_3.0.0.v20120522-1841.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598) ~[org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.Server.handle(Server.java:350) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
    at java.lang.Thread.run(Thread.java:680) [na:1.6.0_37]
Apr 12, 2013 2:13:19 PM maqetta.core.server.DavinciPageServlet doPut
WARNING: DavinciPageServlet:doPut user.getResource(/project1/file5.html) returned Null for user: A
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet doGet
SEVERE: Unhandled Exception
java.io.IOException: CLOSED
    at org.eclipse.jetty.http.gzip.AbstractCompressedStream.checkOut(AbstractCompressedStream.java:288)
    at org.eclipse.jetty.http.gzip.AbstractCompressedStream.write(AbstractCompressedStream.java:210)
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:79)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:99)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:350)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
    at java.lang.Thread.run(Thread.java:680)
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: RequestURL: http://localhost:8081/maqetta/cmd/download
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Query: fileName=sketch.zip&root=project1&resources=%5B%22.%2Fproject1%2Fthemes%2Fsketch%22%5D&libs=%5B%5D
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Cookie: JSESSIONID=0CF6B719D562922F90D6BD08E4F5CE8B; reviewWizardTargetTreeSaveSelectedCookie=root%2Froot%2Ffile1.html; JSESSIONID=xdpzn9258zaj8ziozwmqilnv
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Host: localhost:8081
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept-Language: en-US,en;q=0.8
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Referer: http://localhost:8081/maqetta/
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Connection: keep-alive
Apr 12, 2013 2:13:19 PM org.maqetta.server.DavinciCommandServlet log
INFO: Accept-Encoding: gzip,deflate,sdch
Apr 12, 2013 2:13:44 PM maqetta.core.server.DavinciPageServlet doPut
```

**Comment by peller** [comment]
and the client stack that triggered the request.  It's the rewriteURLs call that triggers the findResource:

```
xhr xhr.js:206
dojo.xhr xhr.js:607
dojo.xhrGet xhr.js:635
Runtime.serverJSONRequest Runtime.js:322
Resource.findResource resource.js:323
(anonymous function) Download.js:115
declare._rewriteUrls Download.js:112
declare.okButton Download.js:158
(anonymous function) lang.js:373
target.(anonymous function).dispatcher aspect.js:94
declare._onClick _ButtonMixin.js:43
inherited declare.js:189
declare._onClick Button.js:64
(anonymous function) lang.js:373
handles
```
