### ISSUE TITLE
Dojo Web Builder: Different result checking checkbox than running DWB manually

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3387]
@peller 

Had a lengthy ST with @peller on this... so, in summary:

Using Maqetta.org, I have a project that if I download as zip with the DWB checkbox on, the result doesn't seem to contain the right dojo.js layer. However, if I manually run the DWB (pointing it at the index.html in my project) then I get the right stuff.

This is coming up because I'm trying to run the downloaded zip through PhoneGap builder and deploy to the Android emulator. Dojo apps running in Android need to have a single dojo layer. 

The PhoneGap result from building the zip file straight out of Maqetta (with DWB checked) does not render correctly in the Android emulator. But, if I modify the zip file to include the DWB output I collected manually and run that through PhoneGap, then that result renders properly in the Android emulator.

The dojo.js in the unmodified Maqetta zip file (with DWB checked) is 156 KB and the one I got from manually using builder is 327 KB. @peller says that indicates the dojo.js file was unmodified in the pure Maqetta case, and something must have crapped out when calling DWB from Maqetta.

**Comment by peller** [comment]
```
java.lang.IllegalStat
eException: FAILED ASSERTION
        at org.mozilla.javascript.Kit.codeBug(Kit.java:480)
        at org.mozilla.javascript.TokenStream.&lt;init&gt;(TokenStream.java:82)
        at org.mozilla.javascript.Parser.parse(Parser.java:336)
        at org.dtk.analysis.script.BaseScriptParser.parse(BaseScriptParser.java:
73)
        at org.dtk.analysis.script.config.BaseScriptConfigParser.initAndParseScr
iptConfiguration(BaseScriptConfigParser.java:92)
        at org.dtk.analysis.script.config.BaseScriptConfigParser.getScriptConfig
(BaseScriptConfigParser.java:79)
        at org.dtk.analysis.page.WebPage.parseScriptConfiguration(WebPage.java:2
89)
        at org.dtk.analysis.page.WebPage.parsePreDojoScript(WebPage.java:177)
        at org.dtk.analysis.page.RemoteWebPage.parsePreDojoScript(RemoteWebPage.
java:86)

        at org.dtk.analysis.page.WebPage.parse(WebPage.java:153)        at org.dtk.analysis.page.RemoteWebPage.&lt;init&gt;(RemoteWebPage.java:62)
        at org.dtk.resources.Dependencies.analyseModulesFromUrl(Dependencies.java:245)
        at org.dtk.resources.Dependencies.analyseDependencies(Dependencies.java:150)
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
...
```

**Comment by peller** [comment]
currently, the dwb checkbox scans all html files in all projects, though it seems to have only encountered your mobile code in file1.html and dojo-theme-editor.html  may be a dup of #3303, as the stack is the same.

**Comment by peller** [comment]
This is what I get when I reduce my workspace to a single project with a single HTML file with two Dijits, Button and Calendar:

```
analyzeWorkspace: number of files: 1
build.dojotoolkit.org: Analyse url=http://app.moketta.org/maqetta/user/E/ws/workspace/p1/file1.html
2012-09-14 21:46:24.480 [qtp413918804-130] WARN  o.a.c.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
build.dojotoolkit.org: Analyse result={"requiredDojoModules":["dojo.parser","dojo._base.lang","dojo.query","dojo.aspect","dojo._base.connect","dojo.dom-style","dojo.dom","dojo._base.html","dojo._base.window","dojo._base.array","dojo.ready","dijit.dijit","dijit.form.Button","dijit.Calendar","dojox.mobile.parser"],"availableModules":["maqetta.space","maqetta.AppStates"],"packages":[{"name":"dojo_web_builder4694715930368537948.tmp","version":"1.0.0"}],"dojoVersion":"UNKNOWN"}
/api/build: {"optimise" : "shrinksafe", "cdn" : "none", "platforms" : "all", "themes" : "claro", "cssOptimise" : "comments", "packages" : [{"name" : "dojo", "version" : "1.7.2"}, {"name" : "dwb", "version" : "1.0.0"}], "layers" : [{"name" : "dojo.js", "modules" : [{"name" : "dojo.parser", "package" : "dojo"}, {"name" : "dojo._base.lang", "package" : "dojo"}, {"name" : "dojo.query", "package" : "dojo"}, {"name" : "dojo.aspect", "package" : "dojo"}, {"name" : "dojo._base.connect", "package" : "dojo"}, {"name" : "dojo.dom-style", "package" : "dojo"}, {"name" : "dojo.dom", "package" : "dojo"}, {"name" : "dojo._base.html", "package" : "dojo"}, {"name" : "dojo._base.window", "package" : "dojo"}, {"name" : "dojo._base.array", "package" : "dojo"}, {"name" : "dojo.ready", "package" : "dojo"}, {"name" : "dijit.dijit", "package" : "dojo"}, {"name" : "dijit.form.Button", "package" : "dojo"}, {"name" : "dijit.Calendar", "package" : "dojo"}, {"name" : "dojox.mobile.parser", "package" : "dojo"}]}]}
2012-09-14 21:46:24.561 [qtp413918804-130] WARN  o.a.c.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
/api/build response: {"error":"Invalid package reference, dojo, in the build request."}
java.net.MalformedURLException
    at java.net.URL.<init>(URL.java:617)
    at java.net.URL.<init>(URL.java:480)
    at java.net.URL.<init>(URL.java:429)
    at maqetta.core.server.command.Download.getBuildURL(Download.java:124)
    at maqetta.core.server.command.Download.handleCommand(Download.java:80)
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:350)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.NullPointerException
    at java.net.URL.<init>(URL.java:522)
    ... 58 more
```

**Comment by aerwin** [comment]
--> back to M7.0.1 at least for discussion... e.g., I know the checkbox is experimental, but if doesn't work at all and we can't fix the underlying issue for M7.0.1, do we need to remove the checkbox until we can?

**Comment by jhpedemonte** [comment]
Regarding last commit, what will user see if DWB download fails?

**Comment by peller** [comment]
@jhpedemonte if an error occurs, because we're treating the zip download as a standard browser download, if the result is HTML rather than a type like application/zip, it will just replace the main page with the error message.  I don't think this is necessarily a bad thing -- I'm a big fan of page transitions -- but I can see how this doesn't fit with the way our app works right now.  It also could be problematic since we do not have a working onbeforeunload event which would trigger a save on open buffers (bug?)  One solution could be to write a more complex download command which uses the new fileapi or some other means to handle the download and any associated errors, but I think we're better off if we can keep it simple.  A better (themed) error template with a back button could help also.

Given the experimental status, I think what's there now is ok.  Surfacing the error is much better than giving the user an unknown result.

**Comment by JonFerraiolo** [comment]
Tried to verify this issue, but DWB didn't work for me, so opened a new issue #3465.
