### ISSUE TITLE
New project beginning with dot causes error

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3388]
also when switching projects after creating the project called ".foo"

```
HTTP ERROR 500

Problem accessing /maqetta/cmd/configProject. Reason:

    commandDescriptor is null or is Put in Get processing
Caused by:

java.lang.AssertionError: commandDescriptor is null or is Put in Get processing
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:42)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:28)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:71)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:25)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:322)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

For consideration in M7.0.1 because it may have catastrophic effects, even though it seems pretty uncommon

**Comment by JonFerraiolo** [comment]
I researched the user problem. Somehow or other he created a project named "." and that because his current project, and our code has problem with such a project name.

**Comment by JonFerraiolo** [comment]
-> @peller - See #3384 - do you know of any issues when you create a project named ".foo"? As you can see by #3384, I tried that and had no problem. The only problem I saw was when the project name was the single letter ".".

If you only saw problems with projects that are named ".", then let's close this.

**Comment by peller** [comment]
This bug report was created when I created a project called ".foo" and got the 500 error on configProject.  Will update my comment to reflect this.

Creating a project called just "." may cause more serious errors, but I wouldn't want to ignore that.

**Comment by JonFerraiolo** [comment]
Could you please try this again? I was successful in creating a new project ".foo" just now.

**Comment by peller** [comment]
Ok, ".foo" works on Orion-integrated builds, fails on lab9.  Would be good to understand why, even if we never ship the former... one of those cases where we may be getting lucky in one particular config?

On any installation, though, just typing "." for a new project name leads to disaster.

**Comment by peller** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
@jhpedemonte - @peller and @JonFerraiolo felt that this one could be done with M8. We have only one user report so far where they inadvertently created a project with name ".", and I suspect we've had this issue for several releases.

**Comment by JonFerraiolo** [comment]
-> M9 Prio-High

@jhpedemonte

**Comment by jhpedemonte** [comment]
-> M10, assign to myself.
