### ISSUE TITLE
500 Server Error: Problem accessing /maqetta/cmd/publish

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3420]
Got this when trying to publish a review on maqetta-test

Also saw 400 errors trying to access blue pages info, but I do not think that was related.
"Problem accessing /maqetta/cmd/getBluePageInfo"

**Comment by aerwin** [comment]
@jhpedemonte Do we possibly have an old `.review` directory on this box?

**Comment by aerwin** [comment]
@jhpedemonte @childsb 

The 500 errors are not occuring now after @jhpedemonte updated the server to the latest build. @jhpedemonte found this in the logs from before the upgrade:

```
2012-09-20 09:44:20.132 [qtp30987167-58] INFO  org.eclipse.orion.server.login - Login success: B 2012-09-20 09:44:36.577 [qtp30987167-67] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/listVersions java.lang.NullPointerException: null         at maqetta.server.orion.user.OrionPersonManager$OrionPersonImpl.getEmail(OrionPersonManager.java:41) ~[na:na]         at maqetta.server.orion.user.OrionPersonManager.getPersonByEmail(OrionPersonManager.java:134) ~[na:na]         at org.davinci.server.review.user.Reviewer.getUserID(Reviewer.java:32) ~[na:na]         at maqetta.core.server.command.ListVersions.handleCommand(ListVersions.java:70) ~[na:na]         at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52) ~[na:na]         at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]         at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]         at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]  
10:50:56 AM: pedemont@us.ibm.com - Javier H Pedemonte/Austin/IBM: quite a few of those exceptions also in /var/log/maqetta.log.1 (rotated log) 
```

This is the same exception as in #3143 which @childsb closed 20 days ago after we discovered (in that case) that MAQETTA_WORKSPACE was set to point at a workspace dir with a bad .review directory in it.

I'm not sure we have any good explanation for what the situation was before the build was upgraded in this case.

**Comment by aerwin** [comment]
In #3143, I had done some analysis into OrionPersonManager related to the and it looked like something had to be wrong with the `IOrionCredentialsService` and I passed it back to @childsb with the question:

> can you envision how there might not be a valid user in the IOrionCredentialsService that matches an entry in the list of persons?

Since then, we've uncovered a couple of additional problems that may or may not play a role here:
- #3406: Orion user id's are not consistent
- #3407: PersonManager only works with people who have logged in since last time server started

**Comment by jhpedemonte** [comment]
I reopened #3143, since I still see that exception in the latest server logs.  Don't know if this bug should be duped to that one or vice versa, or if they are slightly different.  I'll leave it up to @aerwin.

**Comment by aerwin** [comment]
Yes, definitely a dup of #3143. So, closing.

**Comment by peller** [comment]
fwiw, I did see the 500 error on listVersions, but only after the error I got on publish (and on new sessions after that)

**Comment by aerwin** [comment]
@peller Can you successfully create a review now (since the server has been refreshed)?

**Comment by peller** [comment]
@aerwin yes, works now
