### ISSUE TITLE
IllegalStateException in "cmd/addFiles"

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3426]
```
2012-09-14 09:47:02.980 [qtp1256033805-68] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/addFiles
java.lang.IllegalStateException: Committed
    at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1090) ~[org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
    at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:232) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.eclipse.jetty.http.gzip.CompressedResponseWrapper.resetBuffer(CompressedResponseWrapper.java:228) ~[org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.eclipse.jetty.http.gzip.CompressedResponseWrapper.sendError(CompressedResponseWrapper.java:253) ~[org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
    at org.maqetta.server.DavinciCommandServlet.doPost(DavinciCommandServlet.java:126) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

@maqetta/committers

**Comment by jhpedemonte** [comment]
I only see this exception on Sept 14, roughly coinciding with times when the server was deadlocked (see #3374).  So closing this one.
