### ISSUE TITLE
NPE in SMTPTransport

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3427]
```
Exception in thread "Thread-56" java.lang.NullPointerException
    at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1062)
    at org.maqetta.server.mail.SmtpPop3Mailer.sendMessage(SmtpPop3Mailer.java:184)
    at org.maqetta.server.mail.SmtpPop3Mailer.sendMessage(SmtpPop3Mailer.java:191)
    at org.maqetta.server.ServerManager.sendEmail(ServerManager.java:283)
    at maqetta.server.orion.hosted.command.Register$EmailRunnable.run(Register.java:32)
    at java.lang.Thread.run(Thread.java:679)
```

**Comment by jhpedemonte** [comment]
Seen about 17 times since M7 launch on maqetta.org, always following a registration.  I hope this isn't preventing users from getting their registration email.

@JonFerraiolo @peller

**Comment by jhpedemonte** [comment]
Did a spot check of some of the affected users and they all seem to have logged in.  So at least the registration email is getting sent, before (or despite) this error.

**Comment by jhpedemonte** [comment]
Added logging for M7.0.1.  Pushing to M8.

**Comment by jhpedemonte** [comment]
Now using Orion's email APIs.  Closing.
