### ISSUE TITLE
NPE in "cmd/deleteResource" request

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3428]
```
2012-09-14 14:24:06.108 [qtp1033806195-228] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/deleteResource
java.lang.NullPointerException: null
    at maqetta.core.server.command.DeleteResource.handleCommand(DeleteResource.java:21) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

@maqetta/committers 

---

Also seeing NPE with ["cmd/rename"](https://github.com/maqetta/maqetta/issues/3428#issuecomment-8743030).

**Comment by jhpedemonte** [comment]
This one's been happening daily on average, since M7 launch.

**Comment by jhpedemonte** [comment]
Also seeing this, which is probably the same issue.

```
2012-09-19 05:22:51.407 [qtp254232091-3081] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/rename
java.lang.NullPointerException: null
    at maqetta.core.server.command.Rename.handleCommand(Rename.java:25) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```
