### ISSUE TITLE
MalformedURLException when calling Dojo Web Builder

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3429]
```
2012-09-14 15:28:05.678 [qtp811495456-91] WARN  org.eclipse.jetty.http.HttpGenerator - Ignoring extra content OK
2012-09-14 15:28:09.376 [qtp811495456-100] WARN  org.eclipse.jetty.http.HttpGenerator - Ignoring extra content OK
analyzeWorkspace: number of files: 1
build.dojotoolkit.org: Analyse url=http://app.moketta.org/maqetta/user/E/ws/workspace/p1/file1.html
2012-09-14 15:29:41.345 [qtp811495456-98] WARN  o.a.c.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
build.dojotoolkit.org: Analyse result={"requiredDojoModules":["dojo.parser","dojo._base.lang","dojo.query","dojo.aspect","dojo._base.connect","dojo.dom-style","dojo.dom","dojo._base.html","dojo._base.window","dojo._base.array","dojo.ready","dijit.dijit","dijit.form.Button","dijit.Calendar","dojox.mobile.parser"],"availableModules":["maqetta.space","maqetta.AppStates"],"packages":[{"name":"dojo_web_builder2902919527442284658.tmp","version":"1.0.0"}],"dojoVersion":"UNKNOWN"}
/api/build: {"optimise" : "shrinksafe", "cdn" : "none", "platforms" : "all", "themes" : "claro", "cssOptimise" : "comments", "packages" : [{"name" : "dojo", "version" : "1.7.2"}, {"name" : "dwb", "version" : "1.0.0"}], "layers" : [{"name" : "dojo.js", "modules" : [{"name" : "dojo.parser", "package" : "dojo"}, {"name" : "dojo._base.lang", "package" : "dojo"}, {"name" : "dojo.query", "package" : "dojo"}, {"name" : "dojo.aspect", "package" : "dojo"}, {"name" : "dojo._base.connect", "package" : "dojo"}, {"name" : "dojo.dom-style", "package" : "dojo"}, {"name" : "dojo.dom", "package" : "dojo"}, {"name" : "dojo._base.html", "package" : "dojo"}, {"name" : "dojo._base.window", "package" : "dojo"}, {"name" : "dojo._base.array", "package" : "dojo"}, {"name" : "dojo.ready", "package" : "dojo"}, {"name" : "dijit.dijit", "package" : "dojo"}, {"name" : "dijit.form.Button", "package" : "dojo"}, {"name" : "dijit.Calendar", "package" : "dojo"}, {"name" : "dojox.mobile.parser", "package" : "dojo"}]}]}
2012-09-14 15:29:41.454 [qtp811495456-98] WARN  o.a.c.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
/api/build response: {"error":"Invalid package reference, dojo, in the build request."}
java.net.MalformedURLException
    at java.net.URL.<init>(URL.java:617)
    at java.net.URL.<init>(URL.java:480)
    at java.net.URL.<init>(URL.java:429)
    at maqetta.core.server.command.Download.getBuildURL(Download.java:124)
    at maqetta.core.server.command.Download.handleCommand(Download.java:80)
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:350)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.NullPointerException
    at java.net.URL.<init>(URL.java:522)
    ... 58 more
```

I think there were some fixes done on the Dojo Web Builder end, so this may no longer be an issue.  But should still be investigated.

**Comment by aerwin** [comment]
Maybe a dup of #3387?

**Comment by jhpedemonte** [comment]
Too right, thanks Tony. Dupe to #3387.

**Comment by peller** [comment]
Hrm.  #3387 seems to indicate two separate problems, but ok, we'll manage both there.
