### ISSUE TITLE
NPE in DavinciPageServlet.writePage()

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3433]
```
2012-09-15 10:15:26.566 [qtp1301257077-69] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/user/Kv/ws/workspace/project1/samples
java.lang.NullPointerException: null
    at maqetta.core.server.DavinciPageServlet.writePage(DavinciPageServlet.java:340) ~[na:na]
    at maqetta.core.server.DavinciPageServlet.handleLibraryRequest(DavinciPageServlet.java:319) ~[na:na]
    at maqetta.core.server.DavinciPageServlet.handleWSRequest(DavinciPageServlet.java:279) ~[na:na]
    at maqetta.core.server.DavinciPageServlet.doGet(DavinciPageServlet.java:137) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

@maqetta/committers

**Comment by jhpedemonte** [comment]
Only see one instance of this since Sept 12.

I just noticed that this is a `writePage` call to **samples** directory.  Do we still allow this?  I thought we had client-side code to catch and disallow writes to read-only directories.
