### ISSUE TITLE
"File already exists" server error

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3436]
```
org.eclipse.core.runtime.CoreException: File already exists on disk: /var/lib/maqetta/users/U4/lib/file1.html.
        at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:55)
        at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:50)
        at org.eclipse.core.internal.filesystem.local.LocalFile.move(LocalFile.java:319)
        at maqetta.server.orion.VOrionStorage.renameTo(VOrionStorage.java:179)
        at org.maqetta.server.VFile.flushWorkingCopy(VFile.java:308)
        at maqetta.core.server.DavinciPageServlet.doPut(DavinciPageServlet.java:92)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:758)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
```

3 times since Sept 12.

@maqetta/committers

**Comment by JonFerraiolo** [comment]
This could be the result of someone having multiple Maqetta windows open. Maybe in one window they created file1.html and then in another window they don't refresh and try to create file1.html again.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte

**Comment by peller** [comment]
FWIW, I noticed this code in davinci/model/resource/Folder.js createResource:

```
            /* resource already exists on server, so just be gracefull about it. */
```

Seems like this ought to be treated as an error condition.
