### ISSUE TITLE
NPE when calling "cmd/createProject"

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3438]
```

2012-09-20 07:04:34.149 [qtp1690464956-1214] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/createProject
java.lang.NullPointerException: null
    at java.lang.String.compareTo(String.java:1176) ~[na:1.6.0_24]
    at maqetta.server.orion.VOrionWorkspaceStorage.get(VOrionWorkspaceStorage.java:101) ~[na:na]
    at maqetta.server.orion.VOrionWorkspaceStorage.createProj(VOrionWorkspaceStorage.java:55) ~[na:na]
    at maqetta.server.orion.VOrionWorkspaceStorage.create(VOrionWorkspaceStorage.java:44) ~[na:na]
    at maqetta.server.orion.VOrionStorage.newInstance(VOrionStorage.java:212) ~[na:na]
    at maqetta.core.server.user.User.addBaseSettings(User.java:209) ~[na:na]
    at maqetta.server.orion.user.OrionUser.createProject(OrionUser.java:203) ~[na:na]
    at maqetta.core.server.user.User.createProject(User.java:154) ~[na:na]
    at maqetta.core.server.command.CreateProject.handleCommand(CreateProject.java:23) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

@JonFerraiolo, I know you recently looked at an issue where projects with "." failed.  Could this be related?

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte
