### ISSUE TITLE
NPE when invoking "cmd/configProject"

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3439]
```
2012-09-19 10:11:17.506 [qtp1021946387-45] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/configProject
java.lang.NullPointerException: null
    at maqetta.core.server.util.VResourceUtils.matches(VResourceUtils.java:52) ~[na:na]
    at maqetta.server.orion.VOrionStorage.findFiles(VOrionStorage.java:239) ~[na:na]
    at maqetta.server.orion.user.OrionUser.isProject(OrionUser.java:148) ~[na:na]
    at maqetta.server.orion.user.OrionUser.createProject(OrionUser.java:175) ~[na:na]
    at maqetta.core.server.user.User.createProject(User.java:154) ~[na:na]
    at maqetta.server.orion.command.ConfigProject.handleCommand(ConfigProject.java:30) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte
