### ISSUE TITLE
Manual creation of user fails

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3467]
Tried to create a user through the Orion admin panel, but failed with this error:

```
2012-09-25 07:12:19.677 [qtp827506119-213] WARN  o.e.jetty.servlet.ServletHandler - /users
java.lang.NullPointerException: null
        at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:649) ~[na:na]
        at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:805) ~[na:na]
        at maqetta.server.orion.hosted.RegistrationFilter.doFilter(RegistrationFilter.java:36) ~[na:na]
        at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) ~[na:na]
```

**Comment by jhpedemonte** [comment]
@skaegi, did you ever run into such an issue with Orion v0.5?

**Comment by jarthorn** [comment]
I don't know what RegistrationFilter.doFilter is doing, but you are passing a null argument to EclipsePreferences.node.

**Comment by jhpedemonte** [comment]
@skaegi @jarthorn Sorry about that, got confused with another stack which was pure Orion.

Looks like RegistrationFilter was written for one specific case and did not take into account this case.

**Comment by jhpedemonte** [comment]
Moving to M8.  Too risky a fix for 7.0.1.

**Comment by jhpedemonte** [comment]
-> M9

**Comment by jhpedemonte** [comment]
No longer an issue.  Closing.
