### ISSUE TITLE
Red screen of death when missing BODY element

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3554]
I added the meta tag for ie ''''<meta http-equiv="X-UA-Compatible" content="IE=edge">'''' but forgot the `/`   clicked back to design view an nothing the browsers was hung. so I refreshed the browser and then got the red screen of death. At this point I am loucked out of my id. I can't reset my workspace or edit the file to fix the syntax error...

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/form/Button"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</meta>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{'states':['blue_state']}">
 <div data-maq-deltas="{'blue_state':{'style':[{'background-color':'blue'}]}}">
   Div</div>
 <input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Blue/hide" iconClass="dijitNoIcon" onclick="davinci.states.setState('blue_state')"></input>
 <input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Trans/show" iconClass="dijitNoIcon" onclick="davinci.states.setState('Normal')"></input>
 <div data-maq-deltas="{'blue_state':{'style':[{'display':'none !important'}]}}">
 Hide div</div>
 </body>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates"
]);
</script>
</head>
</html>
```

**Comment by jhpedemonte** [comment]
A couple of things to try:
1. I think Jon added code that if you do a **Shift+click** on the **Login** button, it will open Maqetta with all editors closed.
2. Login straight into Orion (drop the "/maqetta" from the URL) and edit/delete the file from there.

**Comment by peller** [comment]
can you record the contents of the RSOD?

**Comment by JonFerraiolo** [comment]
Here is the contents of the RSOD:

h oh! An error has occurred:
Cannot call method 'addAttribute' of undefined
Error: Cannot call method 'addAttribute' of undefined
    at declare._continueLoading (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:1101:18)
    at null. (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:1040:10)
    at runFactory (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/dojo.js:1094:43)
    at execModule (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/dojo.js:1223:5)
    at http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/dojo.js:1258:6
    at guardCheckComplete (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/dojo.js:1238:5)
    at checkComplete (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/dojo.js:1253:4)
    at onLoad (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/dojo.js:1308:7)
    at HTMLDocument.detectReady (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/domReady.js:22:22)

**Comment by JonFerraiolo** [comment]
@peller - do you have time to look at this one? If so, please reassign to yourself.'

The RSOD isn't the big problem here. The big problem is that upon browser refresh the application doesn't refresh itself properly (probably because the parser doesn't create a model), so no toolbar (which means no ability to switch to source view). My best guess is that the parser is dying and we aren't recovering satisfactorily. The fix is probably too risky for M8, but would be good to explore and see what's actually broken and what the fix might be.

**Comment by billreed63** [comment]
I do not see red screen now I see spinning wheel....
and this exception in console

```
TypeError
 "TypeError: Cannot call method 'getChildElement' of undefined
    at declare.addJavaScriptSrc (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:2932:41)
    at _loadJSFile (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:433:19)
    at declare.loadRequires (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:460:21)
    at Array.every (native)
    at declare.loadRequires (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:448:12)
    at declare._setSource (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:859:9)
    at declare._setContentRaw (http://localhost:8081/maqetta/app/davinci/ve/VisualEditor.js?@revision@:305:17)
    at declare._setContent (http://localhost:8081/maqetta/app/davinci/ve/VisualEditor.js?@revision@:266:8)
    at declare.setContent (http://localhost:8081/maqetta/app/davinci/ve/VisualEditor.js?@revision@:258:8)
    at declare.setContent (http://localhost:8081/maqetta/app/davinci/ve/PageEditor.js?@revision@:350:21)
    ----------------------------------------
    rejected at signalDeferred (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:78:15)
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:49:5)
    at signalWaiting (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:28:4)
    at Deferred.resolve (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:186:5)
    at signalDeferred (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:75:15)
    at makeDeferredSignaler (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:64:4)
    at notify (http://localhost:8081/maqetta/app/dojo/_base/Deferred.js?@revision@:187:23)
    at complete (http://localhost:8081/maqetta/app/dojo/_base/Deferred.js?@revision@:168:4)
    at dojo.Deferred.resolve.callback (http://localhost:8081/maqetta/app/dojo/_base/Deferred.js?@revision@:215:4)
    at notify (http://localhost:8081/maqetta/app/dojo/_base/Deferred.js?@revision@:196:69)
    ----------------------------------------
[object Deferred]
    at Promise.Deferred.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:246:24)
    at declare.setEditor (http://localhost:8081/maqetta/app/davinci/workbench/EditorContainer.js?@revision@:110:8)
    at runFactory (http://localhost:8081/maqetta/app/dojo/dojo.js?@revision@:1081:43)
    at execModule (http://localhost:8081/maqetta/app/dojo/dojo.js?@revision@:1210:5)
    at contextRequire (http://localhost:8081/maqetta/app/dojo/dojo.js?@revision@:777:7)
    at guardCheckComplete (http://localhost:8081/maqetta/app/dojo/dojo.js?@revision@:1225:5)
    at contextRequire (http://localhost:8081/maqetta/app/dojo/dojo.js?@revision@:776:6)
    at result (http://localhost:8081/maqetta/app/dojo/dojo.js?@revision@:796:13)
    at declare.setEditor (http://localhost:8081/maqetta/app/davinci/workbench/EditorContainer.js?@revision@:51:3)
    at Object.Workbench._createEditor (http://localhost:8081/maqetta/app/davinci/Workbench.js?@revision@:1503:19)" instrumentation.js:18
logError instrumentation.js:18
(anonymous function) instrumentation.js:57
array.filter array.js:326
logRejected instrumentation.js:55
```

**Comment by peller** [comment]
We were throwing exceptions in various places, such as validating toolbar icons, P6 compatibility code, etc.

Will still post a RSOD if the parser does not create a BODY element, but hopefully the rest of the workbench will be sane.  @JonFerraiolo, please verify and defer to M9 with lower priority.  Given that our visual and source editors are both bound to the Context object and the model, without a document the parser can model, there will be no source or visual editors, so the RSOD is the right behavior for now.  Perhaps we should post a special error message in attachAll() if there is no body, or better yet it would be great if the parser provided error messages which we could post to the user.  It would also be good to be able to launch a source editor without a valid context.

**Comment by JonFerraiolo** [comment]
@peller checkins look good

-> M9 Prio-Med

**Comment by peller** [comment]
changed title to reflect remaining bug: RSOD on missing BODY element
