### ISSUE TITLE
500 error  updating R&C comment

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3556]
testing 702 at 2:19pm central time

Error description: error to update comment , response=RequestError: Unable to load cmd/updateComment?id=ed60200f-8037-a590-c82f-7c7dda5be381&subject=something%20missing%20here%3F&content=something%20doesn't%20look%20right&pageStateList=%5B%5D&viewSceneList=%7B%22DojoMobileViews%22%3A%5B%5D%7D&drawingJson=%5B%7B%22type%22%3A%22Ellipse%22%2C%22x1%22%3A17%2C%22y1%22%3A36%2C%22x2%22%3A194%2C%22y2%22%3A53%2C%22colorAlias%22%3A%22apeller%40us.ibm.com%22%2C%22commentId%22%3A%22ed60200f-8037-a590-c82f-7c7dda5be381%22%2C%22stateList%22%3A%22%5B%5D%22%2C%22sceneList%22%3A%22%7B%5C%22DojoMobileViews%5C%22%3A%5B%5D%7D%22%7D%2C%7B%22type%22%3A%22Ellipse%22%2C%22x1%22%3A17%2C%22y1%22%3A36%2C%22x2%22%3A194%2C%22y2%22%3A53%2C%22colorAlias%22%3A%22apeller%40us.ibm.com%22%2C%22commentId%22%3A%22ed60200f-8037-a590-c82f-7c7dda5be381%22%2C%22stateList%22%3A%22%5B%5D%22%2C%22sceneList%22%3A%22%7B%5C%22DojoMobileViews%5C%22%3A%5B%5D%7D%22%7D%5D status: 500 , reason=Error 500 Server Error

**Comment by peller** [comment]
cannot reproduce, but we should check the server logs

**Comment by jhpedemonte** [comment]
Here's the stack trace from server log:

```
RequestURL: https://maqetta-test:50000/maqetta/cmd/updateComment
Query: id=ed60200f-8037-a590-c82f-7c7dda5be381&subject=something%20missing%20here%3F&content=something%20doesn%27t%20look%20right&pageStateList=%5B%5D&viewSceneList=%7B%22DojoMobileViews%22%3A%5B%5D%7D&drawingJson=%5B%7B%22type%22%3A%22Ellipse%22%2C%22x1%22%3A17%2C%22y1%22%3A36%2C%22x2%22%3A194%2C%22y2%22%3A53%2C%22colorAlias%22%3A%22apeller%40us.ibm.com%22%2C%22commentId%22%3A%22ed60200f-8037-a590-c82f-7c7dda5be381%22%2C%22stateList%22%3A%22%5B%5D%22%2C%22sceneList%22%3A%22%7B%5C%22DojoMobileViews%5C%22%3A%5B%5D%7D%22%7D%2C%7B%22type%22%3A%22Ellipse%22%2C%22x1%22%3A17%2C%22y1%22%3A36%2C%22x2%22%3A194%2C%22y2%22%3A53%2C%22colorAlias%22%3A%22apeller%40us.ibm.com%22%2C%22commentId%22%3A%22ed60200f-8037-a590-c82f-7c7dda5be381%22%2C%22stateList%22%3A%22%5B%5D%22%2C%22sceneList%22%3A%22%7B%5C%22DojoMobileViews%5C%22%3A%5B%5D%7D%22%7D%5D
X-Requested-With: XMLHttpRequest
Cookie: JSESSIONID=4ouw4mthoog7106gt4ryef4kr
Host: maqetta-test:50000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Content-Type: application/x-www-form-urlencoded
Accept-Language: en-US,en;q=0.5
Referer: https://maqetta-test:50000/maqetta/
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0
Accept-Encoding: gzip, deflate
2012-10-26 14:18:46.597 [qtp17427094-133] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/updateComment
java.lang.NullPointerException: null
    at maqetta.server.orion.user.OrionUserManager.assertValidUserId(OrionUserManager.java:44) ~[na:na]
    at maqetta.server.orion.user.OrionUserManager.getUser(OrionUserManager.java:78) ~[na:na]
    at maqetta.core.server.user.ReviewManager.getDesignerUser(ReviewManager.java:224) ~[na:na]
    at maqetta.core.server.command.UpdateComment.handleCommand(UpdateComment.java:30) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:70) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:129) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

I added the code for `assertValidUserId` -- this means that `getUser` was called with an email address, but it expected an Orion user ID (ie. "A", "Bc", etc).

**Comment by JonFerraiolo** [comment]
Which http error code is caused by having too many cookies (which causes the URL string to be too long for Jetty)? Maybe that's a 403 and not a 500.

**Comment by peller** [comment]
It said 500, and the exception would seem to confirm that.

Could not reproduce this problem.

**Comment by jhpedemonte** [comment]
I cannot reproduce this error.

However, it looks like the reason for this error is that the query in the URL is missing the `designerId` argument.  When testing, I see it between `id` and `subject` in the URL, however it is missing in the stack trace.

**Comment by jhpedemonte** [comment]
There's probably something wrong in the client-side R&C code.  The `designerId` comes from _Comment.js_ and is set in _CommentView.js_, in the function `_getDesignerId()`.  Unfortunately, by just looking at the code, I'm not sure what could be going wrong.

This bug isn't specific to 7.0.2 and has probably existed since at least 7.0.0, if not earlier.  Given that it is difficult to reproduce, no sense in holding up 7.0.2 for this.

**Comment by jhpedemonte** [comment]
Lowered priority/severity to High/2.

At the very least, we could make it so that `_getDesignerId()` throws an error if it **does not** return a non-null value, since a valid designer ID is expected by callers.

**Comment by peller** [comment]
agreed.  not a blocker for 7.0.2, perhaps not even high/2

**Comment by jhpedemonte** [comment]
-> M9/Med/S3

**Comment by peller** [comment]
->M10
