### ISSUE TITLE
Nightly build fails to load with existing "users" dir

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3564]
Deployed one of the nightlies to our test server and started up Maqetta server, pointing to an existing _users_ directory.

Doesn't load in browser (just hangs on "Loading Maqetta...").  On the server, I see this error:

```
RequestURL: http://maqetta-app-test.austin.ibm.com/maqetta/cmd/getInitializationInfo
X-Requested-With: XMLHttpRequest
Cookie: JSESSIONID=5epkar5spj1d1harof68o0za0
Host: maqetta-app-test.austin.ibm.com
Accept: */*
X-Forwarded-For: 9.41.22.235
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Content-Type: application/x-www-form-urlencoded
Accept-Language: en-US,en;q=0.8
Referer: http://maqetta-app-test.austin.ibm.com/maqetta/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11
Connection: close
X-Real-IP: 9.41.22.235
Accept-Encoding: gzip,deflate,sdch
2012-11-13 15:13:33.922 [qtp16290468-27] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/getInitializationInfo
java.lang.NullPointerException: null
        at java.io.File.<init>(File.java:239) ~[na:1.6.0_18]
        at maqetta.server.orion.command.GetInitializationInfo.getSiteJson(GetInitializationInfo.java:56) ~[na:na]
        at maqetta.server.orion.command.GetInitializationInfo.handleCommand(GetInitializationInfo.java:34) ~[na:na]
        at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:70) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:129) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) ~[na:na]
        at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50) ~[na:na]
        at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) ~[na:na]
        at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92) ~[na:na]
        at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) ~[na:na]
```

**Comment by JonFerraiolo** [comment]
Might be a permissions problem. The offending line of code is:

```
         File folder = new File(siteConfigDir);
```

**Comment by billreed63** [comment]
I think the siteConfig folder is missing 

```
# check for site configuration Directory
MAQ_CONFIG_DIR=$MAQ_BASE/siteConfig
test -r $MAQ_CONFIG_DIR || { echo "$MAQ_CONFIG_DIR not found"; exit 1; }

# Some props (such as 'admin' password) **must** be in a config file; passing
# them on the command line won't work.
JAVA_ARGS="${JAVA_ARGS} -Dorion.core.configFile=${MAQ_CONFIG}"
# Site configuration json files
JAVA_ARGS="${JAVA_ARGS} -Dmaqetta.siteConfigDirectory=${MAQ_CONFIG_DIR}" 
```

How does the sever get started on the test server?

**Comment by jhpedemonte** [comment]
OK, it was a misconfiguration.  I'm using a different script to launch Maqetta server, not the launch scripts that come within the zip.  Added the relevant bits and it's all fine now.  Thanks.
