### ISSUE TITLE
Server error w/ cmd/resetPassword

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3582]
Tried to reset password, using Firefox and maqetta-test.  I got no error client-side, but saw this on the server:

```
RequestURL: http://maqetta-app-test/maqetta/cmd/resetPassword
Cookie: maqExplorer=project1%2Cproject1%2Fargl%2Cproject1%2Fthemes%2Fthemes%2Fthemes%2Cfoobar%2Cproject1%2Ffolder1%2Ffolder1%2Cproject1%2Fhello%2Cproject1%2Ffoobarargl; resourceTreeSaveSelectedCookie=project1%2Ffile1.html; dijit_Tree_6SaveSelectedCookie=project1%2Fapp.css; dijit_Tree_8SaveSelectedCookie=project1%2Fapp.js; dijit_Tree_10SaveSelectedCookie=project1%2Fargl%2Ffargl.html; dijit_Tree_15SaveSelectedCookie=project1%2Fargl%2Ffargl.html; JSESSIONID=t5f4xru2clkaipqdv7oetkdc
DNT: 1
Host: maqetta-app-test
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Content-Length: 40
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept-Language: en-US,en;q=0.5
Pragma: no-cache
Referer: http://maqetta-app-test/mixloginstatic/LoginWindow.html?redirect=../maqetta/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0
Connection: close
Cache-Control: no-cache
Orion-Version: 1
Accept-Encoding: gzip, deflate
2012-11-28 19:41:30.259 [qtp12774933-23] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/resetPassword
java.lang.NullPointerException: null
    at maqetta.core.server.user.User.getUserID(User.java:618) ~[na:na]
    at maqetta.server.orion.user.OrionUser.<init>(OrionUser.java:52) ~[na:na]
    at maqetta.server.orion.user.OrionUserManager.newUser(OrionUserManager.java:100) ~[na:na]
    at maqetta.server.orion.user.OrionUserManager.getUserByEmail(OrionUserManager.java:94) ~[na:na]
    at maqetta.server.orion.user.OrionUserManager.isValidUserByEmail(OrionUserManager.java:172) ~[na:na]
    at maqetta.server.orion.hosted.command.ResetPassword.handleCommand(ResetPassword.java:49) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doPost(DavinciCommandServlet.java:158) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:129) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

@peller

**Comment by jhpedemonte** [comment]
I've yet to get the email, so this error is preventing this functionality.

**Comment by jhpedemonte** [comment]
@aerwin is seeing the same thing (although it started working again for me at some point, so it's an intermittent issue).

**Comment by jhpedemonte** [comment]
The issue is in **OrionPersonManager.java**:  much of that code makes use of the hash table `persons`, which only gets loaded lazily.

However, if a user hasn't properly logged in since the server started, an attempt to reset the password will fail -- the call to `OrionPersonManager.getPersonByEmail()` will fail since the given user has yet to be added to the `persons` hash table.
