### ISSUE TITLE
Download files -> NullPointerException on server

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3718]
getLibRoots url command specifies libid and version, but not a 'base' argument. leads to server exception. No obvious side effects.

```
java.lang.NullPointerException
        at java.lang.String.compareTo(String.java:1167)
        at maqetta.server.orion.VOrionWorkspaceStorage.get(VOrionWorkspaceStorage.java:100)
        at maqetta.server.orion.VOrionWorkspaceStorage.create(VOrionWorkspaceStorage.java:37)
        at maqetta.server.orion.VOrionStorage.newInstance(VOrionStorage.java:186)
        at maqetta.core.server.user.User.getLibSettings(User.java:232)
        at maqetta.core.server.user.User.getLibs(User.java:571)
        at maqetta.core.server.user.User.getLibPath(User.java:602)
        at maqetta.core.server.command.GetLibRoots.handleCommand(GetLibRoots.java:20)
        at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:70)
```

**Comment by peller** [comment]
cannot reproduce this one either
