### ISSUE TITLE
Error creating TabContainer on canvas

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3770]
New desktop file. Try adding a TabContainer.

```
TypeError {stack: "TypeError: undefined is not a function↵    at decl…orkspace/project1/lib/dojo/dojo/parser.js:138:16)"}
 "TypeError: undefined is not a function
    at declare._makeController (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dijit/layout/TabContainer.js:50:11)
    at declare.buildRendering (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dijit/layout/_TabContainerBase.js:58:23)
    at declare.create (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dijit/_WidgetBase.js:359:8)
    at declare.postscript (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dijit/_WidgetBase.js:300:8)
    at new <anonymous> (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/_base/declare.js:390:7)
    at Object.parser.construct (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/parser.js:425:71)
    at Object.<anonymous> (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/parser.js:170:17)
    at Object.array.map (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/_base/array.js:278:24)
    at Object.parser._instantiate (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/parser.js:164:25)
    at Object.parser.instantiate (http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/dojo/dojo/parser.js:138:16)
    ----------------------------------------
    rejected at signalDeferred (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:84:15)
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:55:5)
    at signalWaiting (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:28:4)
    at resolve (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:192:5)
    at http://localhost:8081/maqetta/app/dojo/promise/all.js?@revision@:68:16
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:37:21)
    at signalWaiting (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:28:4)
    at resolve (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:192:5)
    at http://localhost:8081/maqetta/app/dojo/promise/all.js?@revision@:68:16
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:37:21)
    ----------------------------------------
[object Deferred]
    at Promise.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:252:24)
    at declare._create (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:615:17)
    at null.<anonymous> (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:601:9)
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:37:21)
    at Promise.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:258:5)
    at declare.create (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:600:41)
    at declare.onMouseUp (http://localhost:8081/maqetta/app/davinci/ve/tools/CreateTool.js?@revision@:407:9)
    at declare.onMouseUp (http://localhost:8081/maqetta/app/davinci/ve/Context.js?@revision@:2323:21)
    at Object.dispatcher.around.advice (http://localhost:8081/maqetta/app/dojo/aspect.js?@revision@:103:23)
    at target.(anonymous function).dispatcher [as onMouseUp] (http://localhost:8081/maqetta/app/dojo/aspect.js?@revision@:85:39)" 
```

**Comment by peller** [comment]
Some loader weirdness here.  In TabContainer, the 3rd and 4th dependencies are not defined:  _TabContainerBase and TabController, leading to the exception
