### ISSUE TITLE
save-as widget fails on reload

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3808]
Created a simple widget. dropped on page.  looks good.
save. close. reopen -> parse error

```
Error: Unable to resolve constructor for: 'a.b'
    at Object.<anonymous> (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/parser.js:72:7)
    at Object._578.map (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/dojo.js:6794:13)
    at Object._1b._instantiate (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/parser.js:69:12)
    at http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/parser.js:409:27
    at _4b8 (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/dojo.js:5850:10)
    at Promise.then._4c5.then (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/dojo.js:5966:1)
    at Object._1b.parse (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/parser.js:408:4)
    at null.<anonymous> (http://maqetta-app-test.austin.ibm.com/maqetta/app/davinci/davinci.js?f37acb8a565cc244eb1b52aed0c3613cb885b3fa:58031:44)
    at _5de (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/dojo.js:7273:1)
    at _5da (http://maqetta-app-test.austin.ibm.com/maqetta/user/BPC/ws/workspace/project1/lib/dojo/dojo/dojo.js:7246:1) davinci.js:57826
```

**Comment by peller** [comment]
fixed by @JonFerraiolo's checkin 581b76e6fd24a9af696842d97971eaf934c4fb2b
