### ISSUE TITLE
Server exception on first save on new theme

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3897]
Windows 7/ chrome
1) Create new mobile theme clone of custom, in this case I called it custom1
2) Make a change to the theme, set the background gradient of header
3) Click on the save and notice the following exception on the server

```
org.eclipse.core.runtime.CoreException: Problems encountered while deleting files.
    at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:125)
    at maqetta.server.orion.VOrionStorage.delete(VOrionStorage.java:52)
    at org.maqetta.server.VFile.flushWorkingCopy(VFile.java:303)
    at maqetta.core.server.DavinciPageServlet.doPut(DavinciPageServlet.java:127)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:758)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:99)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.CacheFilter.doFilter(CacheFilter.java:73)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
    at org.eclipse.orion.server.configurator.servlet.ExcludedExtensionGzipFilter.doFilter(ExcludedExtensionGzipFilter.java:42)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:350)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:900)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:954)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
    at java.lang.Thread.run(Thread.java:722)
Contains: Could not delete: C:\__maqetta_server_workspace\a\themes\custom1\custom1.css.
```

The code in org.maqetta.server.VFile.flushWorkingCopy(VFile.java:303)

```
 public void flushWorkingCopy() throws IOException {
        // String name = this.file.getName();
        if (this.workingCopy.exists()) {
            this.file.delete();
            this.workingCopy.renameTo(this.file);

        }

        /*
         * try { this.file.createNewFile(); } catch (IOException e) { // TODO
         * Auto-generated catch block e.printStackTrace(); }
         * this.copyfile(this.workingCopy, this.file);
         */

        // this.workingCopy.delete();
    }
```

**Comment by peller** [comment]
@billreed63 what's the flow here?  Is it that custom1.css does not exist, only a working copy?  Is the right thing to do to check for this.file.exists() before calling delete?

@jhpedemonte

**Comment by billreed63** [comment]
The files exists,

I create a new theme I will use claro1 which is a clone of claro in this example.
When claro1 is created the theme editor is opened with claro1, at this point I looks on my servers file system and I see `themes/claro1/claro1.css /themes/claro1.theme and themes/claro1/document.css` It all looks good at this point.

I then change something in the theme, like the background image gradient of the button, at this point I see that I have 
 `themes/claro1/claro1.css themes/claro1/claro1.css.workingcopy /themes/claro1.theme and themes/claro1/document.css` on the servers files system. 

I then click on the save button 
in `VFile.flushWorkingCopy`  the `if (this.workingCopy.exists()) {` tests true because claro1.css exists 
we then execute the `this.file.delete();`  to delete the claro1.css. the delete throws an exception which is caught  `maqetta.server.orion.VOrionStorage.delete(VOrionStorage.java:52)` which prints a stack trace and returns.
then in `VFile.flushWorkingCopy` we execute the `this.workingCopy.renameTo(this.file);` which I think attempts to rename the claro1.css.workingcopy to the claro1.css which fails because claro1.css did not get deleted. The rename then removes the claro1.css.workingcopy So at this point we have lost all the users changes (in this case only the button color change). 

So we have a couple of things that need to be addressed:
1) Why can we not delete the css file when it is present. note after this first failure all following saves (delete renames work)
2) If the delete throws we need to bubble it up to at least `VFile.flushWorkingCopy` to ensure that the rename of the workingcopy does not happen.
