### ISSUE TITLE
Unfulfilled promise in Custom Widget with sliders

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3962]
Created a custom widget, a DIV with two Dijit sliders.
Open a new document and place the custom widget on the canvas.
Close, reopen: get an exception:

```
Error: dijit._Templated: parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin.   Must pre-load all supporting widgets before instantiation.
    at _2._beforeFillContent (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dijit/_WidgetsInTemplateMixin.js:8:7)
    at _200.buildRendering (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dijit/dijit.js:2092:6)
    at _8f.create (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dijit/dijit.js:477:6)
    at _8f.postscript (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dijit/dijit.js:455:6)
    at new <anonymous> (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dojo/dojo.js:3133:3)
    at Object._1b.construct (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dojo/parser.js:228:30)
    at Object.<anonymous> (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dojo/parser.js:74:13)
    at Object._581.map (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dojo/dojo.js:6811:13)
    at Object._1b._instantiate (http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dojo/parser.js:69:12)
    at http://maqetta-app-test.austin.ibm.com/maqetta/user/E/ws/workspace/newproj/lib/dojo/dojo/parser.js:409:27 davinci.js:55217
```

**Comment by peller** [comment]
@JonFerraiolo 
If you first place a slider on the page, then the custom widget, everything works fine.  I'm guessing it has to do with the compound dijits used in construction of a slider.

The same test using simple widgets like button and calendar works fine

**Comment by PunkChameleon** [comment]
Can you provide more details? Having very similar issue and is driving me mad (semi-related to this; SO post here -- https://stackoverflow.com/questions/25168372/parser-returned-unfilled-promise-error-in-dojo)
