### ISSUE TITLE
WARN::ERROR:  /maqetta/user/_Guest_1303911791900/.....

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#48]
these WARN:ERRORs started showing up in the log after we installed the new
build on maqetta.org. they are repeated for many different files, but all were
under a "TryIt" guest account.
2011-04-28 16:24:03.681:WARN::ERROR: 
/maqetta/user/_Guest_1303986828715/ws/workspace/welcome
2011-04-28 16:24:08.901:WARN::ERROR: 
/maqetta/user/_Guest_1303986828715/ws/workspace/welcome
2011-04-28 16:55:52.739:WARN::ERROR:  /maqetta/cmd/download
2011-04-28 19:11:16.734:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/StackController.js
2011-04-28 19:11:17.373:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/ContentPane.js
2011-04-28 19:11:16.734:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/StackContainer.js
2011-04-28 19:11:29.081:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/MenuSeparator.js
2011-04-28 19:11:29.081:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/CheckedMenuItem.js
2011-04-28 19:11:31.224:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/regexp.js
2011-04-28 19:11:31.325:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/html.js
2011-04-28 19:11:31.325:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/ScrollingTabController.js
2011-04-29 00:12:54.695:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/date.js
2011-04-29 00:12:59.098:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/form/TextBox.js
2011-04-29 00:13:01.366:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/date/locale.js
2011-04-29 00:13:01.368:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/cldr/supplemental.js
2011-04-29 00:14:28.730:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/Calendar.js
2011-04-29 00:14:30.353:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/maqetta/maqetta.js
2011-04-29 03:15:40.028:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/dojo.js
2011-04-29 03:16:49.041:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/dijit.js
2011-04-29 03:53:55.613:WARN::ERROR: 
/maqetta/user/_Guest_1303639043877/ws/workspace/Sample1.html
2011-04-29 04:59:24.572:WARN::ERROR:  /maqetta/cmd/saveFile
2011-04-29 04:59:30.890:WARN::ERROR:  /maqetta/cmd/saveFile
2011-04-29 04:59:37.812:WARN::ERROR:  /maqetta/cmd/saveFile
2011-04-29 04:59:43.445:WARN::ERROR:  /maqetta/cmd/saveFile
2011-04-29 05:12:35.718:WARN::ERROR:  /maqetta/cmd/deleteResource
2011-04-29 05:12:46.516:WARN::ERROR:  /maqetta/cmd/deleteResource
2011-04-29 05:17:35.708:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/cldr/nls/en/gregorian.js
2011-04-29 05:17:35.709:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/PopupMenuItem.js
2011-04-29 05:17:35.710:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/form/Button.js
2011-04-29 05:17:35.821:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/_TabContainerBase.js
2011-04-29 05:17:36.334:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/cookie.js
2011-04-29 05:17:36.335:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/Menu.js
2011-04-29 05:17:36.435:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/nls/loading.js
2011-04-29 05:17:53.487:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/TabContainer.js
2011-04-29 05:17:53.588:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/form/ToggleButton.js
2011-04-29 05:17:53.588:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/layout/TabController.js
2011-04-29 05:17:53.895:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/_HasDropDown.js
2011-04-29 05:17:54.918:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/MenuItem.js
2011-04-29 05:17:56.176:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/nls/common.js
2011-04-29 05:17:56.188:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dojo/i18n.js
2011-04-29 05:17:56.285:WARN::ERROR: 
/maqetta/user/_Guest_1303911791900/ws/workspace/lib/dojo/dijit/_KeyNavContainer.js
2011-04-29 09:07:50.645:WARN::ERROR:  /maqetta/cmd/deleteResource
2011-04-29 09:07:52.265:WARN::ERROR:  /maqetta/cmd/rename
2011-04-29 09:07:52.302:WARN::ERROR:  /maqetta/cmd/loadFile
2011-04-29 09:08:04.388:WARN::ERROR:  /maqetta/cmd/loadFile

followed by this exception:

java.lang.NullPointerException
        at org.davinci.server.DavinciPageServlet.handleLibraryRequest(Unknown
Source)
        at org.davinci.server.DavinciPageServlet.handleWSRequest(Unknown
Source)
        at org.davinci.server.DavinciPageServlet.doGet(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at
org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
        at
org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at
org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:28)
        at
org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:154)
        at
org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
        at
org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:71)
        at
org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:25)
        at
org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:130)
        at
org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:76)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at
org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManage
r.java:318)
        at
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at
org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at
org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at
org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at
org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at
org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at
org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at
org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
        at
org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by waynevicknair** [comment]
Jon, I just tested this on today's build by handcrafting a tryIt URL (http://localhost:50000/maqetta/cmd/tryIt). I don't see any exceptions during editing. I do see several "Library file not found!" messages, but they are valid as they refer to jquery and yui, the libraries that are indeed not present in the internal build.

**Comment by JonFerraiolo** [comment]
So we should close this bug now? If yes, please close.
