### ISSUE TITLE
Create new html file is very slow

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#575]
it seems to be spending most of its time (>5 sec) in findResource.  Brad, when you have a chance, can you take a look?

**Comment by JonFerraiolo** [comment]
@jhpedemonte

Adam, thanks for researching this. Too slow to ship, so this is an M2 requirement.

**Comment by childsb** [comment]
I see a 293MS delay on findResource, which is on par with save and load operation.  (less than 1/3 of a second).  verified with adam that he's not seeing the 5 second delay any longer so closing the bug..

**Comment by peller** [comment]
today, I get this and can't run the app:

```

19:44:18.974 [1836684604@qtp-2134019194-1 - Acceptor0 SelectChannelConnector@0.0.0.0:8080] ERROR org.mortbay.log - EXCEPTION 
java.lang.OutOfMemoryError: Java heap space
    at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:45) ~[na:1.6.0_24]
    at java.lang.StringBuilder.<init>(StringBuilder.java:68) ~[na:1.6.0_24]
    at java.lang.Object.toString(Object.java:219) ~[na:1.6.0_24]
    at java.lang.String.valueOf(String.java:2826) ~[na:1.6.0_24]
    at java.lang.StringBuffer.append(StringBuffer.java:219) ~[na:1.6.0_24]
    at org.mortbay.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:518) ~[na:na]
    at org.mortbay.io.nio.SelectorManager.doSelect(SelectorManager.java:191) ~[na:na]
    at org.mortbay.jetty.nio.SelectChannelConnector.accept(SelectChannelConnector.java:124) ~[na:na]
    at org.mortbay.jetty.AbstractConnector$Acceptor.run(AbstractConnector.java:707) ~[na:na]
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) ~[na:na]
19:44:18.976 [127861719@qtp-2134019194-2 - /maqetta/cmd/findResource?path=*.theme&ignoreCase=true] ERROR org.mortbay.log - Error for /maqetta/cmd/findResource
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2882) ~[na:1.6.0_24]
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100) ~[na:1.6.0_24]
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:390) ~[na:1.6.0_24]
    at java.lang.StringBuilder.append(StringBuilder.java:119) ~[na:1.6.0_24]
    at java.io.UnixFileSystem.resolve(UnixFileSystem.java:93) ~[na:1.6.0_24]
    at java.io.File.<init>(File.java:312) ~[na:1.6.0_24]
    at org.eclipse.osgi.baseadaptor.bundlefile.DirBundleFile.getEntry(DirBundleFile.java:48) ~[na:na]
    at org.eclipse.osgi.baseadaptor.BaseData.getEntry0(BaseData.java:111) ~[na:na]
    at org.eclipse.osgi.baseadaptor.BaseData.getEntry(BaseData.java:102) ~[na:na]
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.getEntry0(AbstractBundle.java:1236) ~[na:na]
    at org.eclipse.osgi.framework.internal.core.AbstractBundle$6.getNextElement(AbstractBundle.java:1434) ~[na:na]
    at org.eclipse.osgi.framework.internal.core.AbstractBundle$6.nextElement(AbstractBundle.java:1422) ~[na:na]
    at org.davinci.ajaxLibrary.LibraryManager$BundleLibraryInfo.find(LibraryManager.java:69) ~[na:na]
    at org.davinci.server.VLibraryResource.listFiles(VLibraryResource.java:118) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:234) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
    at org.davinci.server.VLibraryResource.findChildren(VLibraryResource.java:258) ~[na:na]
19:44:18.977 [127861719@qtp-2134019194-2 - /maqetta/cmd/findResource?path=*.theme&ignoreCase=true] DEBUG org.mortbay.log - GET /maqetta/cmd/findResource?path=*.theme&ignoreCase=true HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Referer: http://localhost:8080/maqetta/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_7) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100 Safari/534.30
Accept: */*
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Cookie: JSESSIONID=v4lb8cskxts1jsd9zz6vqxlj; SaveStateCookie=myapp; resourceTreeSaveStateCookie=.; reviewResourceTreeSaveStateCookie=.review%2Fsnapshot
X-Requested-With: XMLHttpRequest
Content-Type: application/x-www-form-urlencoded


19:44:18.979 [127861719@qtp-2134019194-2 - /maqetta/cmd/findResource?path=*.theme&ignoreCase=true] DEBUG org.mortbay.log - RESPONSE /maqetta/cmd/findResource  500
19:44:18.982 [1836684604@qtp-2134019194-1 - Acceptor0 SelectChannelConnector@0.0.0.0:8080] INFO  org.mortbay.log - org.mortbay.io.nio.SelectorManager$SelectSet@de16483 JVM BUG(s) - canceled keys 1 times
19:44:19.281 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - REQUEST /maqetta/cmd/setWorkbenchState on org.mortbay.jetty.HttpConnection@3b8e609b
19:44:19.281 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - Got Session ID v4lb8cskxts1jsd9zz6vqxlj from cookie
19:44:19.281 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@7ca522a6
19:44:19.281 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - session=org.mortbay.jetty.servlet.HashSessionManager$Session:v4lb8cskxts1jsd9zz6vqxlj@264829771
19:44:19.281 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - servlet=org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-1547917882
19:44:19.281 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - chain=null
19:44:19.281 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - servlet holder=org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-1547917882
19:44:19.282 [127861719@qtp-2134019194-2 - /maqetta/cmd/setWorkbenchState] DEBUG org.mortbay.log - RESPONSE /maqetta/cmd/setWorkbenchState  200
19:44:19.506 [127861719@qtp-2134019194-2 - /favicon.ico] DEBUG org.mortbay.log - REQUEST /favicon.ico on org.mortbay.jetty.HttpConnection@3b8e609b
19:44:19.507 [127861719@qtp-2134019194-2 - /favicon.ico] DEBUG org.mortbay.log - RESPONSE /favicon.ico  200
19:44:22.697 [127861719@qtp-2134019194-2 - /maqetta/app/dijit/themes/claro/layout/images/splitterHorizontalHover.png] DEBUG org.mortbay.log - REQUEST /maqetta/app/dijit/themes/claro/layout/images/splitterHorizontalHover.png on org.mortbay.jetty.HttpConnection@3b8e609b
19:44:22.697 [127861719@qtp-2134019194-2 - /maqetta/app/dijit/themes/claro/layout/images/splitterHorizontalHover.png] DEBUG org.mortbay.log - Got Session ID v4lb8cskxts1jsd9zz6vqxlj from cookie
19:44:22.698 [127861719@qtp-2134019194-2 - /maqetta/app/dijit/themes/claro/layout/images/splitterHorizontalHover.png] DEBUG org.mortbay.log - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@7ca522a6
19:44:22.698 [127861719@qtp-2134019194-2 - /maqetta/app/dijit/themes/claro/layout/images/splitterHorizontalHover.png] DEBUG org.mortbay.log - session=org.mortbay.jetty.servlet.HashSessionManager$Session:v4lb8cskxts1jsd9zz6vqxlj@264829771
19:44:22.698 [127861719@qtp-2134019194-2 - /maqetta/app/dijit/themes/claro/layout/images/splitterHorizontalHover.png] DEBUG org.mortbay.log - servlet=org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-1547917882
19:44:22.698 [127861719@qtp-2134019194-2 - /maqetta/app/dijit/themes/claro/layout/images/splitterHorizontalHover.png] DEBUG org.mortbay.log - chain=null
```

**Comment by peller** [comment]
see also #603
