### ISSUE TITLE
dijit.css is now read-only, breaking some operations in Properties palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#582]
@billreed63, @jhpedemonte
- Create a new theme (e.g., a1)
- Create a new HTML page
- Switch theme to a1
- Add a TextBox
- In Properties palette, go to Layout section and open up CSS Cascade UI for 'width'. Notice that the target rule is:

.dijitTextBox (themes/dijit.css line:undefined) width:15em;
- Change width to 16em with the above rule selected. 

Result=> In VE, the width changes to 16em, but the browser console shows a server error on the PUT operation and the server console prints out some error messages. The reason is that dijit.css is currently read-only, even if using a cloned theme.

Unfortunately, the correct fix might be a non-trivial amount of work. I've labeled this as M2, but it might be too involved and too risky for that milestone.

What we really need is that dijit.css is read-only for claro and sketch but read-write for cloned themes. My recommendation for the right way to fix this is to reorganize themes/ folder to look like this

   ./themes/
      <themename>/
         dijit.css
         <themename>/
             ...many css files...

Then the theme cloning operation would copy the tree starting with the outer <themename> folder. This makes it so that there is a separate copy of dijit.css for each theme. We need this because some CSS rules are in the dijit.css file and we don't want CSS changes from one theme to affect a different theme.

**Comment by childsb** [comment]
@billreed63 - how much work would it be to move the files around?

If it's a lot, I would suggest we just make the dijit files read/write for the users workspace on this release, and move the next release.  As of now, we have 3 plugins with 2 themes each to modify metadata and imports for.  this might be a little much.

let me know if we should go the quick fix approach and i can do the change.

**Comment by billreed63** [comment]
I might be missing something but I think all we have to do is copy dijit.css and dijit_rtl.css to the claro and sketch theme folders. then change the `@import url("../dijit.css");` in claro.css and sketch...

**Comment by JonFerraiolo** [comment]
Sounds like we are converging on both a Plan A (longer-term) and Plan B (short-term - just copy dijit.css and dijit-rtl-css). My gut is telling me to go with Plan B for now and not attempt Plan A for M2.

But if we go with Plan B for the short-term and then Plan A down the road, what is the impact in terms of migrating user workspaces to deal with URL changes? The URLs for theme CSS files will change with Plan A. Instead of <link href="themes/claro/claro.css">, with my original proposal it will be <link href="themes/claro/claro/claro.css>. User HTML files would need to be changed. I think that's doable, but non-trivial.

**Comment by billreed63** [comment]
I just tested this and it works, do you want me to commit the fix?

**Comment by jhpedemonte** [comment]
Still seeing some issues with latest build (July 5). Run the PropertiesPalette2 test plan, _Layout Properties_.  I'm able to complete step 7 (set width for **TextBox**), but get errors when doing step 8 (set width/height on **Calendar**).

I get this on the browser's error console:

> PUT http://localhost:50000/maqetta/cmd/saveFile?path=.%2Fthemes%2Fclaro%2Fdijit.css&isWorkingCopy=true 500 (Internal Server Error)
> Error: Unable to load ./cmd/saveFile?path=.%2Fthemes%2Fclaro%2Fdijit.css&isWorkingCopy=true status:500
> Error: Unable to load ./cmd/saveFile?path=.%2Fthemes%2Fclaro%2Fdijit.css&isWorkingCopy=true status:500

And I see this in the console running the server:

```
2011-07-05 08:54:40.863:WARN::ERROR:  /maqetta/cmd/saveFile
java.lang.NullPointerException
    at org.davinci.server.Command.transferStreams(Unknown Source)
    at org.davinci.server.internal.command.SaveFile.handleCommand(Unknown Source)
    at org.davinci.server.DavinciCommandServlet.doPut(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:730)
    at org.davinci.server.DavinciCommandServlet.service(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:126)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:939)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

So it's still trying to save **dijit.css** but failing.

**Comment by billreed63** [comment]
This looks, like it is attempting to change claro which is read only

July 2011
