### ISSUE TITLE
download themes/claro folder results in server exception

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#714]
- select themes/claro (or sketch) in the file explorer
- ctrl-click (mac) and choose download
- the file that comes down is empty (0 bytes)  The following appears on the server console:

00:16:44.579 [181720683@qtp-2038975040-1 - Acceptor0 SelectChannelConnector@0.0.0.0:8080] INFO  org.mortbay.log - org.mortbay.io.nio.SelectorManager$SelectSet@48a826da JVM BUG(s) - canceled keys 7 times
00:16:46.558 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - REQUEST /maqetta/cmd/download on org.mortbay.jetty.HttpConnection@7a0aae8a
00:16:46.558 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - Got Session ID 1stv4410fp4jj10kne8mrhnymq from cookie
00:16:46.558 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@79a61172
00:16:46.558 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - session=org.mortbay.jetty.servlet.HashSessionManager$Session:1stv4410fp4jj10kne8mrhnymq@1521508299
00:16:46.558 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - servlet=org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-222237550
00:16:46.558 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - chain=null
00:16:46.558 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - servlet holder=org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-222237550
00:16:46.563 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] WARN  org.mortbay.log - /maqetta/cmd/download
java.io.IOException: Closed
    at org.mortbay.jetty.HttpConnection$Output.print(HttpConnection.java:1016) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.davinci.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:56) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[javax.servlet_2.5.0.v200910301333.jar:na]
    at org.davinci.server.DavinciCommandServlet.service(DavinciCommandServlet.java:108) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) ~[javax.servlet_2.5.0.v200910301333.jar:na]
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:126) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) ~[javax.servlet_2.5.0.v200910301333.jar:na]
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318) ~[org.eclipse.equinox.http.jetty_2.0.0.v20100503.jar:na]
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.Server.handle(Server.java:322) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [org.mortbay.jetty.util_6.1.23.v201004211559.jar:na]
00:16:46.563 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - GET /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Referer: http://localhost:8080/maqetta/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_7) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Cookie: reviewResourceTreeSaveStateCookie=.review%2Fsnapshot; reviewWizardSourceTreeSaveStateCookie=.; JSESSIONID=1stv4410fp4jj10kne8mrhnymq; reviewCommentExplorerViewTreeSaveStateCookie=.review%2Fsnapshot; fileDialogFolderTreeSaveStateCookie=.; SaveStateCookie=.%2FSampleJs.js%2Cmyapp%2Cdiv_0%2Cdiv_1%2Cspan_0%2Cundefined%2C.%2Fapp.css; resourceTreeSaveStateCookie=.%2C.%2Fsample_data%2C.%2Fmaqetta%2C.%2Flib%2C.%2Flib%2Fdojo%2C.%2Flib%2Fdojo%2Fdojox%2C.%2Fthemes%2C.%2Flib%2Fdojo%2Fdojox%2Feditor%2C.%2Flib%2Fdojo%2Fdojox%2Feditor%2Fplugins%2C.%2Flib%2Fdojo%2Fdojox%2Feditor%2Fplugins%2Fresources%2C.%2Flib%2Fdojo%2Fdojox%2Feditor%2Fplugins%2Fresources%2Fimages%2C.%2Ffolder1%2C.%2Fggg%2C.%2Faaaa

00:16:46.564 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - Response already committed for handling java.io.IOException: Closed
00:16:46.564 [525734967@qtp-2038975040-81 - /maqetta/cmd/download?fileName=downloadxxz.zip&resources=%5B%22./themes/claro%22%5D] DEBUG org.mortbay.log - RESPONSE /maqetta/cmd/download  200

**Comment by peller** [comment]
in org.davinci.server.internal.command.Download.handleCommand, close is called twice, I think... then an additional time from org.davinci.server.DavinciCommandServlet.doGet

I think the zos.close() should be sufficient and will close the parent stream.  The catch(IOException) surrounding that should probably re-throw?  close() calls and temp file cleanup should be in finally blocks.

**Comment by childsb** [comment]
resolved the exception with commit 26fd45e77e0972d49e15a9f1a58fe058b2cfca61
