### ISSUE TITLE
New File... in themes folder results in errors, no meaningful error UI

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#981]
themes is a read-only folder, so perhaps it should fail.  Right now, there appears to be an unhandled exception and a 500 from the server, and several exceptions result on the client.  The only visible UI is an alert dialog, and the contents are 'undefined'.

serverJSONRequest probably should pass in an error handler to the dojo.xhr call rather than test for response=="OK"  davinci.Runtime.serverJSONRequest probably should not substitute its own error handler with console messages for 4xx codes.  Right now, there appear to be three error handlers registered to log messages to the console.  There's also a reference error.  Not sure where it's coming from.

```
00:27:20.201 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - REQUEST /maqetta/cmd/createResource on org.mortbay.jetty.HttpConnection@4f2d26d2
00:27:20.201 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - Got Session ID 10fkomlihu20r1omfxflhr9k6r from cookie
00:27:20.202 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@7d5718f2
00:27:20.202 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - session=org.mortbay.jetty.servlet.HashSessionManager$Session:10fkomlihu20r1omfxflhr9k6r@1522338280
00:27:20.202 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - servlet=org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-909053268
00:27:20.202 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - chain=null
00:27:20.202 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - servlet holder=org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-909053268
00:27:20.289 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] WARN  org.mortbay.log - /maqetta/cmd/createResource
java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.6.0_26]
    at java.io.File.createNewFile(File.java:883) ~[na:1.6.0_26]
    at org.davinci.server.VFile.createNewInstance(VFile.java:120) ~[na:na]
    at org.davinci.server.internal.command.CreateResource.handleCommand(CreateResource.java:32) ~[na:na]
    at org.davinci.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:51) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[javax.servlet_2.5.0.v200910301333.jar:na]
    at org.davinci.server.DavinciCommandServlet.service(DavinciCommandServlet.java:108) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) ~[javax.servlet_2.5.0.v200910301333.jar:na]
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:126) ~[na:na]
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) ~[javax.servlet_2.5.0.v200910301333.jar:na]
    at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:318) ~[org.eclipse.equinox.http.jetty_2.0.0.v20100503.jar:na]
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.Server.handle(Server.java:322) ~[org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409) [org.mortbay.jetty.server_6.1.23.v201004211559.jar:na]
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [org.mortbay.jetty.util_6.1.23.v201004211559.jar:na]
00:27:20.289 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - GET /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Referer: http://localhost:8080/maqetta/
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.218 Safari/535.1
Content-Type: application/x-www-form-urlencoded
Accept: */*
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Cookie: JSESSIONID=10fkomlihu20r1omfxflhr9k6r; resourceTreeSaveStateCookie=.%2Fproject1; reviewCommentExplorerViewTreeSaveStateCookie=.review%2Fsnapshot; SaveStateCookie=myapp; fileDialogFolderTreeSaveStateCookie=.%2Fproject1


00:27:20.290 [32685607@qtp-196244428-44 - /maqetta/cmd/createResource?path=.%2Fproject1%2Fthemes%2Ffile1.html&isFolder=false] DEBUG org.mortbay.log - RESPONSE /maqetta/cmd/createResource  500
```

**Comment by childsb** [comment]
fixed by marking library folders read only and preventing new files in read only folders.
